//! The flyer: a low-poly 3D anteater (Adrian, 2026-10-01: "a low poly 3D
//! anteater seen from the same perspective, like the tilted above view as
//! the rest of the view"). The mesh in anteater_mesh.zig (generated by
//! tools/anteater_mesh.py) is posed every frame (forelegs flap about their
//! shoulder pivots, the head sways, the body rolls with the bank), tilted by
//! the camera's own downward view, lit by one directional light, projected
//! with the march's horizontal scale (px_per_tan 100) at a fixed distance
//! ahead of the camera, and rasterised as flat-shaded triangles with a
//! painter's sort. All integer: Q16 for the pose, Q4 screen coordinates for
//! the edge functions, 4 shades per material. No comptime work.
const cart = @import("cart-api");
const fixed = @import("fixed.zig");
const camera = @import("camera.zig");
const mesh = @import("anteater_mesh.zig");

// --- Knobs ------------------------------------------------------------------

/// The one constant that removes the avatar (draw compiles to nothing).
pub const show_avatar = true;
/// Screen anchor: the model's origin projects here at the rest pose.
const anchor_x: i32 = 80;
const anchor_y: i32 = 101;
/// Distance of the model origin ahead of the eye, Q16 model units, and the
/// projection scale (pixels per unit at distance 1; the march's px_per_tan).
const dist: i32 = (52 << 16) / 10;
const scale: i32 = 100;
/// Camera tilt in 1/1024 turns at the level horizon (24 degrees), and its
/// change per row the horizon moves (diving lowers the tilt).
const tilt_level: i32 = 68;
const tilt_per_row: i32 = 1;
/// Roll of the model per Q16 row of horizon shear (2 units per row: 20 rows
/// of shear reads as 14 degrees of bank).
const roll_per_row: i32 = 2;
/// Flap: amplitude in 1/1024 turns (100 = 35 degrees) and frames per cycle (power of two).
const flap_amp: i32 = 100;
const flap_period_log2: u5 = 5; // 32 frames
/// Head sway: amplitude (110 = 39 degrees) and period.
const sway_amp: i32 = 110;
const sway_period_log2: u5 = 7; // 128 frames
/// Body bob with the flap, Q16 units.
const bob_amp: i32 = 6554; // 0.1
/// Light direction in camera space (x right, y up, z forward), Q8, unit length:
/// the Iris sun ahead and above, a little to the left.
const light = [3]i32{ -83, 190, 150 };
/// Shade factors per level in 1/256: in shadow, grazing, lit, full.
const shade_mul = [4]u32{ 140, 185, 225, 256 };
/// Clip box on screen (the caption is at row 119).
const clip_x0: i32 = 20;
const clip_x1: i32 = 140;
const clip_y0: i32 = 56;
const clip_y1: i32 = 118;

// --- State ------------------------------------------------------------------

const n_verts = mesh.verts.len;
const n_tris = mesh.tris.len;

/// Projected vertices in Q4 screen pixels (clamped to i16), and camera-space
/// position in Q6 units (for normals; the model is within 8 units).
var sx: [n_verts]i16 = undefined;
var sy: [n_verts]i16 = undefined;
var cx: [n_verts]i16 = undefined;
var cy: [n_verts]i16 = undefined;
var cz: [n_verts]i16 = undefined;
/// Visible triangles this frame: index and depth key, sorted far to near.
var order: [n_tris]u8 = undefined;
var depth: [n_tris]i16 = undefined;
var shade_of: [n_tris]u8 = undefined;
/// Colour per (material, shade), ready-to-store pixels.
var colours: [4][4]cart.Pixel = undefined;
var frame_count: u32 = 0;

pub fn init() void {
    for (mesh.material_rgb, 0..) |rgb, m| {
        for (shade_mul, 0..) |k, s| {
            const r = ((rgb >> 16) & 0xFF) * k >> 8;
            const g = ((rgb >> 8) & 0xFF) * k >> 8;
            const b = (rgb & 0xFF) * k >> 8;
            colours[m][s] = .from_color(.{
                .r = @intCast((r * 31 + 127) / 255),
                .g = @intCast((g * 63 + 127) / 255),
                .b = @intCast((b * 31 + 127) / 255),
            });
        }
    }
}

/// Pose, project, sort and fill the anteater over the finished terrain.
pub fn draw() void {
    if (!show_avatar) return;
    const f = frame_count;
    frame_count +%= 1;
    const cam = camera.cam;

    // Pose angles in 1/1024 turns.
    const flap = fixed.mul(flap_amp << 16, camera.sin(@intCast((f << (10 - flap_period_log2)) & 1023))) >> 16;
    const sway = fixed.mul(sway_amp << 16, camera.sin(@intCast((f << (10 - sway_period_log2)) & 1023))) >> 16;
    const roll = (cam.roll * roll_per_row) >> 16;
    const tilt = tilt_level - (cam.horizon - 64) * tilt_per_row;
    const bob = fixed.mul(bob_amp, camera.cos(@intCast((f << (10 - flap_period_log2)) & 1023)));

    const sin_r = camera.sin(roll);
    const cos_r = camera.cos(roll);
    const sin_t = camera.sin(tilt);
    const cos_t = camera.cos(tilt);
    const sin_f = camera.sin(flap);
    const cos_f = camera.cos(flap);
    const sin_s = camera.sin(sway);
    const cos_s = camera.cos(sway);

    // Transform every vertex: bone, roll about z, tilt about x, translate, project.
    for (mesh.verts, 0..) |v, i| {
        var x: i32 = @as(i32, v.x) << 8; // 1/256 units -> Q16
        var y: i32 = @as(i32, v.y) << 8;
        var z: i32 = @as(i32, v.z) << 8;
        switch (v.bone) {
            1, 2 => {
                const p = mesh.pivots[v.bone];
                const px = @as(i32, p[0]) << 8;
                const py = @as(i32, p[1]) << 8;
                const dx = x - px;
                const dy = y - py;
                // The left foreleg flaps the other way round so both rise together.
                const s = if (v.bone == 2) sin_f else -sin_f;
                x = px + fixed.mul(dx, cos_f) - fixed.mul(dy, s);
                y = py + fixed.mul(dx, s) + fixed.mul(dy, cos_f);
            },
            3 => {
                const p = mesh.pivots[3];
                const px = @as(i32, p[0]) << 8;
                const pz = @as(i32, p[2]) << 8;
                const dx = x - px;
                const dz = z - pz;
                x = px + fixed.mul(dx, cos_s) + fixed.mul(dz, sin_s);
                z = pz - fixed.mul(dx, sin_s) + fixed.mul(dz, cos_s);
            },
            else => {},
        }
        y += bob;
        // Roll about z.
        const xr = fixed.mul(x, cos_r) - fixed.mul(y, sin_r);
        const yr = fixed.mul(x, sin_r) + fixed.mul(y, cos_r);
        // Tilt about x: the camera looks down, so the top turns toward the eye.
        const yt = fixed.mul(yr, cos_t) + fixed.mul(z, sin_t);
        const zt = -fixed.mul(yr, sin_t) + fixed.mul(z, cos_t) + dist;
        cx[i] = @intCast(xr >> 10);
        cy[i] = @intCast(yt >> 10);
        cz[i] = @intCast(zt >> 10);
        // Project to Q4 pixels: anchor + coord * scale / z.
        sx[i] = clamp16((anchor_x << 4) + @as(i32, @intCast(@divTrunc(@as(i64, xr) * (scale << 4), zt))));
        sy[i] = clamp16((anchor_y << 4) - @as(i32, @intCast(@divTrunc(@as(i64, yt) * (scale << 4), zt))));
    }

    // Cull, light and sort (insertion sort, far to near).
    var n: usize = 0;
    for (mesh.tris, 0..) |t, ti| {
        const a = t.a;
        const b = t.b;
        const c = t.c;
        // Screen-space area: the mesh winds counter-clockwise seen from outside
        // with y up; with screen y down (and x right) a front face has
        // positive area here.
        const area = (@as(i32, sx[b]) - sx[a]) * (@as(i32, sy[c]) - sy[a]) - (@as(i32, sx[c]) - sx[a]) * (@as(i32, sy[b]) - sy[a]);
        if (area <= 0) continue;
        // Normal in camera space (Q6 coordinates) and the light.
        const e1x = @as(i32, cx[b]) - cx[a];
        const e1y = @as(i32, cy[b]) - cy[a];
        const e1z = @as(i32, cz[b]) - cz[a];
        const e2x = @as(i32, cx[c]) - cx[a];
        const e2y = @as(i32, cy[c]) - cy[a];
        const e2z = @as(i32, cz[c]) - cz[a];
        const nx = e1y * e2z - e1z * e2y;
        const ny = e1z * e2x - e1x * e2z;
        const nz = e1x * e2y - e1y * e2x;
        const nl: i64 = @as(i64, nx) * light[0] + @as(i64, ny) * light[1] + @as(i64, nz) * light[2];
        const nn: u64 = @as(u64, @intCast(@as(i64, nx) * nx + @as(i64, ny) * ny + @as(i64, nz) * nz));
        const len: i64 = @intCast(isqrt(nn)); // |n| in Q6 units squared... same scale as nl / 256
        const ratio: i64 = if (len == 0) 0 else @divTrunc(nl, len); // Q8 cosine
        shade_of[ti] = if (ratio <= 0) 0 else if (ratio < 90) 1 else if (ratio < 180) 2 else 3;
        const key: i16 = @intCast(@as(i32, cz[a]) + cz[b] + cz[c]);
        // Insert far first (largest key first).
        var j = n;
        while (j > 0 and depth[j - 1] < key) : (j -= 1) {
            order[j] = order[j - 1];
            depth[j] = depth[j - 1];
        }
        order[j] = @intCast(ti);
        depth[j] = key;
        n += 1;
    }

    for (order[0..n]) |ti| {
        const t = mesh.tris[ti];
        fill(sx[t.a], sy[t.a], sx[t.b], sy[t.b], sx[t.c], sy[t.c], colours[t.mat][shade_of[ti]]);
    }
}

/// Flat triangle in Q4 screen coordinates (positive area as computed in draw), clipped to the box.
fn fill(x0: i32, y0: i32, x1: i32, y1: i32, x2: i32, y2: i32, px: cart.Pixel) void {
    const min_x = @max(clip_x0, (@min(x0, @min(x1, x2)) + 15) >> 4);
    const max_x = @min(clip_x1, (@max(x0, @max(x1, x2))) >> 4);
    const min_y = @max(clip_y0, (@min(y0, @min(y1, y2)) + 15) >> 4);
    const max_y = @min(clip_y1, (@max(y0, @max(y1, y2))) >> 4);
    if (min_x > max_x or min_y > max_y) return;
    // Edge functions E(p) = (bx-ax)(py-ay) - (by-ay)(px-ax) at pixel centres;
    // with the winding kept by draw, all three are >= 0 inside.
    const a01 = y0 - y1;
    const b01 = x1 - x0;
    const a12 = y1 - y2;
    const b12 = x2 - x1;
    const a20 = y2 - y0;
    const b20 = x0 - x2;
    const psx = (min_x << 4) + 8;
    const psy = (min_y << 4) + 8;
    var w0_row = a12 * (psx - x1) + b12 * (psy - y1);
    var w1_row = a20 * (psx - x2) + b20 * (psy - y2);
    var w2_row = a01 * (psx - x0) + b01 * (psy - y0);
    var y = min_y;
    while (y <= max_y) : (y += 1) {
        var w0 = w0_row;
        var w1 = w1_row;
        var w2 = w2_row;
        var x = min_x;
        while (x <= max_x) : (x += 1) {
            if (w0 >= 0 and w1 >= 0 and w2 >= 0)
                cart.framebuffer[@intCast(x)][@intCast(y)] = px;
            w0 += a12 << 4;
            w1 += a20 << 4;
            w2 += a01 << 4;
        }
        w0_row += b12 << 4;
        w1_row += b20 << 4;
        w2_row += b01 << 4;
    }
}

inline fn clamp16(v: i32) i16 {
    return @intCast(@max(-32768, @min(32767, v)));
}

/// Integer square root of a u64.
fn isqrt(v: u64) u64 {
    if (v == 0) return 0;
    var x: u64 = @as(u64, 1) << @intCast((64 - @clz(v) + 1) / 2);
    while (true) {
        const y = (x + v / x) / 2;
        if (y >= x) return x;
        x = y;
    }
}
