//! The flyer: a flying anteater (Adrian, 2026-09-30: "a flying anteater
//! would be great and quite amusing and cute ... flapping his lil arms"),
//! drawn at bottom-centre after the terrain. Side profile facing the flight
//! direction: long drooping snout, humped back, the giant anteater's dark
//! shoulder band, a bushy tail streaming behind, one stubby arm flapping
//! with big claws. Three flap phases (raised, level, down) cycle
//! raised-level-down-level; banking shears the sprite with the horizon.
//! The frames are ASCII rows generated by `tools/anteater.py`
//! (`python3 tools/anteater.py <bg.png> frames.txt`), one byte per pixel:
//! `.` transparent, `o` outline, `b` body, `l` light, `k` band, `c` claw,
//! `e` eye. No comptime work: the rows are string literals read at run time.
const cart = @import("cart-api");
const fixed = @import("fixed.zig");

// --- Knobs ------------------------------------------------------------------

/// The one constant that removes the avatar (draw compiles to nothing).
pub const show_avatar = true;
/// Sprite box: 44x28 at x 58..101, rows 89..116 (the caption sits at 119).
pub const w = 44;
pub const h = 28;
pub const x0 = 80 - w / 2;
pub const y0 = 117 - h;
/// Frames per flap phase (a full flap is 4 phases).
const flap_period: u32 = 5;
/// Bank shear: rows the sprite's edge moves per row of horizon roll across
/// the whole screen (the horizon shears cam.roll rows over 160 columns; the
/// sprite shears by the same slope, so 1/160 row per column per roll row).
const shear_cols: i32 = 160;
/// Colours, 0xRRGGBB.
const outline_rgb: u32 = 0x241C22;
const body_rgb: u32 = 0xB4A48C;
const light_rgb: u32 = 0xECE2CC;
const band_rgb: u32 = 0x3A3038;
const claw_rgb: u32 = 0xFAF6EE;
const eye_rgb: u32 = 0x100C10;

const Frame = [h]*const [w:0]u8;

/// Phase order over the flap cycle.
const cycle = [4]u8{ 0, 1, 2, 1 };

var flap: u32 = 0;

/// Draw the flyer for the camera roll (Q16 rows of horizon shear; banking
/// right is negative roll). Call once per frame after the terrain.
pub fn draw(roll: i32) void {
    if (!show_avatar) return;
    const px = [_]cart.Pixel{
        .from_color(.rgb(outline_rgb)),
        .from_color(.rgb(body_rgb)),
        .from_color(.rgb(light_rgb)),
        .from_color(.rgb(band_rgb)),
        .from_color(.rgb(claw_rgb)),
        .from_color(.rgb(eye_rgb)),
    };
    const fr = &frames[cycle[(flap / flap_period) & 3]];
    flap +%= 1;
    // Shear: column sx is offset by (sx - w/2) * roll / shear_cols rows,
    // positive roll (left side of the horizon low) lowers the left side.
    const slope = @divTrunc(roll, shear_cols); // Q16 rows per column
    for (0..w) |sx| {
        const dy = (slope * (@as(i32, @intCast(sx)) - w / 2) + fixed.one / 2) >> fixed.Q;
        const col = &cart.framebuffer[x0 + sx];
        for (0..h) |sy| {
            const ch = fr[sy][sx];
            if (ch == '.') continue;
            const y = @as(i32, y0) + @as(i32, @intCast(sy)) - dy;
            if (y < 0 or y >= 128) continue;
            col[@intCast(y)] = px[
                switch (ch) {
                    'o' => 0,
                    'b' => 1,
                    'l' => 2,
                    'k' => 3,
                    'c' => 4,
                    else => 5,
                }
            ];
        }
    }
}

/// Flap phases: raised, level, down.
const frames = [3]Frame{
    // phase 0: arms raised
    .{
        "............................................",
        "............................................",
        "............................................",
        "...............................oo...........",
        "..............................occoo.........",
        "..............................occcco........",
        ".............................ooccco.........",
        "........................oo..obbcco..........",
        "..........ooo.....ooooookko.obbbbo..........",
        "......oooobbbooooobbbbbkkkkoobbbbboo........",
        "....oobbbbbbbbbbbbbbbbbbkkklbbbbebbboo......",
        "...obbbbbbbbbbbbbbbbbbbbkkklbbbbbbbbbboo....",
        "..obbbbbbbbbbbbbbbbbbbbbbkkbbbbbbbbbbbbbo...",
        ".obbbbbbbbblbbbbbbbbbbbbbkbbbbbbbbooobbbbo..",
        "obbbbbbllbllblbbbbbbbbbbbbbbbbbboo...ooblbo.",
        "obbblbblbblbllbbbbbbbbbbbbbbbbbbo......oolbo",
        "obbllblbblbblbbbbbbbbbbbbbbbblbbo........olb",
        ".ollbllblbbbbbbbbbbbbbbbbbbbkllbo.........ob",
        "oblbblbbbbbbbbbobbbbbbbbbbbkkklo...........o",
        "bblbbbbbobbooooobbbbbbbbbbbbkko.............",
        "obbbbbbo.oo....obbbbbbbbbbbboo..............",
        ".obbooo........obbbboooooooo................",
        "..oo............oooo........................",
        "............................................",
        "............................................",
        "............................................",
        "............................................",
        "............................................",
    },
    // phase 1: arms level
    .{
        "............................................",
        "............................................",
        "............................................",
        "............................................",
        "............................................",
        "............................................",
        ".............................oo.............",
        "........................oo..obbo............",
        "..........ooo.....ooooookko.obbboo..........",
        "......oooobbbooooobbbbbkkkkoobbbbboo.oo.....",
        "....oobbbbbbbbbbbbbbbbbbkkklbbbbebbbocco....",
        "...obbbbbbbbbbbbbbbbbbbbkkklbbbbbbbbccco....",
        "..obbbbbbbbbbbbbbbbbbbbbbkkllbbbbbbbcccbo...",
        ".obbbbbbbbblbbbbbbbbbbbbbkkbbbbbbbbbbbbbbo..",
        "obbbbbbllbllblbbbbbbbbbbbbbbbbbbbbbooooblbo.",
        "obbblbblbblbllbbbbbbbbbbbbbbbbbbboo....oolbo",
        "obbllblbblbblbbbbbbbbbbbbbbbbbbbo........olb",
        ".ollbllblbbbbbbbbbbbbbbbbbbbkllbo.........ob",
        "oblbblbbbbbbbbbobbbbbbbbbbbkkklo...........o",
        "bblbbbbbobbooooobbbbbbbbbbbbkko.............",
        "obbbbbbo.oo....obbbbbbbbbbbboo..............",
        ".obbooo........obbbboooooooo................",
        "..oo............oooo........................",
        "............................................",
        "............................................",
        "............................................",
        "............................................",
        "............................................",
    },
    // phase 2: arms down
    .{
        "............................................",
        "............................................",
        "............................................",
        "............................................",
        "............................................",
        "............................................",
        ".............................oo.............",
        "........................oo..obbo............",
        "..........ooo.....ooooookko.obbboo..........",
        "......oooobbbooooobbbbbkkkkoobbbbboo........",
        "....oobbbbbbbbbbbbbbbbbbkkklbbbbebbboo......",
        "...obbbbbbbbbbbbbbbbbbbbkkklbbbbbbbbbboo....",
        "..obbbbbbbbbbbbbbbbbbbbbbkkllbbbbbbbbbbbo...",
        ".obbbbbbbbblbbbbbbbbbbbbbkkblbbbbbooobbbbo..",
        "obbbbbbllbllblbbbbbbbbbbbbbbbbbboo...ooblbo.",
        "obbblbblbblbllbbbbbbbbbbbbbbbbbbo......oolbo",
        "obbllblbblbblbbbbbbbbbbbbbbbbbbboo.......olb",
        ".ollbllblbbbbbbbbbbbbbbbbbbbbbbbbbo.......ob",
        "oblbblbbbbbbbbbobbbbbbbbbbbkkbbbbbbo.......o",
        "bblbbbbbobbooooobbbbbbbbbbbbkkobbbbbooo.....",
        "obbbbbbo.oo....obbbbbbbbbbbboo.oobbcccco....",
        ".obbooo........obbbboooooooo.....ooccco.....",
        "..oo............oooo...............oco......",
        "....................................o.......",
        "............................................",
        "............................................",
        "............................................",
        "............................................",
    },
};
