//! The Utah teapot easter egg (SPEC.md sections 4 and 7): a teapot-joint
//! cell draws its two half cylinders and calls `draw` at its centre. Unlike
//! the pipes this is a triangle mesh (`teapot_mesh.zig`, generated by
//! tools/gen_teapot.py, 248 triangles), rasterized with a z test against
//! zbuf.zig and shaded per pixel through shade.zig with the perspective-
//! correct interpolated vertex normal. Drawn once per teapot, so it is
//! written for clarity rather than speed (a 20 px teapot costs well under a
//! millisecond). Generic over the pixel sink like draw.zig.
const std = @import("std");
const math = @import("../math.zig");
const grid = @import("../grid.zig");
const camera = @import("../camera.zig");
const zbuf = @import("zbuf.zig");
const shade = @import("shade.zig");
const mesh = @import("teapot_mesh.zig");

const Vec3 = math.Vec3;

/// Half the teapot's box in its local axes per unit of `size` (x towards
/// the spout, y up, z sideways): with size 1.0 it reaches 1.07 cells from
/// the centre along the spout, 0.5 up and down, 0.67 to the sides.
pub const half_extent = mesh.half_extent;

/// Suggested `size`. A cell is only 8 to 10 px on screen in the fitted
/// views, so 0.6 gives a 5 px blob (about 30 pixels); 1.0 is about 9 px
/// tall and 20 px from spout to handle, spilling into the neighbouring cells
/// (the z buffer sorts that out), which reads as a teapot.
pub const default_size: f32 = 1.0;
pub const triangle_count = mesh.triangles.len;

/// Vertices behind this view depth (world units) skip the whole teapot.
/// Never happens with the fitted views: the camera is outside the grid.
const near: f32 = 0.05;

const cx: f32 = camera.screen_w / 2;
const cy: f32 = camera.screen_h / 2;

/// Per-vertex scratch, filled once per draw (static: no allocation, and the
/// cart has one core). Plain [3]f32 rows like the mesh tables.
var rel: [mesh.positions.len][3]f32 = undefined; // world position - eye
var nrm: [mesh.positions.len][3]f32 = undefined; // world normal
var scr: [mesh.positions.len][3]f32 = undefined; // screen x, y, 1 / view depth

/// Orthonormal right-handed basis for the teapot: `y` = up, `x` = front
/// (the spout's side), `z` = x cross y. A front that is `none` or on the up
/// axis is replaced by the next axis round, so any pair of directions works.
pub fn basis(up: grid.Dir, front: grid.Dir) [3]Vec3 {
    const u: grid.Dir = if (up == .none) .py else up;
    var f = front;
    if (f == .none or f.axis() == u.axis()) {
        const next_axis: u3 = (@as(u3, u.axis()) + 1) % 3;
        f = @fromBackingInt(@intCast(next_axis * 2));
    }
    const x = f.vec();
    const y = u.vec();
    return .{ x, y, math.cross(x, y) };
}

/// Draws the teapot centred on `centre` (world units), local +y along
/// `up`, the spout towards `front`, palette colour `color`, `size` = height
/// in cells (`default_size`). Back faces are culled; every pixel is
/// z tested against zbuf (depth = view depth * zbuf.scale, smaller is
/// nearer) and written with S.put; one S.mark_dirty covers the whole
/// teapot (the box around its projected vertices).
pub fn draw(comptime S: type, cam: *const camera.Camera, centre: Vec3, up: grid.Dir, front: grid.Dir, color: u4, size: f32) void {
    const b = basis(up, front);
    const ax = b[0] * math.splat(size);
    const ay = b[1] * math.splat(size);
    const az = b[2] * math.splat(size);
    const off = centre - cam.eye;

    var x_lo: f32 = std.math.floatMax(f32);
    var y_lo: f32 = std.math.floatMax(f32);
    var x_hi: f32 = -std.math.floatMax(f32);
    var y_hi: f32 = -std.math.floatMax(f32);
    for (mesh.positions, mesh.normals, 0..) |p, n, i| {
        const r = off + ax * math.splat(p[0]) + ay * math.splat(p[1]) + az * math.splat(p[2]);
        const z = math.dot(r, cam.fwd);
        if (z < near) return;
        const iz = 1.0 / z;
        const sx = cx + math.dot(r, cam.right) * camera.focal * iz;
        const sy = cy - math.dot(r, cam.up) * camera.focal * iz;
        const wn = b[0] * math.splat(n[0]) + b[1] * math.splat(n[1]) + b[2] * math.splat(n[2]);
        rel[i] = .{ r[0], r[1], r[2] };
        nrm[i] = .{ wn[0], wn[1], wn[2] };
        scr[i] = .{ sx, sy, iz };
        x_lo = @min(x_lo, sx);
        y_lo = @min(y_lo, sy);
        x_hi = @max(x_hi, sx);
        y_hi = @max(y_hi, sy);
    }
    const rect = clip_rect(x_lo, y_lo, x_hi, y_hi);
    if (rect.is_empty()) return;

    for (mesh.triangles) |t| {
        const r0 = v3(rel[t[0]]);
        // Back face: the outward normal points away from the eye (which
        // sits at rel = 0).
        const fn_ = math.cross(v3(rel[t[1]]) - r0, v3(rel[t[2]]) - r0);
        if (math.dot(fn_, r0) >= 0) continue;
        fill_triangle(S, cam, rect, t, color);
    }
    S.mark_dirty(rect);
}

inline fn v3(a: [3]f32) Vec3 {
    return .{ a[0], a[1], a[2] };
}

/// Fills one front-facing triangle: pixel centres inside all three edges
/// (inclusive), clipped to `rect`; 1/z and normal/z interpolate linearly in
/// screen space, so depth and normal are perspective-correct.
fn fill_triangle(comptime S: type, cam: *const camera.Camera, rect: camera.Rect, t: [3]u16, color: u4) void {
    const a = scr[t[0]];
    const b = scr[t[1]];
    const c = scr[t[2]];
    const area = (b[0] - a[0]) * (c[1] - a[1]) - (c[0] - a[0]) * (b[1] - a[1]);
    if (@abs(area) < 1e-6) return;
    const inv_area = 1.0 / area;

    const fx0 = @max(@floor(@min(a[0], @min(b[0], c[0]))), @as(f32, @floatFromInt(rect.x0)));
    const fy0 = @max(@floor(@min(a[1], @min(b[1], c[1]))), @as(f32, @floatFromInt(rect.y0)));
    const fx1 = @min(@ceil(@max(a[0], @max(b[0], c[0]))), @as(f32, @floatFromInt(rect.x1)));
    const fy1 = @min(@ceil(@max(a[1], @max(b[1], c[1]))), @as(f32, @floatFromInt(rect.y1)));
    if (fx1 <= fx0 or fy1 <= fy0) return;
    const x0: u32 = @intFromFloat(fx0);
    const y0: u32 = @intFromFloat(fy0);
    const x1: u32 = @intFromFloat(fx1);
    const y1: u32 = @intFromFloat(fy1);

    // Normal / z at each corner.
    const na = v3(nrm[t[0]]) * math.splat(a[2]);
    const nb = v3(nrm[t[1]]) * math.splat(b[2]);
    const nc = v3(nrm[t[2]]) * math.splat(c[2]);

    var x = x0;
    while (x < x1) : (x += 1) {
        const px = @as(f32, @floatFromInt(x)) + 0.5;
        var y = y0;
        while (y < y1) : (y += 1) {
            const py = @as(f32, @floatFromInt(y)) + 0.5;
            // Barycentric weights from the edge functions, normalised by
            // the signed area so either winding works.
            const wa = ((b[0] - px) * (c[1] - py) - (c[0] - px) * (b[1] - py)) * inv_area;
            const wb = ((c[0] - px) * (a[1] - py) - (a[0] - px) * (c[1] - py)) * inv_area;
            const wc = 1.0 - wa - wb;
            if (wa < 0 or wb < 0 or wc < 0) continue;
            const iz = wa * a[2] + wb * b[2] + wc * c[2];
            const depth = 1.0 / iz;
            const q = @min(depth * zbuf.scale, 65534.0);
            const qz: u16 = @intFromFloat(@max(q, 0.0));
            if (qz >= zbuf.buf[x][y]) continue;
            zbuf.buf[x][y] = qz;
            const n = math.normalize((na * math.splat(wa) + nb * math.splat(wb) + nc * math.splat(wc)) * math.splat(depth));
            const d = cam.ray(@floatFromInt(x), @floatFromInt(y));
            S.put(x, y, shade.shade(color, n, d, x, y));
        }
    }
}

/// Pixel rectangle around projected points (the same rule as
/// camera.screen_rect: floor of the minimum to ceil of the maximum plus one,
/// clipped to the screen).
fn clip_rect(x0: f32, y0: f32, x1: f32, y1: f32) camera.Rect {
    const fx0 = std.math.clamp(@floor(x0), 0, camera.screen_w);
    const fy0 = std.math.clamp(@floor(y0), 0, camera.screen_h);
    const fx1 = std.math.clamp(@ceil(x1) + 1, 0, camera.screen_w);
    const fy1 = std.math.clamp(@ceil(y1) + 1, 0, camera.screen_h);
    return .{
        .x0 = @intFromFloat(fx0),
        .y0 = @intFromFloat(fy0),
        .x1 = @intFromFloat(fx1),
        .y1 = @intFromFloat(fy1),
    };
}

// ---------------------------------------------------------------------------
// Host tests

/// Array surface: records every put and the marked rects.
const TestSurface = struct {
    var px: [camera.screen_w][camera.screen_h]u16 = undefined;
    var puts: u32 = 0;
    var outside: u32 = 0;
    var marks: u32 = 0;
    var mark: camera.Rect = .empty;
    var touched: [camera.screen_w][camera.screen_h]bool = undefined;

    fn reset() void {
        for (&px) |*col| @memset(col, 0);
        for (&touched) |*col| @memset(col, false);
        puts = 0;
        outside = 0;
        marks = 0;
        mark = .empty;
    }
    pub fn put(x: u32, y: u32, c: u16) void {
        px[x][y] = c;
        touched[x][y] = true;
        puts += 1;
    }
    pub fn mark_dirty(r: camera.Rect) void {
        marks += 1;
        mark = r;
    }
    fn check_inside() u32 {
        var n: u32 = 0;
        for (0..camera.screen_w) |x| for (0..camera.screen_h) |y| {
            if (!touched[x][y]) continue;
            if (x < mark.x0 or x >= mark.x1 or y < mark.y0 or y >= mark.y1) n += 1;
        };
        return n;
    }
    fn count_touched() u32 {
        var n: u32 = 0;
        for (touched) |col| for (col) |t| {
            n += @intFromBool(t);
        };
        return n;
    }
};

test "teapot basis is orthonormal and right-handed for every direction pair" {
    const dirs = [_]grid.Dir{ .px, .nx, .py, .ny, .pz, .nz, .none };
    for (dirs) |u| for (dirs) |f| {
        const b = basis(u, f);
        for (0..3) |i| {
            try std.testing.expectApproxEqAbs(@as(f32, 1), math.dot(b[i], b[i]), 1e-6);
            for (0..3) |j| if (i != j) try std.testing.expectApproxEqAbs(@as(f32, 0), math.dot(b[i], b[j]), 1e-6);
        }
        try std.testing.expectApproxEqAbs(@as(f32, 1), math.dot(math.cross(b[0], b[1]), b[2]), 1e-6);
        if (u != .none) try std.testing.expectEqual(u.vec(), b[1]);
        if (f != .none and u != .none and f.axis() != u.axis()) try std.testing.expectEqual(f.vec(), b[0]);
    };
}

test "teapot mesh: unit normals, outward windings, indices in range" {
    var outward: u32 = 0;
    for (mesh.triangles) |t| {
        for (t) |k| try std.testing.expect(k < mesh.positions.len);
        const a = v3(mesh.positions[t[0]]);
        const fn_ = math.cross(v3(mesh.positions[t[1]]) - a, v3(mesh.positions[t[2]]) - a);
        const vn = v3(mesh.normals[t[0]]) + v3(mesh.normals[t[1]]) + v3(mesh.normals[t[2]]);
        outward += @intFromBool(math.dot(fn_, vn) > 0);
    }
    // Every face agrees with its vertex normals (a few at the knob's pole
    // may disagree slightly; none do with the current cuts).
    try std.testing.expectEqual(@as(u32, mesh.triangles.len), outward);
    for (mesh.normals) |n| try std.testing.expectApproxEqAbs(@as(f32, 1), math.dot(v3(n), v3(n)), 1e-3);
}

test "teapot draws inside its one dirty rect, z tested, from every view" {
    for (0..camera.views.len) |v| {
        const cam = camera.view(v, 0);
        zbuf.clear();
        TestSurface.reset();
        const centre = grid.cell_center(6, 5, 6);
        draw(TestSurface, &cam, centre, .py, .px, 3, default_size);
        try std.testing.expectEqual(@as(u32, 1), TestSurface.marks);
        try std.testing.expectEqual(@as(u32, 0), TestSurface.check_inside());
        // About 9 px tall at the default size: a few dozen pixels.
        try std.testing.expect(TestSurface.count_touched() > 40);
        const first = TestSurface.puts;
        // Drawn again at the same depth: the z test rejects every pixel.
        draw(TestSurface, &cam, centre, .py, .px, 3, default_size);
        try std.testing.expectEqual(first, TestSurface.puts);
    }
}

test "teapot behind a nearer surface draws nothing" {
    const cam = camera.view(3, 0);
    zbuf.clear();
    for (&zbuf.buf) |*col| @memset(col, 1);
    TestSurface.reset();
    draw(TestSurface, &cam, grid.cell_center(6, 5, 6), .pz, .ny, 7, 0.6);
    try std.testing.expectEqual(@as(u32, 0), TestSurface.puts);
}

// Writes a PPM of a large teapot (shaded with shade.zig) when the
// environment variable PIPES_TEAPOT_PPM names an output path:
//   PIPES_TEAPOT_PPM=/tmp/teapot.ppm zig build test -Dcart=snouty-pipes
// Four panels: front view, three-quarter, from above, from below.
test "teapot preview image (PIPES_TEAPOT_PPM)" {
    const out = std.testing.environ.getPosix("PIPES_TEAPOT_PPM") orelse return;
    const w = camera.screen_w * 2;
    const h = camera.screen_h * 2;
    var img: [w * h * 3]u8 = undefined;
    const panels = [_]struct { view: usize, up: grid.Dir, front: grid.Dir }{
        .{ .view = 0, .up = .py, .front = .px },
        .{ .view = 3, .up = .py, .front = .nz },
        .{ .view = 2, .up = .py, .front = .px },
        .{ .view = 5, .up = .px, .front = .pz },
    };
    for (panels, 0..) |p, i| {
        const cam = camera.view(p.view, 0);
        zbuf.clear();
        TestSurface.reset();
        draw(TestSurface, &cam, math.splat(0), p.up, p.front, @intCast(2 + 3 * i), 5.0);
        const ox = (i % 2) * camera.screen_w;
        const oy = (i / 2) * camera.screen_h;
        for (0..camera.screen_w) |x| for (0..camera.screen_h) |y| {
            const c = TestSurface.px[x][y];
            const o = ((oy + y) * w + ox + x) * 3;
            const r: u32 = c & 31;
            const g: u32 = (c >> 5) & 63;
            const bl: u32 = c >> 11;
            img[o] = @intCast(r * 255 / 31);
            img[o + 1] = @intCast(g * 255 / 63);
            img[o + 2] = @intCast(bl * 255 / 31);
        };
    }
    var buf: [32]u8 = undefined;
    const header = try std.fmt.bufPrint(&buf, "P6\n{d} {d}\n255\n", .{ w, h });
    const file = try std.Io.Dir.cwd().createFile(std.testing.io, out, .{});
    defer file.close(std.testing.io);
    try file.writeStreamingAll(std.testing.io, header);
    try file.writeStreamingAll(std.testing.io, &img);
}
