//! Host tool: parses cart/src/levels/*.txt with `level_parse.zig` and writes
//! `cart/src/levels/gen.zig`, plain literal data the cart compiles without
//! any comptime work (the macOS build of our Zig runs out of memory on the
//! old comptime parser). Run from the repo root via tools/gen_levels.sh:
//!
//!     zig run cart/src/gen_levels.zig -- cart/src/levels/gen.zig
const std = @import("std");
const level_parse = @import("level_parse.zig");
const levels = @import("levels.zig");

const Entry = struct { name: []const u8, file: []const u8, default_wall: u8 };

/// Order matters: `levels.all[i]` is manifest[i].
const manifest = [_]Entry{
    .{ .name = "test", .file = "test.txt", .default_wall = 0 },
    .{ .name = "wolf_e1m1", .file = "wolf_e1m1.txt", .default_wall = 0 },
};

var io_mem: std.Io.Threaded = .init_single_threaded;
const io = io_mem.io();

var src_buf: [1 << 20]u8 = undefined;
var parsed: [manifest.len]level_parse.Parsed = undefined;

pub fn main(init: std.process.Init.Minimal) !void {
    var args = try init.args.iterateAllocator(std.heap.page_allocator);
    defer args.deinit();
    _ = args.next();
    const out_path = args.next() orelse {
        std.debug.print("usage: zig run cart/src/gen_levels.zig -- <out.zig>\n", .{});
        std.process.exit(1);
    };

    const cwd = std.Io.Dir.cwd();
    for (manifest, 0..) |e, i| {
        var path_buf: [256]u8 = undefined;
        const path = try std.fmt.bufPrint(&path_buf, "cart/src/levels/{s}", .{e.file});
        const src = cwd.readFile(io, path, &src_buf) catch |err| {
            std.debug.print("gen_levels: cannot read {s}: {s}\n", .{ path, @errorName(err) });
            std.process.exit(1);
        };
        level_parse.parse(&parsed[i], src, e.default_wall) catch |err| {
            std.debug.print("gen_levels: {s}: parse error: {s}\n", .{ path, @errorName(err) });
            std.process.exit(1);
        };
    }

    const out_file = try cwd.createFile(io, out_path, .{});
    defer out_file.close(io);
    var buf: [1 << 16]u8 = undefined;
    var fw = out_file.writer(io, &buf);
    const w = &fw.interface;
    try emit(w);
    try w.flush();
}

fn emit(w: *std.Io.Writer) !void {
    try w.writeAll(
        \\// Generated by cart/src/gen_levels.zig from cart/src/levels/*.txt. Do not edit; run tools/gen_levels.sh.
        \\const levels = @import("../levels.zig");
        \\const Level = levels.Level;
        \\const DoorDef = levels.DoorDef;
        \\const PickupDef = levels.PickupDef;
        \\const EnemyDef = levels.EnemyDef;
        \\
    );
    for (manifest, 0..) |e, i| {
        const p = &parsed[i];
        try w.print("\nconst {s}_doors = [_]DoorDef{{\n", .{e.name});
        for (p.doors[0..p.door_count]) |d| {
            try w.print("    .{{ .x = {d}, .y = {d}, .kind = .{s}, .vertical = {} }},\n", .{ d.x, d.y, @tagName(d.kind), d.vertical });
        }
        try w.print("}};\n\nconst {s}_pickups = [_]PickupDef{{\n", .{e.name});
        for (p.pickups[0..p.pickup_count]) |d| {
            try w.print("    .{{ .x = {d}, .y = {d}, .kind = .{s} }},\n", .{ d.x, d.y, @tagName(d.kind) });
        }
        try w.print("}};\n\nconst {s}_enemies = [_]EnemyDef{{\n", .{e.name});
        for (p.enemies[0..p.enemy_count]) |d| {
            try w.print("    .{{ .x = {d}, .y = {d}, .kind = .{s} }},\n", .{ d.x, d.y, @tagName(d.kind) });
        }
        try w.writeAll("};\n");
    }
    try w.writeAll("\npub const all = [_]Level{\n");
    for (manifest, 0..) |e, i| {
        const p = &parsed[i];
        try w.print("    .{{\n        .name = \"{s}\",\n        .width = {d},\n        .height = {d},\n        .cells = .{{\n", .{ e.name, p.width, p.height });
        for (p.cells) |row| {
            try w.writeAll("            .{ ");
            for (row, 0..) |c, x| {
                if (x != 0) try w.writeAll(", ");
                try w.print("{d}", .{c});
            }
            try w.writeAll(" },\n");
        }
        try w.print("        }},\n        .start_x = {d},\n        .start_y = {d},\n        .start_angle = {d},\n", .{ p.start_x, p.start_y, p.start_angle });
        try slice_field(w, "doors", e.name, p.door_count);
        try slice_field(w, "pickups", e.name, p.pickup_count);
        try slice_field(w, "enemies", e.name, p.enemy_count);
        try w.print("        .default_wall = {d},\n    }},\n", .{p.default_wall});
    }
    try w.writeAll("};\n");
}

fn slice_field(w: *std.Io.Writer, field: []const u8, name: []const u8, count: usize) !void {
    if (count == 0) {
        try w.print("        .{s} = &.{{}},\n", .{field});
    } else {
        try w.print("        .{s} = &{s}_{s},\n", .{ field, name, field });
    }
}
