#!/usr/bin/env python3
"""Generate cart/src/gen/scroller_font.zig: the 16-row sine-scroller font.

    python3 tools/gen_font.py [--proof docs/scroller_font.png]

DejaVu Sans Bold at 18 px (capitals 13 px tall), ASCII 32..95, rendered
in grey levels and thresholded at 50%, 1 bit per pixel. Each glyph is a
run of u16 column words, bit 0 = top row. Empty leading and trailing
columns are stripped, then one blank spacing column is appended; space is
6 blank columns. The vertical shift is chosen to lose the fewest set
pixels outside the 16 rows (a pixel or two of '$' and the comma tail).
"""
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

HERE = Path(__file__).resolve().parent.parent
OUT = HERE / "cart" / "src" / "gen" / "scroller_font.zig"
FONT = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
SIZE = 18
HEIGHT = 16
FIRST, LAST = 32, 95
SPACE_WIDTH = 6


def render_all():
    font = ImageFont.truetype(FONT, SIZE)
    bitmaps = {}
    for c in range(FIRST, LAST + 1):
        im = Image.new("L", (40, 40), 0)
        ImageDraw.Draw(im).text((4, 0), chr(c), font=font, fill=255)
        px = im.load()
        bitmaps[c] = [[px[x, y] >= 128 for x in range(40)] for y in range(40)]
    return bitmaps


def best_shift(bitmaps):
    best = None
    for shift in range(0, 12):
        lost = sum(bm[y][x] for bm in bitmaps.values() for y in range(40) for x in range(40)
                   if not (shift <= y < shift + HEIGHT))
        if best is None or lost < best[1]:
            best = (shift, lost)
    return best


def glyph_columns(bm, shift, c):
    cols = []
    for x in range(40):
        w = 0
        for r in range(HEIGHT):
            if bm[shift + r][x]:
                w |= 1 << r
        cols.append(w)
    if c == 32:
        return [0] * SPACE_WIDTH
    lo = next(i for i, w in enumerate(cols) if w)
    hi = max(i for i, w in enumerate(cols) if w)
    return cols[lo:hi + 1] + [0]


def build():
    bitmaps = render_all()
    shift, lost = best_shift(bitmaps)
    glyphs = [glyph_columns(bitmaps[c], shift, c) for c in range(FIRST, LAST + 1)]
    return glyphs, shift, lost


def write_zig(glyphs, shift, lost):
    data = [w for g in glyphs for w in g]
    offsets, o = [], 0
    for g in glyphs:
        offsets.append(o)
        o += len(g)
    widths = [len(g) for g in glyphs]
    n = len(data)
    L = [
        "//! Generated by tools/gen_font.py; do not edit. Rerun and commit to change.",
        f"//! DejaVu Sans Bold {SIZE} px, capitals 13 px tall, thresholded at 50%,",
        f"//! vertical shift {shift} ({lost} set pixels fall outside the 16 rows).",
        "//! ASCII 32..95, variable width with 1 px of spacing baked in, space",
        f"//! {SPACE_WIDTH} px. A glyph is `width` column words; bit 0 is the top row.",
        f"//! Data: {n} u16 columns ({2 * n} bytes) + {2 * len(glyphs)} bytes offsets + {len(glyphs)} bytes widths.",
        "",
        "pub const height = 16;",
        "pub const first: u8 = 32;",
        "pub const last: u8 = 95;",
        "",
        "pub const Glyph = struct { width: u8, columns: []const u16 };",
        "",
        "/// Lower case maps to upper case; anything else outside 32..95 is '?'.",
        "pub fn glyph(c: u8) Glyph {",
        "    var k = c;",
        "    if (k >= 'a' and k <= 'z') k -= 32;",
        "    if (k < first or k > last) k = '?';",
        "    const i = k - first;",
        "    const off = offsets[i];",
        "    const w = widths[i];",
        "    return .{ .width = w, .columns = columns_data[off .. off + w] };",
        "}",
        "",
        f"const widths: [{len(glyphs)}]u8 = .{{",
    ]
    for i in range(0, len(widths), 16):
        L.append("    " + ", ".join(str(w) for w in widths[i:i + 16]) + ",")
    L.append("};")
    L.append("")
    L.append(f"const offsets: [{len(glyphs)}]u16 = .{{")
    for i in range(0, len(offsets), 12):
        L.append("    " + ", ".join(str(v) for v in offsets[i:i + 12]) + ",")
    L.append("};")
    L.append("")
    L.append(f"const columns_data: [{n}]u16 = .{{")
    for gi, g in enumerate(glyphs):
        ch = chr(FIRST + gi)
        L.append(f"    // {ch!r}")
        for i in range(0, len(g), 8):
            L.append("    " + ", ".join(f"0x{w:04x}" for w in g[i:i + 8]) + ",")
    L.append("};")
    L += [
        "",
        'const std = @import("std");',
        "",
        'test "every glyph has columns matching its width" {',
        "    var c: u16 = first;",
        "    while (c <= last) : (c += 1) {",
        "        const g = glyph(@intCast(c));",
        "        try std.testing.expect(g.width > 0);",
        "        try std.testing.expectEqual(@as(usize, g.width), g.columns.len);",
        "    }",
        "}",
        "",
        'test "A has set bits, space is blank and 6 wide" {',
        "    var bits: u32 = 0;",
        "    for (glyph('A').columns) |w| bits |= w;",
        "    try std.testing.expect(bits != 0);",
        "    const sp = glyph(' ');",
        "    try std.testing.expectEqual(@as(u8, 6), sp.width);",
        "    for (sp.columns) |w| try std.testing.expectEqual(@as(u16, 0), w);",
        "}",
        "",
        'test "mapping: lower case to upper, unknown to ?" {',
        "    try std.testing.expectEqual(glyph('A').columns.ptr, glyph('a').columns.ptr);",
        "    try std.testing.expectEqual(glyph('?').columns.ptr, glyph('~').columns.ptr);",
        "    try std.testing.expectEqual(glyph('?').columns.ptr, glyph(0).columns.ptr);",
        "    try std.testing.expectEqual(glyph('?').columns.ptr, glyph(200).columns.ptr);",
        "}",
        "",
        'test "last column of every glyph is blank spacing" {',
        "    var c: u16 = first;",
        "    while (c <= last) : (c += 1) {",
        "        const g = glyph(@intCast(c));",
        "        try std.testing.expectEqual(@as(u16, 0), g.columns[g.width - 1]);",
        "    }",
        "}",
        "",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(L))
    zig_fmt(OUT)
    print(f"wrote {OUT}: {n} columns, {2 * n + 3 * len(glyphs)} bytes, shift {shift}, lost {lost}")


def zig_fmt(path):
    """zig fmt aligns the table columns; run it so the output is fmt-clean."""
    import os
    import subprocess
    zig = os.path.expanduser("~/.local/bin/zig")
    subprocess.run([zig if os.path.exists(zig) else "zig", "fmt", str(path)], check=True,
                   stdout=subprocess.DEVNULL)


def proof(path):
    """Decode the written .zig back and draw the alphabet, 4x."""
    import re
    src = OUT.read_text()
    widths = [int(v) for v in re.search(r"const widths: \[\d+\]u8 = \.\{(.*?)\};", src, re.S).group(1).replace(",", " ").split()]
    offsets = [int(v) for v in re.search(r"const offsets: \[\d+\]u16 = \.\{(.*?)\};", src, re.S).group(1).replace(",", " ").split()]
    body = re.search(r"const columns_data: \[\d+\]u16 = \.\{(.*?)\};", src, re.S).group(1)
    data = [int(v, 16) for v in re.findall(r"0x([0-9a-f]{4})", body)]
    rows = ["".join(chr(c) for c in range(32, 64)), "".join(chr(c) for c in range(64, 96)),
            "DEMOSNOUT  *  GREETINGS TO THE ZIG COMMUNITY!"]
    W = max(sum(widths[ord(ch) - 32] for ch in r) for r in rows) + 4
    im = Image.new("RGB", (W, len(rows) * 20 + 4), (16, 16, 48))
    px = im.load()
    for ri, r in enumerate(rows):
        x = 2
        y0 = 2 + ri * 20
        for ch in r:
            i = ord(ch) - 32
            for k in range(widths[i]):
                w = data[offsets[i] + k]
                for b in range(16):
                    px[x, y0 + b] = (255, 230, 80) if (w >> b) & 1 else ((40, 40, 90) if k == widths[i] - 1 else (16, 16, 48))
                x += 1
    im = im.resize((im.width * 4, im.height * 4), Image.NEAREST)
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    im.save(path)
    print(f"proof {path}")


if __name__ == "__main__":
    glyphs, shift, lost = build()
    write_zig(glyphs, shift, lost)
    if "--proof" in sys.argv:
        proof(sys.argv[sys.argv.index("--proof") + 1])
