#!/usr/bin/env python3
# Forked from snouty-zero/tools/gen_sin.py at f8f6962.
"""Write cart/src/gen/sin.zig: a 256-entry Q16.16 sine table.

    python3 tools/gen_sin.py      (from the cart directory)

Entry i is round(sin(2*pi*i/256) * 65536). The output is a plain literal
array (no comptime work, the Mac OOM rule) and is committed to the tree.
"""
import math
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "cart" / "src" / "gen" / "sin.zig"


def main() -> None:
    vals = [round(math.sin(2 * math.pi * i / 256) * 65536) for i in range(256)]
    lines = [
        "// Generated by tools/gen_sin.py; do not edit.",
        "// table[i] = round(sin(2*pi*i/256) * 65536), Q16.16, i in turns/256.",
        "pub const table = [256]i32{",
    ]
    for row in range(0, 256, 8):
        lines.append("    " + " ".join(f"{v}," for v in vals[row:row + 8]))
    lines.append("};")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
