#!/usr/bin/env python3
"""Write cart/src/gen/tables.zig: the theremin's constant tables.

    python3 tools/gen_tables.py          # rewrite the file
    python3 tools/gen_tables.py --check  # exit 1 if the committed file differs

The tables are generated on the host and committed (repository CLAUDE.md:
heavy comptime fails on Adrian's Mac, so no comptime trigonometry):

- sine: 257 samples of one sine cycle in Q15 (the last repeats the first,
  so the voice can interpolate without wrapping).
- semitone_q30: 2^(s/12) for s = 0..11, Q30.
- cent_q30: 2^(c/1200) for c = 0..99, Q30.
- base_inc_q8: the phase increment of MIDI note 0 (8.1758 Hz) at 44.1 kHz
  for a 32-bit phase, times 256.
"""
import math
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "cart", "src", "gen", "tables.zig")
RATE = 44100


def render() -> str:
    sine = [round(32767 * math.sin(2 * math.pi * i / 256)) for i in range(257)]
    semi = [round((2 ** (s / 12)) * (1 << 30)) for s in range(12)]
    cent = [round((2 ** (c / 1200)) * (1 << 30)) for c in range(100)]
    midi0 = 440.0 * 2 ** (-69 / 12)
    base = round(midi0 * (1 << 40) / RATE)
    out = []
    out.append("//! Generated by tools/gen_tables.py; do not edit by hand.")
    out.append("//! Sine cycle (Q15, 257 entries), 2^(s/12) and 2^(c/1200) in Q30, and")
    out.append("//! the 32-bit phase increment of MIDI note 0 at 44.1 kHz times 256.")
    out.append("")
    out.append(f"pub const base_inc_q8: u32 = {base};")
    out.append("")
    out.append("pub const sine = [257]i16{")
    # One value per line: zig fmt aligns multi-value rows into columns.
    out.extend(f"    {v}," for v in sine)
    out.append("};")
    out.append("")
    out.append("pub const semitone_q30 = [12]u32{")
    out.extend(f"    {v}," for v in semi)
    out.append("};")
    out.append("")
    out.append("pub const cent_q30 = [100]u32{")
    out.extend(f"    {v}," for v in cent)
    out.append("};")
    out.append("")
    return "\n".join(out)


def main() -> int:
    text = render()
    if "--check" in sys.argv[1:]:
        try:
            with open(OUT) as f:
                ok = f.read() == text
        except FileNotFoundError:
            ok = False
        print("gen_tables: " + ("up to date" if ok else "cart/src/gen/tables.zig differs; run tools/gen_tables.py"))
        return 0 if ok else 1
    with open(OUT, "w") as f:
        f.write(text)
    print(f"gen_tables: wrote {os.path.relpath(OUT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
