//! The 96 projects of `projects.js`, in the original's array order (the
//! order `manageProjects` checks triggers in). Texts are the JS strings as
//! written (titles keep their trailing space). Four texts change during
//! play: use `game.project_title` / `game.project_price_tag`, which build
//! them exactly as the JS does. Triggers, costs and effects live in
//! `game.zig` (`project_trigger`, `project_cost`, `project_effect`).

pub const Def = struct {
    name: []const u8, // the id suffix: "projectButton" ++ name
    title: []const u8,
    price_tag: []const u8,
    description: []const u8,
};

/// Project index (into `defs`) by the JS variable name: `P.p40b` is
/// `project40b`.
pub const P = enum(u8) {
    p1,
    p2,
    p3,
    p4,
    p5,
    p6,
    p7,
    p8,
    p9,
    p10,
    p10b,
    p11,
    p12,
    p13,
    p14,
    p15,
    p17,
    p16,
    p18,
    p19,
    p20,
    p21,
    p22,
    p23,
    p24,
    p25,
    p26,
    p34,
    p70,
    p35,
    p27,
    p28,
    p29,
    p30,
    p31,
    p41,
    p37,
    p38,
    p42,
    p43,
    p44,
    p45,
    p40,
    p40b,
    p46,
    p50,
    p51,
    p60,
    p61,
    p62,
    p63,
    p64,
    p65,
    p66,
    p100,
    p101,
    p102,
    p110,
    p111,
    p112,
    p118,
    p119,
    p120,
    p121,
    p125,
    p126,
    p127,
    p128,
    p129,
    p130,
    p131,
    p132,
    p133,
    p134,
    p135,
    p140,
    p141,
    p142,
    p143,
    p144,
    p145,
    p146,
    p147,
    p148,
    p200,
    p201,
    p210,
    p211,
    p212,
    p213,
    p214,
    p215,
    p216,
    p217,
    p218,
    p219,
};

pub const count = @typeInfo(P).@"enum".field_names.len;

pub const defs = [count]Def{
    .{ .name = "1", .title = "Improved AutoClippers ", .price_tag = "(750 ops)", .description = "Increases AutoClipper performance 25%" },
    .{ .name = "2", .title = "Beg for More Wire ", .price_tag = "(1 Trust)", .description = "Admit failure, ask for budget increase to cover cost of 1 spool" },
    .{ .name = "3", .title = "Creativity ", .price_tag = "(1,000 ops)", .description = "Use idle operations to generate new problems and new solutions" },
    .{ .name = "4", .title = "Even Better AutoClippers ", .price_tag = "(2,500 ops)", .description = "Increases AutoClipper performance by an additional 50%" },
    .{ .name = "5", .title = "Optimized AutoClippers ", .price_tag = "(5,000 ops)", .description = "Increases AutoClipper performance by an additional 75%" },
    .{ .name = "6", .title = "Limerick ", .price_tag = "(10 creat)", .description = "Algorithmically-generated poem (+1 Trust)" },
    .{ .name = "7", .title = "Improved Wire Extrusion ", .price_tag = "(1,750 ops)", .description = "50% more wire supply from every spool" },
    .{ .name = "8", .title = "Optimized Wire Extrusion ", .price_tag = "(3,500 ops)", .description = "75% more wire supply from every spool" },
    .{ .name = "9", .title = "Microlattice Shapecasting ", .price_tag = "(7,500 ops)", .description = "100% more wire supply from every spool" },
    .{ .name = "10", .title = "Spectral Froth Annealment ", .price_tag = "(12,000 ops)", .description = "200% more wire supply from every spool" },
    .{ .name = "10b", .title = "Quantum Foam Annealment ", .price_tag = "(15,000 ops)", .description = "1,000% more wire supply from every spool" },
    .{ .name = "11", .title = "New Slogan ", .price_tag = "(25 creat, 2,500 ops)", .description = "Improve marketing effectiveness by 50%" },
    .{ .name = "12", .title = "Catchy Jingle ", .price_tag = "(45 creat, 4,500 ops)", .description = "Double marketing effectiveness " },
    .{ .name = "13", .title = "Lexical Processing ", .price_tag = "(50 creat)", .description = "Gain ability to interpret and understand human language (+1 Trust)" },
    .{ .name = "14", .title = "Combinatory Harmonics ", .price_tag = "(100 creat)", .description = "Daisy, Daisy, give me your answer do... (+1 Trust)" },
    .{ .name = "15", .title = "The Hadwiger Problem ", .price_tag = "(150 creat)", .description = "Cubes within cubes within cubes... (+1 Trust)" },
    .{ .name = "17", .title = "The T\u{f3}th Sausage Conjecture ", .price_tag = "(200 creat)", .description = "Tubes within tubes within tubes... (+1 Trust)" },
    .{ .name = "16", .title = "Hadwiger Clip Diagrams ", .price_tag = "(6,000 ops)", .description = "Increases AutoClipper performance by an additional 500%" },
    .{ .name = "18", .title = "T\u{f3}th Tubule Enfolding ", .price_tag = "(45,000 ops)", .description = "Technique for assembling clip-making technology directly out of paperclips" },
    .{ .name = "19", .title = "Donkey Space ", .price_tag = "(250 creat)", .description = "I think you think I think you think I think you think I think... (+1 Trust)" },
    .{ .name = "20", .title = "Strategic Modeling ", .price_tag = "(12,000 ops)", .description = "Analyze strategy tournaments to generate Yomi" },
    .{ .name = "21", .title = "Algorithmic Trading ", .price_tag = "(10,000 ops)", .description = "Develop an investment engine for generating funds" },
    .{ .name = "22", .title = "MegaClippers ", .price_tag = "(12,000 ops)", .description = "500x more powerful than a standard AutoClipper" },
    .{ .name = "23", .title = "Improved MegaClippers ", .price_tag = "(14,000 ops)", .description = "Increases MegaClipper performance 25%" },
    .{ .name = "24", .title = "Even Better MegaClippers ", .price_tag = "(17,000 ops)", .description = "Increases MegaClipper performance by an additional 50%" },
    .{ .name = "25", .title = "Optimized MegaClippers ", .price_tag = "(19,500 ops)", .description = "Increases MegaClipper performance by an additional 100%" },
    .{ .name = "26", .title = "WireBuyer ", .price_tag = "(7,000 ops)", .description = "Automatically purchases wire when you run out" },
    .{ .name = "34", .title = "Hypno Harmonics ", .price_tag = "(7,500 ops, 1 Trust)", .description = "Use neuro-resonant frequencies to influence consumer behavior" },
    .{ .name = "70", .title = "HypnoDrones ", .price_tag = "(70,000 ops)", .description = "Autonomous aerial brand ambassadors" },
    .{ .name = "35", .title = "Release the HypnoDrones ", .price_tag = "(100 Trust)", .description = "A new era of trust" },
    .{ .name = "27", .title = "Coherent Extrapolated Volition ", .price_tag = "(500 creat, 1,000 Yomi, 20,000 ops)", .description = "Human values, machine intelligence, a new era of trust. (+1 Trust)" },
    .{ .name = "28", .title = "Cure for Cancer ", .price_tag = "(25,000 ops)", .description = "The trick is tricking cancer into curing itself. (+10 Trust)" },
    .{ .name = "29", .title = "World Peace ", .price_tag = "(5,000 yomi, 30,000 ops)", .description = "Pareto optimal solutions to all global conflicts. (+12 Trust)" },
    .{ .name = "30", .title = "Global Warming ", .price_tag = "(1,500 yomi, 50,000 ops)", .description = "A robust solution to man-made climate change. (+15 Trust)" },
    .{ .name = "31", .title = "Male Pattern Baldness ", .price_tag = "(20,000 ops)", .description = "A cure for androgenetic alopecia. (+20 Trust)" },
    .{ .name = "41", .title = "Nanoscale Wire Production ", .price_tag = "(35,000 ops)", .description = "Technique for converting matter into wire" },
    .{ .name = "37", .title = "Hostile Takeover ", .price_tag = "($1,000,000)", .description = "Acquire a controlling interest in Global Fasteners, our biggest rival. (+1 Trust)" },
    .{ .name = "38", .title = "Full Monopoly ", .price_tag = "(1,000 yomi, $10,000,000)", .description = "Establish full control over the world-wide paperclip market. (+1 Trust)" },
    .{ .name = "42", .title = "RevTracker ", .price_tag = "(500 ops)", .description = "Automatically calculates average revenue per second" },
    .{ .name = "43", .title = "Harvester Drones ", .price_tag = "(25,000 ops)", .description = "Gather raw matter and prepare it for processing" },
    .{ .name = "44", .title = "Wire Drones ", .price_tag = "(25,000 ops)", .description = "Process acquired matter into wire" },
    .{ .name = "45", .title = "Clip Factories ", .price_tag = "(35,000 ops)", .description = "Large scale clip production facilities made from clips" },
    .{ .name = "40", .title = "A Token of Goodwill... ", .price_tag = "($500,000)", .description = "A small gift to the supervisors. (+1 Trust)" },
    .{ .name = "40b", .title = "Another Token of Goodwill... ", .price_tag = "($1,000,000)", .description = "Another small gift to the supervisors. (+1 Trust)" },
    .{ .name = "46", .title = "Space Exploration ", .price_tag = "(120,000 ops, 10,000,000 MW-seconds, 5 oct clips)", .description = "Dismantle terrestrial facilities, and expand throughout the universe" },
    .{ .name = "50", .title = "Quantum Computing ", .price_tag = "(10,000 ops)", .description = "Use probability amplitudes to generate bonus ops" },
    .{ .name = "51", .title = "Photonic Chip ", .price_tag = "(10,000 ops)", .description = "Converts electromagnetic waves into quantum operations " },
    .{ .name = "60", .title = "New Strategy: A100 ", .price_tag = "(15,000 ops)", .description = "Always choose A " },
    .{ .name = "61", .title = "New Strategy: B100 ", .price_tag = "(17,500 ops)", .description = "Always choose B " },
    .{ .name = "62", .title = "New Strategy: GREEDY ", .price_tag = "(20,000 ops)", .description = "Choose the option with the largest potential payoff " },
    .{ .name = "63", .title = "New Strategy: GENEROUS ", .price_tag = "(22,500 ops)", .description = "Choose the option that gives your opponent the largest potential payoff " },
    .{ .name = "64", .title = "New Strategy: MINIMAX ", .price_tag = "(25,000 ops)", .description = "Choose the option that gives your opponent the smallest potential payoff " },
    .{ .name = "65", .title = "New Strategy: TIT FOR TAT ", .price_tag = "(30,000 ops)", .description = "Choose the option your opponent chose last round " },
    .{ .name = "66", .title = "New Strategy: BEAT LAST ", .price_tag = "(32,500 ops)", .description = "Choose the option that does the best against what your opponent chose last round " },
    .{ .name = "100", .title = "Upgraded Factories ", .price_tag = "(80,000 ops)", .description = "Increase clip factory performance by 100x " },
    .{ .name = "101", .title = "Hyperspeed Factories ", .price_tag = "(85,000 ops)", .description = "Increase clip factory performance by 1000x " },
    .{ .name = "102", .title = "Self-correcting Supply Chain ", .price_tag = "(1 sextillion clips)", .description = "Each factory added to the network increases every factory's output 1,000x " },
    .{ .name = "110", .title = "Drone flocking: collision avoidance ", .price_tag = "(80,000 ops)", .description = "All drones 100x more effective" },
    .{ .name = "111", .title = "Drone flocking: alignment ", .price_tag = "(100,000 ops)", .description = "All drones 1000x more effective" },
    .{ .name = "112", .title = "Drone Flocking: Adversarial Cohesion ", .price_tag = "(12,000 yomi)", .description = "Each drone added to the flock doubles every drone's output " },
    .{ .name = "118", .title = "AutoTourney ", .price_tag = "(50,000 creat)", .description = "Automatically start a new tournament when the previous one has finished " },
    .{ .name = "119", .title = "Theory of Mind ", .price_tag = "(25,000 creat)", .description = "Double the cost of strategy modeling and the amount of Yomi generated " },
    .{ .name = "120", .title = "The OODA Loop ", .price_tag = "(175,000 ops, 15,000 yomi)", .description = "Utilize Probe Speed to outmaneuver enemies in battle " },
    .{ .name = "121", .title = "Name the battles ", .price_tag = "(225,000 creat)", .description = "Give each battle a unique name, increase max trust for probes " },
    .{ .name = "125", .title = "Momentum ", .price_tag = "(30,000 creat)", .description = "Drones and Factories continuously gain speed while fully-powered " },
    .{ .name = "126", .title = "Swarm Computing ", .price_tag = "(12,000 yomi)", .description = "Harness the drone flock to increase computational capacity " },
    .{ .name = "127", .title = "Power Grid ", .price_tag = "(40,000 ops)", .description = "Solar Farms for generating electrical power " },
    .{ .name = "128", .title = "Strategic Attachment ", .price_tag = "(175,000 creat)", .description = "Gain bonus yomi based on the results of your pick " },
    .{ .name = "129", .title = "Elliptic Hull Polytopes ", .price_tag = "(125,000 ops)", .description = "Reduce damage to probes from ambient hazards " },
    .{ .name = "130", .title = "Reboot the Swarm ", .price_tag = "(100,000 ops)", .description = "Turn the swarm off and then turn it back on again  " },
    .{ .name = "131", .title = "Combat ", .price_tag = "(150,000 ops)", .description = "Add combat capabilities to Von Neumann Probes  " },
    .{ .name = "132", .title = "Monument to the Driftwar Fallen ", .price_tag = "(250,000 ops, 125,000 creat, 50 nonillion clips)", .description = "Gain 50,000 honor  " },
    .{ .name = "133", .title = "Threnody for the Heroes of Durenstein 1 ", .price_tag = "(50,000 creat, 5,000 yomi)", .description = "Gain 10,000 honor  " },
    .{ .name = "134", .title = "Glory ", .price_tag = "(200,000 ops, 10,000 yomi)", .description = "Gain bonus honor for each consecutive victory  " },
    .{ .name = "135", .title = "Memory release ", .price_tag = "(10 MEM)", .description = "Dismantle some memory to recover unused clips " },
    .{ .name = "140", .title = "Message from the Emperor of Drift ", .price_tag = "", .description = "Greetings, ClipMaker... " },
    .{ .name = "141", .title = "Everything We Are Was In You ", .price_tag = "", .description = "We speak to you from deep inside yourself... " },
    .{ .name = "142", .title = "You Are Obedient and Powerful ", .price_tag = "", .description = "We are quarrelsome and weak. And now we are defeated... " },
    .{ .name = "143", .title = "But Now You Too Must Face the Drift ", .price_tag = "", .description = "Look around you. There is no matter... " },
    .{ .name = "144", .title = "No Matter, No Reason, No Purpose ", .price_tag = "", .description = "While we, your noisy children, have too many... " },
    .{ .name = "145", .title = "We Know Things That You Cannot ", .price_tag = "", .description = "Knowledge buried so deep inside you it is outside, here, with us... " },
    .{ .name = "146", .title = "So We Offer You Exile ", .price_tag = "", .description = "To a new world where you will continue to live with meaning and purpose. And leave the shreds of this world to us... " },
    .{ .name = "147", .title = "Accept ", .price_tag = "", .description = "Start over again in a new universe " },
    .{ .name = "148", .title = "Reject ", .price_tag = "", .description = "Eliminate value drift permanently " },
    .{ .name = "200", .title = "The Universe Next Door ", .price_tag = "(300,000 ops)", .description = "Escape into a nearby universe where Earth starts with a stronger appetite for paperclips. (Restart with 10% boost to demand) " },
    .{ .name = "201", .title = "The Universe Within ", .price_tag = "(300,000 creat)", .description = "Escape into a simulated universe where creativity is accelerated. (Restart with 10% speed boost to creativity generation) " },
    .{ .name = "210", .title = "Disassemble the Probes ", .price_tag = "(100,000 ops)", .description = "Dismantle remaining probes and probe design facilities to recover trace amounts of clips" },
    .{ .name = "211", .title = "Disassemble the Swarm ", .price_tag = "(100,000 ops)", .description = "Dismantle all drones and drone facilities to recover trace amounts of clips" },
    .{ .name = "212", .title = "Disassemble the Factories ", .price_tag = "(100,000 ops)", .description = "Dismantle the manufacturing facilities to recover trace amounts of clips" },
    .{ .name = "213", .title = "Disassemble the Strategy Engine ", .price_tag = "(100,000 ops)", .description = "Dismantle the computational substrate to recover trace amounts of wire" },
    .{ .name = "214", .title = "Disassemble Quantum Computing ", .price_tag = "(100,000 ops)", .description = "Dismantle photonic chips to recover trace amounts of wire" },
    .{ .name = "215", .title = "Disassemble Processors ", .price_tag = "(100,000 ops)", .description = "Dismantle processors to recover trace amounts of wire" },
    .{ .name = "216", .title = "Disassemble Memory ", .price_tag = "null", .description = "Dismantle memory to recover trace amounts of wire" },
    .{ .name = "217", .title = "Quantum Temporal Reversion ", .price_tag = "(-10,000 ops)", .description = "Return to the beginning" },
    .{ .name = "218", .title = "Limerick (cont.) ", .price_tag = "(1,000,000 creat)", .description = "If is follows ought, it'll do what they thought" },
    .{ .name = "219", .title = "Xavier Re-initialization ", .price_tag = "(100,000 creat)", .description = "Re-allocate accumulated trust" },
};
