const std = @import("std");
const Build = std.Build;

const os_cart = @import("../../build/os_cart.zig");
// A module of the root build.zig, not a package root. If Zig says "import of
// file outside module path" here, `zig build` was run in this directory: run
// `zig build -Dcart=snouty-zero` from the repository root instead.
const common = @import("../../build/common.zig");

/// This cart's directory, relative to the repository root that build.zig runs from.
const dir = "carts/snouty-zero/";

/// Floor inner loop (SPEC 18, measured in M0): `row` walks along a screen
/// row with incremental adds and writes at a 256-byte stride (the default:
/// 2.32 ms against 2.76 in the calibrated bench); `column` walks down a
/// framebuffer column (sequential halfword writes, two multiply-accumulates
/// per pixel), kept for a hardware check of the stride cost.
pub const FloorLoop = enum { column, row };

/// Generated data files embedded by the `assets` module (PLAN.md "Generated
/// data formats"). Each becomes `assets.<name>: []const u8`.
const data_files = [_][]const u8{
    "edge_tiles.bin",
    "edge_pal.bin",
    "edge_horizon.bin",
    "cold_aisle_map.bin",
    "cold_aisle_attr.bin",
    "cold_aisle_center.bin",
};

pub fn add(b: *Build, sycl_badge_dep: *Build.Dependency, opts: common.Options) void {
    const options = b.addOptions();
    // -Ddebug_overlay=true draws the frame time top-right (declared by the root build.zig).
    options.addOption(bool, "debug_overlay", opts.debug_overlay);
    // -Dsound: the initial value of the sound toggle (docs/SOUND.md).
    options.addOption(bool, "sound", opts.sound);
    const floor_loop = b.option(FloorLoop, "zero_floor", "snouty-zero: floor inner loop, row (default, PLAN.md M0 status) or column") orelse .row;
    options.addOption(FloorLoop, "floor_loop", floor_loop);
    build_options = options;

    os_cart.add(b, sycl_badge_dep, .{
        .mode = opts.cart_mode,
        .name = "snouty-zero",
        .optimize = .ReleaseFast,
        .root_source_file = b.path(dir ++ "cart/src/main.zig"),
        .custom_builder = &build_cart_modules,
    });

    // `zig build check-float` (shared step): the cart is all-integer; fail if the ELF
    // links any soft-float or libm routine.
    const check_float = b.addSystemCommand(&.{"node"});
    check_float.addFileArg(b.path("tools/check_float.mjs"));
    check_float.addFileArg(b.graph.path(.install_prefix, "firmware/snouty-zero.elf"));
    check_float.step.dependOn(b.getInstallStep());
    check_float.has_side_effects = true;
    opts.check_float_step.dependOn(&check_float.step);

    // `zig build test` (shared step): host tests for the modules without a cart
    // API dependency (cart/src/host_tests.zig lists them).
    const tests_mod = b.createModule(.{
        .root_source_file = b.path(dir ++ "cart/src/host_tests.zig"),
        .target = b.graph.host,
        .optimize = .Debug,
    });
    tests_mod.addImport("assets", assets_module(b));
    const tests = b.addTest(.{ .root_module = tests_mod });
    opts.test_step.dependOn(&b.addRunArtifact(tests).step);
}

var build_options: ?*Build.Step.Options = null;

/// The `assets` module: a generated assets.zig with one `@embedFile` per
/// data file, the files copied next to it (an @embedFile cannot reach
/// outside its module's directory).
fn assets_module(b: *Build) *Build.Module {
    const wf = b.addWriteFiles();
    var src: std.ArrayList(u8) = .empty;
    src.appendSlice(b.allocator, "//! Generated by carts/snouty-zero/build.zig: the committed assets/gen/*.bin files.\n") catch @panic("oom");
    for (data_files) |f| {
        _ = wf.addCopyFile(b.path(b.fmt(dir ++ "assets/gen/{s}", .{f})), f);
        const stem = f[0 .. f.len - ".bin".len];
        src.appendSlice(b.allocator, b.fmt("pub const {s}: []const u8 = @embedFile(\"{s}\");\n", .{ stem, f })) catch @panic("oom");
    }
    const assets_zig = wf.add("assets.zig", src.items);
    return b.createModule(.{ .root_source_file = assets_zig });
}

fn build_cart_modules(b: *Build, cart: *Build.Module, cart_api: *Build.Module, step: *Build.Step) void {
    _ = cart_api;
    _ = step;
    cart.addImport("build_options", build_options.?.createModule());
    cart.addImport("assets", assets_module(b));
}
