#!/usr/bin/env python3
"""Bake a preview.mjs input script into the cart's demo data (PLAN.md M5).

    tools/gen_demo.py tools/scripts/demo_build_farm.json \
        --out cart/src/demos/build_farm.zig [--hash 0x12345678] [--level 0]

The script is the usual JSON array of {"from": T1, "to": T2, "hold": [...]}
entries (inclusive ticks, tick 0 = the level's first sim.step, no title
press; an entry with an empty "hold" pads idle ticks). The demo runs for
T = max(to) + 1 ticks. Output is plain literal Zig data: run-length pairs
of (button word, ticks) in cart.Controls bit order, the level index, the
fixed seed and the expected sim.hash_gameplay after tick T-1 (0 =
unrecorded; tools/record_demo.sh fills it in).
"""
import argparse
import json
import sys

BUTTONS = {"START": 1 << 0, "SELECT": 1 << 1, "A": 1 << 2, "B": 1 << 3,
           "UP": 1 << 5, "DOWN": 1 << 6, "LEFT": 1 << 7, "RIGHT": 1 << 8}
# Any non-zero value works (sim.init treats 0 as "use the default"); the
# demo's hash depends on it, so it never changes once a demo is recorded.
DEMO_SEED = 0x5EED_0001


def load(path):
    with open(path) as f:
        entries = json.load(f)
    if not isinstance(entries, list):
        sys.exit(f"{path}: top level must be a JSON array")
    total = 0
    parsed = []
    for k, e in enumerate(entries):
        for key in e:
            if key not in ("from", "to", "hold"):
                sys.exit(f"{path}: entry {k}: unknown field {key!r}")
        fr, to = e["from"], e["to"]
        if not (isinstance(fr, int) and isinstance(to, int) and 0 <= fr <= to):
            sys.exit(f"{path}: entry {k}: bad from/to")
        bits = 0
        for b in e["hold"]:
            name = str(b).upper()
            if name not in BUTTONS:
                sys.exit(f"{path}: entry {k}: unknown button {b!r}")
            bits |= BUTTONS[name]
        parsed.append((fr, to, bits))
        total = max(total, to + 1)
    return parsed, total


def per_tick(entries, total):
    words = [0] * total
    for fr, to, bits in entries:
        for t in range(fr, to + 1):
            words[t] |= bits
    return words


def runs_of(words):
    runs = []
    for w in words:
        if runs and runs[-1][0] == w and runs[-1][1] < 0xFFFF:
            runs[-1][1] += 1
        else:
            runs.append([w, 1])
    return runs


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("script")
    ap.add_argument("--out", required=True)
    ap.add_argument("--hash", default="0", help="expected debug_gameplay_hash after the last tick (0 = unrecorded)")
    ap.add_argument("--level", type=int, default=0, help="level index (0 Build Farm, 1 Staging, 2 Production; the attract demo uses 2)")
    a = ap.parse_args()
    entries, total = load(a.script)
    if total == 0:
        sys.exit(f"{a.script}: empty demo")
    if total > 3 * 3600:
        sys.exit(f"{a.script}: {total} ticks is longer than the 3 min attract cap")
    words = per_tick(entries, total)
    runs = runs_of(words)
    final_hash = int(a.hash, 0) & 0xFFFFFFFF
    lines = [
        "//! GENERATED by tools/gen_demo.py from " + a.script.replace("\\", "/") + "; do not edit.",
        "//! Attract-mode demo: a fixed seed plus a run-length input log (SPEC.md 11,",
        "//! PLAN.md M5). Bit layout of `buttons` is cart.Controls / state.Buttons.",
        "pub const Run = struct { buttons: u16, ticks: u16 };",
        "",
        f"pub const level_index: u8 = {a.level};",
        f"pub const seed: u32 = 0x{DEMO_SEED:08X};",
        f"pub const total_ticks: u32 = {total};",
        "/// sim.hash_gameplay of the state after the last tick as recorded in the",
        "/// simulator; 0 = not recorded yet (tools/record_demo.sh).",
        f"pub const final_hash: u32 = 0x{final_hash:08X};",
        "",
        "pub const runs = [_]Run{",
    ]
    for w, n in runs:
        lines.append(f"    .{{ .buttons = 0x{w:04X}, .ticks = {n} }},")
    lines.append("};")
    lines.append("")
    with open(a.out, "w") as f:
        f.write("\n".join(lines))
    print(f"gen_demo: {a.script}: {total} ticks, {len(runs)} runs, {len(runs) * 4} bytes, final_hash 0x{final_hash:08X} -> {a.out}")


if __name__ == "__main__":
    main()
