//! Quantisation of linear f32 RGB to RGB565 `Pixel` (PLAN.md "Quantisation",
//! SPEC.md 5.5, PLAN.md M3 dither modes 2 to 4).
//!
//! Three of the four modes are the same arithmetic, `floor(c * max + th)`
//! per channel, and differ only in the threshold table:
//!
//! - `bayer_temporal` (default): `(B + 0.5) / 16` from a 4x4 Bayer matrix
//!   whose x index is shifted by 2 on odd frames.
//! - `blue_noise`: `(v + 0.5) / 256` from a 64x64 void-and-cluster table
//!   (`bluenoise64.bin`, tools/gen_bluenoise.py), static.
//! - `none`: the constant 1e-4 (straight truncation).
//!
//! Every threshold table is column-major with 64 rows, `[column][64]f32`,
//! and read as `table[(x & x_mask) * 64 + (y & 63)]`; the mode only picks
//! the pointer and the column mask (3, 63, 7 or 0), set once per frame by
//! begin_frame. The Bayer table has 6 columns (4 plus the 2 the parity
//! shift reaches) so the odd-frame shift is a pointer offset, not an add.
//!
//! `palette16` runs the same per-pixel code with scale 15 on every channel
//! and an 8x8 Bayer table `(B + 0.5) / 64` (mask 7), so each RGB565 field
//! holds a 4-bit cube coordinate; end_frame() then maps every pixel through
//! the 16^3 nearest-colour cube (`palette16_cube.bin`) to one of 16
//! precomputed Pixels (`palette16.bin`; both from tools/gen_palette16.py).
//! The pass costs only in that mode; the pixel loop has no mode branch.
//!
//! No clamp is needed: the input is saturated to [0, 1] and every threshold
//! is below 1, so `c * 31 + th < 32`, `c * 63 + th < 64`, `c * 15 + th < 16`
//! (and the palette fields stay below 16, inside their 5/6/5 slots).
//!
//! No gamma table: the output is linear, as the reference (tools/
//! reference.py) expects in mode `none`.
//!
//! Tables come from committed host-generated files and are expanded to f32
//! in init() at start(); nothing here is generated by comptime loops beyond
//! a few dozen entries (root CLAUDE.md: the Mac Zig OOMs on big comptime).
const cart = @import("cart-api");
const math = @import("math.zig");

pub const Mode = enum(u32) { bayer_temporal = 0, none = 1, blue_noise = 2, palette16 = 3 };

pub var mode: Mode = .bayer_temporal;

/// B cycles bayer_temporal -> blue_noise -> palette16 -> none -> bayer_temporal.
pub fn next_mode() void {
    set_mode(switch (mode) {
        .bayer_temporal => .blue_noise,
        .blue_noise => .palette16,
        .palette16 => .none,
        .none => .bayer_temporal,
    });
}

pub fn set_mode(m: Mode) void {
    mode = m;
    select_table();
}

/// One-letter name for the debug overlay.
pub fn mode_letter() u8 {
    return switch (mode) {
        .bayer_temporal => 'B',
        .none => 'N',
        .blue_noise => 'U',
        .palette16 => 'P',
    };
}

/// Called once per frame before any quantise() call.
pub fn begin_frame(frame: u32) void {
    parity = frame & 1;
    select_table();
}

/// Expand the embedded byte tables. Call once from start(), before the
/// first frame.
pub noinline fn init() void {
    for (0..64) |x| {
        for (0..64) |y| {
            const v: f32 = @floatFromInt(bluenoise_bytes[y * 64 + x]);
            blue_table[x * 64 + y] = (v + 0.5) / 256.0;
        }
    }
    for (0..bayer4_columns) |x| {
        for (0..64) |y| {
            const b: f32 = @floatFromInt(bayer4[y & 3][x & 3]);
            bayer4_table[x * 64 + y] = (b + 0.5) / 16.0;
        }
    }
    for (0..8) |x| {
        for (0..64) |y| {
            const b: f32 = @floatFromInt(bayer8(x, y & 7));
            bayer8_table[x * 64 + y] = (b + 0.5) / 64.0;
        }
    }
    for (&palette_pixels, 0..) |*p, i| {
        const bits = @as(u16, palette_bytes[2 * i]) | (@as(u16, palette_bytes[2 * i + 1]) << 8);
        p.* = cart.Pixel.from_color(@bitCast(bits));
    }
    select_table();
}

/// Frame parity stored by begin_frame (0 even, 1 odd).
var parity: u32 = 0;

/// Threshold table for the current frame and mode (see the file comment).
var table: [*]const f32 = &none_table;
var x_mask: u32 = 0;
/// Levels per channel minus one: 31/63/31 for RGB565, 15 for the palette
/// cube (quantise leaves the cube cell in the RGB565 fields).
var scale: math.Vec3 = rgb565_scale;
const rgb565_scale: math.Vec3 = .{ 31.0, 63.0, 31.0 };
const cube_scale: math.Vec3 = @splat(15.0);

fn select_table() void {
    scale = if (mode == .palette16) cube_scale else rgb565_scale;
    switch (mode) {
        .bayer_temporal => {
            table = bayer4_table[parity * 2 * 64 ..].ptr;
            x_mask = 3;
        },
        .none => {
            table = &none_table;
            x_mask = 0;
        },
        .blue_noise => {
            table = &blue_table;
            x_mask = 63;
        },
        .palette16 => {
            table = &bayer8_table;
            x_mask = 7;
        },
    }
}

const bayer4 = [4][4]u8{
    .{ 0, 8, 2, 10 },
    .{ 12, 4, 14, 6 },
    .{ 3, 11, 1, 9 },
    .{ 15, 7, 13, 5 },
};

/// 8x8 Bayer value at (x, y), 0..63, by the recursion
/// M(2n) = [4M, 4M + 2; 4M + 3, 4M + 1]: the lowest bits of x and y give the
/// most significant base-4 digit. Agrees with bayer4 on its 4x4 corner.
fn bayer8(x: usize, y: usize) u32 {
    var v: u32 = 0;
    inline for (0..3) |k| {
        const xb: u32 = @intCast((x >> k) & 1);
        const yb: u32 = @intCast((y >> k) & 1);
        v = (v << 2) | ((xb ^ yb) << 1) | yb;
    }
    return v;
}

/// 4 Bayer columns plus the 2 the odd-frame shift reaches.
const bayer4_columns = 6;
var bayer4_table: [bayer4_columns * 64]f32 = undefined;
var bayer8_table: [8 * 64]f32 = undefined;
var blue_table: [64 * 64]f32 = undefined;
const none_table: [64]f32 = @splat(1e-4);

const bluenoise_bytes: *const [4096]u8 = @embedFile("bluenoise64.bin");
const palette_bytes: *const [32]u8 = @embedFile("palette16.bin");
const palette_cube: *const [4096]u8 = @embedFile("palette16_cube.bin");
var palette_pixels: [16]cart.Pixel = undefined;

/// Quantise linear RGB in [0, 1] (already saturated) for screen pixel (x, y).
/// Branch-free and the same instructions in every mode (only `scale` and the
/// table differ), so the default mode costs what M2.2's did: a per-pixel
/// palette branch here cost 0.6 to 0.9 ms of FP stalls and taken branches
/// on badge-bench. In palette16 the fields hold the 4-bit cube coordinates
/// and end_frame() maps them to palette colours.
pub inline fn quantise(x: u32, y: u32, rgb: math.Vec3) cart.Pixel {
    const th = table[((x & x_mask) << 6) | (y & 63)];
    // Separate mul and add (not @mulAdd): VMUL+VADD are 1 cycle each on the
    // M33, VFMA is 3, and wasm would lower fma to a libcall.
    const q = rgb * scale + @as(math.Vec3, @splat(th));
    // Non-negative, so truncation is floor.
    const r: u16 = @intFromFloat(q[0]);
    const g: u16 = @intFromFloat(q[1]);
    const b: u16 = @intFromFloat(q[2]);
    // DisplayColor layout: r bits 0..4, g 5..10, b 11..15.
    const bits: u16 = r | (g << 5) | (b << 11);
    return cart.Pixel.from_color(@bitCast(bits));
}

/// Called once per frame after the last quantise() call and before anything
/// else draws. palette16 only: every pixel's (r, g, b) fields are its cube
/// cell (0..15 each); replace it with the nearest palette colour.
pub fn end_frame() void {
    if (mode != .palette16) return;
    if (cart.is_wasm) {
        // The simulator's Pixel is byte-swapped; go through DisplayColor.
        const pixels: *[cart.screen_width * cart.screen_height]cart.Pixel = @ptrCast(cart.framebuffer);
        for (pixels) |*p| p.* = palette_pixels[palette_cube[cube_cell(@as(u16, @bitCast(p.to_color())))]];
        return;
    }
    // Hardware: Pixel is the DisplayColor bits; two pixels per word, the
    // field extraction done for both halves at once.
    const words: *[cart.screen_width * cart.screen_height / 2]u32 = @ptrCast(cart.framebuffer);
    for (words) |*w| {
        const v = w.*;
        const cells = cube_cell(v);
        const lo: u32 = @as(u16, @bitCast(palette_pixels[palette_cube[cells & 0xffff]]));
        const hi: u32 = @as(u16, @bitCast(palette_pixels[palette_cube[cells >> 16]]));
        w.* = lo | (hi << 16);
    }
}

/// r bits 0..3 stay, g 5..8 -> 4..7, b 11..14 -> 8..11, in each 16-bit half.
inline fn cube_cell(bits: u32) u32 {
    return (bits & 0x000f_000f) | ((bits >> 1) & 0x00f0_00f0) | ((bits >> 3) & 0x0f00_0f00);
}
