//! Background music (SPEC.md section 8): Satie's Gymnopedie No. 1 as a
//! small chiptune, rendered by the cart into the newer firmware's
//! streaming-audio ring (lib/stream_audio.zig, root docs/SOUND.md
//! section 7). The notes are cart/src/music_data.zig, generated by
//! tools/gen_music.py from a public-domain MIDI file.
//!
//! Eight voices: 0 the lead (a soft 25% pulse with delayed vibrato), 1 its
//! echo (the same line 3/8 of a beat later, quieter), 2..7 a pool for the
//! rolled triangle chords and the triangle bass. The generator assigns
//! every note its voice, so the cart never allocates.
//!
//! Synthesis runs at `rate` (22.05 kHz, half the OS rate) and is
//! upsampled 2x by linear interpolation; envelopes and vibrato step once
//! per `block` samples. Integers only: phase is a u32, amplitude Q16.
//!
//! Timing: `update` once per cart update keeps `target` samples queued
//! (~113 ms: one 50 ms frame at 20 fps plus a slow frame's worth). The
//! song clock is the samples rendered, so a slow frame never changes the
//! tempo; the music just pauses if the ring runs dry. `enabled` false
//! fades the voices out (`fade_k`), stops the song where it is and then
//! pushes nothing; on again resumes from there.
//!
//! The wasm simulator has no streaming audio: main.zig calls `sim_update`
//! instead, which advances the song by one 60 Hz tick and reports each
//! note through `on_note` (the lead, echo and bass go to the simulator's
//! `tone` channels; the chords are dropped).
const std = @import("std");
const stream = @import("stream_audio");
const data = @import("music_data.zig");

/// Starts as `-Dsound` says (main.zig `start`); Start in attract toggles it.
pub var enabled: bool = false;

// ---- Knobs ----

/// Synthesis rate (the OS plays `stream.sample_rate`, twice this).
pub const rate: u32 = stream.sample_rate / 2;
/// Quarter notes per minute ("Lent et douloureux").
pub const bpm: u32 = 64;
/// Synthesis samples per step (a sixteenth of a quarter note).
pub const step_samples: u32 = rate * 60 / (bpm * data.steps_per_quarter);
/// Envelope and vibrato tick, in synthesis samples (~1.45 ms).
pub const block: u32 = 32;
/// OS-rate samples kept queued, and the ring.
pub const target: u32 = 5000;
pub const ring_bytes = 8192;

pub const Wave = enum { triangle, pulse25 };

pub const Inst = struct {
    wave: Wave,
    /// Peak output level 0..255 at full velocity (one voice alone reaches
    /// +-127 around 128 at 255).
    gain: u32,
    attack_ms: u32,
    /// Exponential decay toward `sustain` (fraction of peak, per mille).
    decay_ms: u32,
    sustain: u32,
    release_ms: u32,
    /// Vibrato: +-inc >> vibrato_shift (0 = none), after vibrato_delay_ms.
    vibrato_shift: u5 = 0,
    vibrato_delay_ms: u32 = 0,
};

const lead: Inst = .{ .wave = .pulse25, .gain = 82, .attack_ms = 8, .decay_ms = 1200, .sustain = 450, .release_ms = 250, .vibrato_shift = 7, .vibrato_delay_ms = 350 };
const echo: Inst = .{ .wave = .pulse25, .gain = 32, .attack_ms = 8, .decay_ms = 1200, .sustain = 450, .release_ms = 300, .vibrato_shift = 7, .vibrato_delay_ms = 350 };
const pad: Inst = .{ .wave = .triangle, .gain = 48, .attack_ms = 30, .decay_ms = 1500, .sustain = 350, .release_ms = 300 };
const bass: Inst = .{ .wave = .triangle, .gain = 76, .attack_ms = 5, .decay_ms = 2500, .sustain = 400, .release_ms = 400 };
/// Vibrato rate.
const vibrato_hz: u32 = 5;
/// Release time constant when the music is switched off.
const fade_ms: u32 = 15;

// ---- Notes ----

pub const Note = packed struct(u32) { start: u11, dur: u8, pitch: u7, voice: u3, bass: u1, vel: u2 };

fn note(w: u32) Note {
    return @bitCast(w);
}

// ---- Envelope constants (comptime; no float at run time) ----

/// Q16 per-block step that moves 1 - 1/e of the way in `ms`.
fn k_of(ms: u32) u32 {
    const blocks: f64 = @as(f64, @floatFromInt(ms)) * @as(f64, @floatFromInt(rate)) / (1000.0 * @as(f64, @floatFromInt(block)));
    const k = 65536.0 * (1.0 - @exp(-1.0 / @max(blocks, 1.0)));
    return @max(1, @as(u32, @intFromFloat(k)));
}

fn blocks_of(ms: u32) u32 {
    return @max(1, ms * rate / (1000 * block));
}

const Env = struct {
    wave: Wave,
    gain: u32,
    attack_inc: u32,
    decay_k: u32,
    sustain: u32,
    release_k: u32,
    vibrato_shift: u5,
    vibrato_delay: u32,
};

fn env_of(comptime i: Inst) Env {
    return comptime .{
        .wave = i.wave,
        .gain = i.gain,
        .attack_inc = 65536 / blocks_of(i.attack_ms),
        .decay_k = k_of(i.decay_ms),
        .sustain = i.sustain * 65536 / 1000,
        .release_k = k_of(i.release_ms),
        .vibrato_shift = i.vibrato_shift,
        .vibrato_delay = blocks_of(i.vibrato_delay_ms),
    };
}

const envs = [_]Env{ env_of(lead), env_of(echo), env_of(pad), env_of(bass) };
const fade_k: u32 = k_of(fade_ms);
const lfo_inc: u32 = @intCast((@as(u64, vibrato_hz) << 32) * block / rate);

/// Phase increments of MIDI notes 120..131 at `rate`; lower octaves shift.
const top_octave: [12]u32 = blk: {
    var t: [12]u32 = undefined;
    for (&t, 0..) |*v, k| {
        const hz: f64 = 440.0 * @exp2((@as(f64, @floatFromInt(120 + k)) - 69.0) / 12.0);
        v.* = @intFromFloat(hz * 4294967296.0 / @as(f64, @floatFromInt(rate)));
    }
    break :blk t;
};

pub fn inc_of(pitch: u7) u32 {
    return top_octave[pitch % 12] >> @intCast(10 - pitch / 12);
}

/// The note's frequency in whole Hz (the simulator's `tone`).
pub fn hz_of(pitch: u7) u32 {
    return @intCast((@as(u64, inc_of(pitch)) * rate + (1 << 31)) >> 32);
}

// ---- Voices ----

const Stage = enum(u8) { off, attack, decay, release };

const Voice = struct {
    phase: u32 = 0,
    inc: u32 = 0,
    /// Q16 of the note's peak.
    amp: u32 = 0,
    /// Peak level 0..255 (instrument gain x velocity).
    level: u32 = 0,
    stage: Stage = .off,
    env: u8 = 0,
    /// Steps until the release.
    gate: u16 = 0,
    /// Blocks since the note started (vibrato delay).
    age: u32 = 0,
};

var voices: [8]Voice = @splat(.{});

/// Called for every note the sequencer starts (simulator only).
pub var on_note: ?*const fn (n: Note) void = null;

fn env_index(n: Note) u8 {
    if (n.voice == 0) return 0;
    if (n.voice == 1) return 1;
    return if (n.bass == 1) 3 else 2;
}

fn note_on(n: Note) void {
    if (on_note) |f| f(n);
    const v = &voices[n.voice];
    const e = env_index(n);
    const level = envs[e].gain * (5 + @as(u32, n.vel)) / 8;
    // A voice still sounding restarts from its current output level and
    // keeps its phase, so a retrigger does not click.
    const amp: u32 = if (v.stage == .off) 0 else @min(65536, v.amp * v.level / level);
    v.* = .{ .phase = v.phase, .inc = inc_of(n.pitch), .amp = amp, .level = level, .stage = .attack, .env = e, .gate = n.dur, .age = 0 };
}

// ---- Sequencer ----

var section: u8 = 0;
var cursor: u16 = 0;
var step: u16 = 0;
/// Synthesis samples to the next step boundary (0: fire it now).
var step_left: u32 = 0;
var block_left: u32 = 0;
var lfo: u32 = 0;

/// Gates first (a note of length d ends at its step + d, before a new
/// note on that voice starts), then the notes that start on this step.
noinline fn do_step() void {
    for (&voices) |*v| {
        if (v.gate > 0) {
            v.gate -= 1;
            if (v.gate == 0 and v.stage != .off) v.stage = .release;
        }
    }
    const sec = data.order[section];
    while (cursor < sec.notes.len) : (cursor += 1) {
        const n = note(sec.notes[cursor]);
        if (n.start != step) break;
        note_on(n);
    }
    step += 1;
    if (step == sec.steps) {
        step = 0;
        cursor = 0;
        section = @intCast((section + 1) % data.order.len);
    }
    step_left = step_samples;
}

/// Advance the song by `n` synthesis samples without rendering.
fn advance(n: u32) void {
    var left = n;
    while (true) {
        if (step_left == 0) do_step();
        if (left == 0) return;
        const c = @min(left, step_left);
        step_left -= c;
        left -= c;
    }
}

/// Envelopes and vibrato, once per block. `fade`: everything releases
/// with `fade_k`.
noinline fn tick_envelopes(fade: bool) void {
    lfo +%= lfo_inc;
    for (&voices) |*v| {
        const e = envs[v.env];
        switch (v.stage) {
            .off => continue,
            .attack => {
                v.amp += e.attack_inc;
                if (v.amp >= 65536) {
                    v.amp = 65536;
                    v.stage = .decay;
                }
            },
            .decay => {
                if (v.amp > e.sustain) v.amp -= (v.amp - e.sustain) * e.decay_k >> 16;
            },
            .release => {
                v.amp -|= (v.amp * e.release_k >> 16) + 1;
            },
        }
        if (fade and v.stage != .release) v.stage = .release;
        if (fade) v.amp -|= (v.amp * fade_k >> 16) + 1;
        if (v.stage == .release and v.amp < 256) {
            v.amp = 0;
            v.stage = .off;
        }
        v.age +|= 1;
    }
}

fn sounding() bool {
    for (voices) |v| if (v.stage != .off) return true;
    return false;
}

/// Vibrato offset for `v` this block: +-inc >> shift on a triangle LFO.
fn vibrato_inc(v: *const Voice) u32 {
    const e = envs[v.env];
    if (e.vibrato_shift == 0 or v.age < e.vibrato_delay) return v.inc;
    // Triangle -32768..32767 from the LFO phase.
    const s: i32 = @as(i32, @intCast(@abs(@as(i32, @intCast(lfo >> 15)) - 65536))) - 32768;
    const depth: i32 = @intCast(v.inc >> e.vibrato_shift);
    return @bitCast(@as(i32, @bitCast(v.inc)) + @as(i32, @intCast(@divTrunc(@as(i64, depth) * s, 32768))));
}

/// Mix `out.len` (<= block) synthesis samples of every sounding voice.
noinline fn mix(out: []i32) void {
    @memset(out, 0);
    for (&voices) |*v| {
        if (v.stage == .off) continue;
        const a: i32 = @intCast(v.amp * v.level >> 16);
        if (a == 0) continue;
        const inc = vibrato_inc(v);
        var p = v.phase;
        switch (envs[v.env].wave) {
            .triangle => for (out) |*o| {
                const s: i32 = @as(i32, @intCast(p >> 24)) - 128;
                o.* += (@as(i32, @intCast(@abs(s))) * 2 - 128) * a;
                p +%= inc;
            },
            // Zero mean: +96 for a quarter of the cycle, -32 for the rest.
            .pulse25 => for (out) |*o| {
                o.* += (if (p < 0x4000_0000) @as(i32, 96) else -32) * a;
                p +%= inc;
            },
        }
        v.phase = p;
    }
}

/// The previous synthesis sample (the interpolation's left end).
var last: i32 = 0;
var fading = false;

/// Fill `out` (even length) with OS-rate samples. Returns the count
/// written: short once a fade has finished.
noinline fn fill(out: []u8) usize {
    var buf: [block]i32 = undefined;
    var k: usize = 0;
    while (k + 2 <= out.len) {
        if (fading and !sounding()) break;
        if (!fading and step_left == 0) do_step();
        if (block_left == 0) {
            tick_envelopes(fading);
            block_left = block;
        }
        var c: u32 = @min(block_left, @as(u32, @intCast((out.len - k) / 2)));
        if (!fading) c = @min(c, step_left);
        mix(buf[0..c]);
        for (buf[0..c]) |m| {
            out[k] = to_u8((last + m) >> 1);
            out[k + 1] = to_u8(m);
            last = m;
            k += 2;
        }
        block_left -= c;
        if (!fading) step_left -= c;
    }
    return k;
}

fn to_u8(m: i32) u8 {
    return @intCast(std.math.clamp(128 + (m >> 8), 0, 255));
}

// ---- The cart side ----

/// Undefined, so in .bss: the OS reads only what `push` wrote.
var ring: [ring_bytes]u8 align(8) = undefined;
var scratch: [512]u8 = undefined;
var started = false;

/// Start: flip `enabled` (off fades out, on resumes the song).
pub fn toggle() void {
    enabled = !enabled;
}

/// Once per cart update on the badge (not wasm).
pub noinline fn update() void {
    fading = !enabled;
    if (fading and !sounding()) return;
    if (!started) {
        stream.start(&ring);
        started = true;
    }
    const q = stream.queued();
    if (q >= target) return;
    var want = @min(target - q, stream.free()) & ~@as(u32, 1);
    while (want > 0) {
        const n = fill(scratch[0..@min(want, scratch.len)]);
        if (n == 0) break;
        _ = stream.push(scratch[0..n]);
        want -= @intCast(n);
    }
}

var sim_acc: u32 = 0;

/// Once per simulator update (a fixed 60 Hz there): advance the song by a
/// tick, reporting notes through `on_note`.
pub noinline fn sim_update() void {
    if (!enabled) return;
    sim_acc += rate;
    const n = sim_acc / 60;
    sim_acc %= 60;
    advance(n);
}

/// Synthesis samples in one pass of the song.
pub fn song_samples() u32 {
    var steps: u32 = 0;
    for (data.order) |s| steps += s.steps;
    return steps * step_samples;
}

// ---- Host tests ----

const testing = std.testing;

fn reset_for_test(r: *stream.Ring) void {
    stream.ring = r;
    started = false;
    voices = @splat(.{});
    section = 0;
    cursor = 0;
    step = 0;
    step_left = 0;
    block_left = 0;
    last = 0;
    fading = false;
    on_note = null;
}

test "music: the table is ordered, in range and never overlaps a voice" {
    for (data.order) |sec| {
        var prev: u32 = 0;
        var busy_until: [8]u32 = @splat(0);
        for (sec.notes) |w| {
            const n = note(w);
            try testing.expect(n.start >= prev);
            try testing.expect(n.start < sec.steps);
            try testing.expect(n.dur > 0);
            try testing.expect(n.pitch >= 48 and n.pitch <= 96);
            try testing.expect(busy_until[n.voice] <= n.start);
            busy_until[n.voice] = @as(u32, n.start) + n.dur;
            prev = n.start;
        }
    }
    // Body, ending 1, body, ending 2, rest: about 3.6 minutes.
    try testing.expectEqual(@as(usize, 5), data.order.len);
    try testing.expect(song_samples() / rate > 200 and song_samples() / rate < 240);
}

test "music: pitch table" {
    try testing.expectEqual(@as(u32, 440), hz_of(69));
    try testing.expectEqual(@as(u32, 220), hz_of(57));
    try testing.expectEqual(@as(u32, 740), hz_of(78)); // F#5, the first melody note
}

var lead_notes: u32 = 0;
var echo_notes: u32 = 0;
fn count_note(n: Note) void {
    if (n.voice == 0) lead_notes += 1;
    if (n.voice == 1) echo_notes += 1;
}

test "music: the simulator path plays every lead note once per pass and loops" {
    var r: stream.Ring = undefined;
    reset_for_test(&r);
    on_note = &count_note;
    lead_notes = 0;
    echo_notes = 0;
    enabled = true;
    defer enabled = false;
    // One pass is song_samples(); 60 Hz ticks of rate / 60.
    const ticks = song_samples() / (rate / 60) - 1;
    for (0..ticks) |_| sim_update();
    var expect: u32 = 0;
    for (data.order) |sec| {
        for (sec.notes) |w| expect += @intFromBool(note(w).voice == 0);
    }
    try testing.expectEqual(expect, lead_notes);
    try testing.expectEqual(expect, echo_notes);
    // Into the second pass: the first bass note again, section 0.
    for (0..120) |_| sim_update();
    try testing.expectEqual(@as(u8, 0), section);
    try testing.expect(lead_notes == expect);
}

test "music: the badge path keeps the ring at the target, in range, then fades out" {
    var r: stream.Ring = undefined;
    reset_for_test(&r);
    enabled = true;
    defer enabled = false;
    // Nothing queued while off and silent.
    enabled = false;
    update();
    try testing.expect(!started);
    enabled = true;
    var lo: u8 = 255;
    var hi: u8 = 0;
    // 30 s of 20 fps frames: the OS reads 2205 samples per frame.
    for (0..600) |_| {
        update();
        try testing.expect(stream.queued() >= target - 1);
        var k: u32 = 0;
        while (k < 2205) : (k += 1) {
            const s = ring[r.tail];
            lo = @min(lo, s);
            hi = @max(hi, s);
            r.tail = (r.tail + 1) % ring_bytes;
        }
    }
    // Music, not silence, and no clipping at the rails.
    try testing.expect(hi > 150 and lo < 106);
    try testing.expect(hi < 255 and lo > 0);
    const at = section;
    const at_step = step;
    // Off: a short fade (the OS reads a frame each update), then nothing
    // more is pushed and the song holds where it was.
    enabled = false;
    var updates: u32 = 0;
    while (sounding()) : (updates += 1) {
        try testing.expect(updates < 3);
        r.tail = r.head;
        update();
    }
    r.tail = r.head;
    update();
    try testing.expectEqual(@as(u32, 0), stream.queued());
    try testing.expectEqual(at, section);
    try testing.expectEqual(at_step, step);
}

test "music: a whole pass stays inside the rails (clipping under 0.05%)" {
    var r: stream.Ring = undefined;
    reset_for_test(&r);
    var buf: [4096]u8 = undefined;
    var total: u64 = 0;
    var clipped: u64 = 0;
    var peak: i32 = 0;
    while (total < 2 * @as(u64, song_samples())) {
        const n = fill(&buf);
        for (buf[0..n]) |s| {
            clipped += @intFromBool(s == 0 or s == 255);
            const d: i32 = @as(i32, s) - 128;
            peak = @max(peak, @as(i32, @intCast(@abs(d))));
        }
        total += n;
    }
    // At the knobs above: peak 126 of 127, rms 22, nothing clipped.
    try testing.expect(clipped * 2000 < total);
    try testing.expect(peak > 60);
}
