//! GENERATED by tools/gen_shore.py. Do not edit.
//! Shore texture, PLAN.md "Shore texture format".
pub const width = 256;
pub const height = 48;
pub const palette: [16][3]f32 = .{
    .{ 0.0, 0.0, 0.0 },
    .{ 0.035, 0.065, 0.025 },
    .{ 0.4, 0.21, 0.07 },
    .{ 0.8, 0.56, 0.42 },
    .{ 0.09, 0.04, 0.018 },
    .{ 1.0, 0.48, 0.12 },
    .{ 0.72, 0.42, 0.18 },
    .{ 0.045, 0.065, 0.13 },
    .{ 1.0, 0.86, 0.56 },
    .{ 0.01, 0.008, 0.012 },
    .{ 0.2, 0.05, 0.46 },
    .{ 0.42, 0.17, 0.7 },
    .{ 0.07, 0.02, 0.17 },
    .{ 0.8, 0.07, 0.035 },
    .{ 0.58, 0.31, 0.34 },
    .{ 0.9, 0.84, 0.7 },
};
pub const texels: *const [6144]u8 = @embedFile("shore_texels.bin");
