//! GENERATED by tools/gen_shore.py (currently a stub from the M2 plan commit). Do not edit.
//! Shore texture, PLAN.md "Shore texture format".
pub const width = 256;
pub const height = 32;
pub const palette: [16][3]f32 = .{
    .{ 0.0, 0.0, 0.0 },
    .{ 0.3, 0.22, 0.15 },
    .{ 0.85, 0.55, 0.35 },
    .{ 0.1, 0.12, 0.08 },
    .{ 0.5, 0.5, 0.5 },
    .{ 0.5, 0.5, 0.5 },
    .{ 0.5, 0.5, 0.5 },
    .{ 0.5, 0.5, 0.5 },
    .{ 0.5, 0.5, 0.5 },
    .{ 0.5, 0.5, 0.5 },
    .{ 0.5, 0.5, 0.5 },
    .{ 0.5, 0.5, 0.5 },
    .{ 0.5, 0.5, 0.5 },
    .{ 0.5, 0.5, 0.5 },
    .{ 0.5, 0.5, 0.5 },
    .{ 0.5, 0.5, 0.5 },
};
pub const texels: *const [4096]u8 = @embedFile("shore_texels.bin");
