#!/usr/bin/env python3
"""Generate cart/src/gen/textures.zig from assets/*.png.

    python3 tools/gen_textures.py            # write assets/ and gen/textures.zig
    python3 tools/gen_textures.py --no-assets  # regenerate only textures.zig

--assets (the default) first refreshes the three PNGs from ../snouty-art:
  assets/snouty.png   frame 0 (leftmost 32x32) of out/maze/snouty.png
  assets/iris.png     out/maze/iris.png (32x32)
  assets/iris_big.png ref/iris_mark.png (RGBA 288x288) on black, LANCZOS to 64x64
The maze sheets use magenta #FF00FF as the transparent key; the key is kept
in the PNGs and replaced here by a per-texture background colour.

Output values are u16 in the packed bit layout of cart.DisplayColor
(r in bits 0..4, g in bits 5..10, b in bits 11..15), so that
`cart.Pixel.from_color(@bitCast(v))` gives the right colour on both the
badge and wasm (from_color does the wasm byte swap).
"""
import sys
from pathlib import Path

from PIL import Image

HERE = Path(__file__).resolve().parent.parent
ART = Path("/home/exedev/snouty-art")
ASSETS = HERE / "assets"
OUT = HERE / "cart" / "src" / "gen" / "textures.zig"

KEY = (255, 0, 255)
# Background that replaces the magenta key, per texture. Snouty is tiled
# by the rotozoomer, so a dark navy that stays distinct from its
# near-black outline (41,32,41); the Iris marks sit on black.
TEXTURES = [
    ("snouty", 32, (0x10, 0x20, 0x40)),
    ("iris", 32, (0, 0, 0)),
    ("iris_big", 64, (0, 0, 0)),
]


def refresh_assets() -> None:
    ASSETS.mkdir(exist_ok=True)
    sheet = Image.open(ART / "out/maze/snouty.png").convert("RGB")
    sheet.crop((0, 0, 32, 32)).save(ASSETS / "snouty.png")
    Image.open(ART / "out/maze/iris.png").convert("RGB").save(ASSETS / "iris.png")
    mark = Image.open(ART / "ref/iris_mark.png").convert("RGBA")
    bg = Image.new("RGBA", mark.size, (0, 0, 0, 255))
    flat = Image.alpha_composite(bg, mark).convert("RGB")
    flat.resize((64, 64), Image.LANCZOS).save(ASSETS / "iris_big.png")


def displaycolor_bits(rgb) -> int:
    r, g, b = rgb
    return (r >> 3) | ((g >> 2) << 5) | ((b >> 3) << 11)


def main() -> None:
    if "--no-assets" not in sys.argv:
        refresh_assets()
    lines = [
        "//! Generated by tools/gen_textures.py from assets/*.png; do not edit.",
        "//! Rerun `python3 tools/gen_textures.py` and commit when assets change.",
        "//!",
        "//! Each texture is indexed [y][x]. Values are u16 in the packed bit",
        "//! layout of cart.DisplayColor (r5 in bits 0..4, g6 in bits 5..10,",
        "//! b5 in bits 11..15), so the cart converts each texel once at init()",
        "//! with `cart.Pixel.from_color(@bitCast(v))` (which applies the wasm",
        "//! byte swap). The magenta transparency key of the source sheets is",
        "//! already replaced: snouty by dark navy 0x102040, iris and iris_big",
        "//! by black.",
        "",
    ]
    for name, size, bg in TEXTURES:
        im = Image.open(ASSETS / f"{name}.png").convert("RGB")
        assert im.size == (size, size), (name, im.size)
        px = im.load()
        lines.append(f"pub const {name}: [{size}][{size}]u16 = .{{")
        for y in range(size):
            vals = []
            for x in range(size):
                c = px[x, y]
                if c == KEY:
                    c = bg
                vals.append(f"0x{displaycolor_bits(c):04x}")
            # 8 values per line keeps zig fmt happy and lines short.
            lines.append("    .{")
            for i in range(0, size, 8):
                lines.append("        " + ", ".join(vals[i:i + 8]) + ",")
            lines.append("    },")
        lines.append("};")
        lines.append("")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
