#!/usr/bin/env python3
"""Write cart/src/font8.zig: the OS 8x8 font (sycl-badge/src/font.zig),
characters 0x20..0x7E, as a plain table the renderer draws through its sink.

Why a copy: render.zig is generic over a pixel sink so host tests can check
every put against the marked dirty rects; cart.text writes the framebuffer
itself. Importing sycl-badge/src/font.zig as a module would put that file in
two modules of the firmware build (it belongs to upstream's `board`).

  tools/gen_font.py           # rewrite cart/src/font8.zig
  tools/gen_font.py --check   # exit 1 if the committed file is stale
"""
import re
import sys
from pathlib import Path

here = Path(__file__).resolve().parent
cart = here.parent
root = cart.parent.parent
src = root / "sycl-badge" / "src" / "font.zig"
dst = cart / "cart" / "src" / "font8.zig"

first, last = 0x20, 0x7E


def render() -> str:
    text = src.read_text()
    rows = [int(b, 2) for b in re.findall(r"0b([01]{8})", text)]
    glyphs = [rows[i * 8:(i + 1) * 8] for i in range(len(rows) // 8)]
    out = [
        "//! Generated by tools/gen_font.py from sycl-badge/src/font.zig; do not edit.",
        "//! The OS 8x8 font, characters 0x20..0x7E. Row bytes top to bottom, bit 7",
        "//! is the leftmost pixel, and a 1 bit is ink (inverted from the OS table).",
        "",
        f"pub const first: u8 = 0x{first:02X};",
        f"pub const last: u8 = 0x{last:02X};",
        "",
        f"pub const glyphs = [{last - first + 1}][8]u8{{",
    ]
    for c in range(first, last + 1):
        g = glyphs[c - 0x20]
        ink = ", ".join(f"0x{(~b) & 0xFF:02X}" for b in g)
        ch = chr(c).replace("\\", "\\\\")
        out.append(f"    .{{ {ink} }}, // '{ch}'")
    out.append("};")
    return "\n".join(out) + "\n"


def main() -> int:
    want = render()
    if "--check" in sys.argv[1:]:
        if not dst.exists() or dst.read_text() != want:
            print(f"gen_font: {dst.relative_to(root)} is stale; run tools/gen_font.py", file=sys.stderr)
            return 1
        print("gen_font: up to date")
        return 0
    dst.write_text(want)
    print(f"gen_font: wrote {dst.relative_to(root)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
