#!/usr/bin/env python3
"""Writes the title picture: reference/title.png (the Universal Paperclips
box) scaled to the badge screen and reduced to a 16-colour palette.

Outputs (committed, read by cart/src/ui/title.zig):
  cart/src/ui/gen/title.zig   width, height, the palette as RGB565-ready
                              0xRRGGBB values
  cart/src/ui/gen/title.bin   4 bits per pixel, row-major, two pixels per
                              byte (low nibble first)

  tools/gen_title.py               # rewrite both
  tools/gen_title.py --check       # exit 1 if either is stale
  tools/gen_title.py --png out.png # preview the reduced picture (x3)
"""
import argparse
import os
import sys

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
CART = os.path.join(HERE, "..")
SRC = os.path.join(CART, "reference", "title.png")
OUT_ZIG = os.path.join(CART, "cart", "src", "ui", "gen", "title.zig")
OUT_BIN = os.path.join(CART, "cart", "src", "ui", "gen", "title.bin")

# The picture fills the screen width; 453x355 scales to 160x125.
WIDTH = 160


def reduce():
    im = Image.open(SRC).convert("RGB")
    h = round(im.height * WIDTH / im.width)
    im = im.resize((WIDTH, h), Image.LANCZOS)
    # 16 grey levels, evenly spaced, no dithering: the picture is almost
    # entirely grey (black text, white and grey box faces), and flat faces
    # stay flat on the small LCD. An adaptive palette spent most of its
    # entries on near-whites and lost the text.
    g = im.convert("L")
    data = g.get_flattened_data() if hasattr(g, "get_flattened_data") else g.getdata()
    # index 0 = white, 15 = black
    pix = [15 - min(15, (v * 15 + 127) // 255) for v in data]
    colors = []
    for i in range(16):
        v = round((15 - i) * 255 / 15)
        colors.append((v, v, v))
    return WIDTH, h, colors, pix


def render():
    w, h, colors, pix = reduce()
    data = bytearray()
    for i in range(0, len(pix), 2):
        lo = pix[i]
        hi = pix[i + 1] if i + 1 < len(pix) else 0
        data.append(lo | hi << 4)
    lines = [
        "//! Generated by tools/gen_title.py from reference/title.png; do not edit.",
        "//! title.bin: 4 bits per pixel, row-major, low nibble first.",
        "",
        "pub const width: u32 = %d;" % w,
        "pub const height: u32 = %d;" % h,
        "pub const palette = [16]u32{",
    ]
    for c in colors:
        lines.append("    0x%02X%02X%02X," % c)
    lines += ["};", "pub const pixels: *const [%d]u8 = @embedFile(\"title.bin\");" % len(data), ""]
    return "\n".join(lines), bytes(data), (w, h, colors, pix)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--png")
    a = ap.parse_args()
    text, data, (w, h, colors, pix) = render()
    if a.png:
        im = Image.new("RGB", (w, h))
        im.putdata([colors[p] for p in pix])
        im.resize((w * 3, h * 3), Image.NEAREST).save(a.png)
        return
    if a.check:
        ok = os.path.exists(OUT_ZIG) and open(OUT_ZIG).read() == text
        ok = ok and os.path.exists(OUT_BIN) and open(OUT_BIN, "rb").read() == data
        if not ok:
            print("gen_title: cart/src/ui/gen/title.* is stale; run tools/gen_title.py", file=sys.stderr)
            sys.exit(1)
        return
    with open(OUT_ZIG, "w") as f:
        f.write(text)
    with open(OUT_BIN, "wb") as f:
        f.write(data)


if __name__ == "__main__":
    main()
