#!/usr/bin/env python3
"""Writes cart/src/ui/gen/font5x7.zig: the cart's 5x7 font in a 6x8 cell.

The glyphs are the classic 5x7 LCD font (the Adafruit GFX `glcdfont`
shapes, which descend from the HD44780 ROM): five column bytes per glyph,
bit 0 the top row, bit 7 the descender row. ASCII 0x20..0x7E, plus a few
extra codes the cart uses:

  0x7F  (c) copyright sign (the ending's "(c) 2017 Everybody House Games")
  0x80  left-pointing triangle (page tab)
  0x81  right-pointing triangle (page tab, cursor)
  0x82  degree-like small square (quantum chip off, unused glyph slot)

The table is data, not code: the cart reads it at draw time, so no
comptime work is involved (CLAUDE.md: keep comptime light).

  tools/gen_font.py            # rewrite the .zig (and --png preview)
  tools/gen_font.py --check    # exit 1 if the committed file is stale
  tools/gen_font.py --png out.png
"""
import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "cart", "src", "ui", "gen", "font5x7.zig")

GLYPHS = """
00 00 00 00 00
00 00 5F 00 00
00 07 00 07 00
14 7F 14 7F 14
24 2A 7F 2A 12
23 13 08 64 62
36 49 56 20 50
00 08 07 03 00
00 1C 22 41 00
00 41 22 1C 00
2A 1C 7F 1C 2A
08 08 3E 08 08
00 80 70 30 00
08 08 08 08 08
00 00 60 60 00
20 10 08 04 02
3E 51 49 45 3E
00 42 7F 40 00
72 49 49 49 46
21 41 49 4D 33
18 14 12 7F 10
27 45 45 45 39
3C 4A 49 49 31
41 21 11 09 07
36 49 49 49 36
46 49 49 29 1E
00 00 14 00 00
00 40 34 00 00
00 08 14 22 41
14 14 14 14 14
00 41 22 14 08
02 01 59 09 06
3E 41 5D 59 4E
7C 12 11 12 7C
7F 49 49 49 36
3E 41 41 41 22
7F 41 41 41 3E
7F 49 49 49 41
7F 09 09 09 01
3E 41 41 51 73
7F 08 08 08 7F
00 41 7F 41 00
20 40 41 3F 01
7F 08 14 22 41
7F 40 40 40 40
7F 02 1C 02 7F
7F 04 08 10 7F
3E 41 41 41 3E
7F 09 09 09 06
3E 41 51 21 5E
7F 09 19 29 46
26 49 49 49 32
03 01 7F 01 03
3F 40 40 40 3F
1F 20 40 20 1F
3F 40 38 40 3F
63 14 08 14 63
03 04 78 04 03
61 59 49 4D 43
00 7F 41 41 41
02 04 08 10 20
00 41 41 41 7F
04 02 01 02 04
40 40 40 40 40
00 03 07 08 00
20 54 54 78 40
7F 28 44 44 38
38 44 44 44 28
38 44 44 28 7F
38 54 54 54 18
00 08 7E 09 02
18 A4 A4 9C 78
7F 08 04 04 78
00 44 7D 40 00
20 40 40 3D 00
7F 10 28 44 00
00 41 7F 40 00
7C 04 78 04 78
7C 08 04 04 78
38 44 44 44 38
FC 18 24 24 18
18 24 24 18 FC
7C 08 04 04 08
48 54 54 54 24
04 04 3F 44 24
3C 40 40 20 7C
1C 20 40 20 1C
3C 40 30 40 3C
44 28 10 28 44
4C 90 90 90 7C
44 64 54 4C 44
00 08 36 41 00
00 00 77 00 00
00 41 36 08 00
02 01 02 04 02
3E 41 5D 55 41
08 1C 3E 7F 00
00 7F 3E 1C 08
00 1C 14 1C 00
"""

FIRST = 0x20


def glyphs():
    rows = [ln.split() for ln in GLYPHS.strip().splitlines()]
    out = [[int(b, 16) for b in r] for r in rows]
    assert all(len(g) == 5 for g in out)
    return out


def render():
    g = glyphs()
    lines = [
        "//! Generated by tools/gen_font.py; do not edit by hand.",
        "//! The 5x7 font in a 6x8 cell: five column bytes per glyph, bit 0 the",
        "//! top row, bit 7 the descender row; codes 0x%02X..0x%02X." % (FIRST, FIRST + len(g) - 1),
        "",
        "pub const first: u8 = 0x%02X;" % FIRST,
        "pub const count: usize = %d;" % len(g),
        "",
        "pub const columns = [count][5]u8{",
    ]
    for i, cols in enumerate(g):
        c = FIRST + i
        name = chr(c) if 0x20 < c < 0x7F else "0x%02X" % c
        if name == "\\":
            name = "backslash"
        lines.append("    .{ %s }, // %s" % (", ".join("0x%02X" % b for b in cols), name))
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def png(path):
    from PIL import Image

    g = glyphs()
    per = 16
    rows = (len(g) + per - 1) // per
    im = Image.new("L", (per * 6 * 4, rows * 8 * 4), 255)
    for i, cols in enumerate(g):
        ox, oy = (i % per) * 6, (i // per) * 8
        for x, b in enumerate(cols):
            for y in range(8):
                if b >> y & 1:
                    for dx in range(4):
                        for dy in range(4):
                            im.putpixel(((ox + x) * 4 + dx, (oy + y) * 4 + dy), 0)
    im.save(path)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--png")
    a = ap.parse_args()
    text = render()
    if a.check:
        cur = open(OUT).read() if os.path.exists(OUT) else ""
        if cur != text:
            print("gen_font: %s is stale; run tools/gen_font.py" % OUT, file=sys.stderr)
            sys.exit(1)
        return
    if a.png:
        png(a.png)
        return
    with open(OUT, "w") as f:
        f.write(text)


if __name__ == "__main__":
    main()
