//! Generated by tools/gen_ports_table.py: do not edit. The peripheral
//! each well-known game gets at power-on (core/ports.zig `detect`,
//! docs/MULTIPLAYER.md). A row is an FNV-1a 32 hash with its low
//! three bits replaced by the `ports.Kind`: the hash of the header
//! serial (0x180-0x18D), or for a placeholder serial that several
//! games share, of the serial and the header checksum (0x180-0x18F).
//! Literal data, no comptime work (CLAUDE.md).

pub const count = 61;
pub const kind_mask: u32 = 7;

pub const rows = [count]u32{
    0xFD43AD0A, // GM MK-1573-00   Mega Bomberman  (verified)
    0x117A8A52, // GM T-48123 -00  Gauntlet IV
    0xEA201E22, // GM T-081326 00  NBA Jam
    0xEB201FB2, // GM T-081326 01  NBA Jam (rev 1)
    0x8BD57CA2, // GM T-81033  00  NBA Jam (JP)
    0x6E994C4A, // GM 00004801-00  Columns III (JP)
    0xB341283A, // GM T-23056 -00  Columns III
    0x127BF592, // GM T-81496 -00  Dragon: The Bruce Lee Story
    0x2BDE3792, // GM T-70286 -00  Dragon: The Bruce Lee Story (EU)
    0x582BF622, // GM T-177016-00  Street Racer
    0x48DE87EA, // GM T-95146-00   Tiny Toon Adventures: ACME All-Stars
    0x5B1A6992, // GM T-125016-00  The Lost Vikings
    0x58660862, // GM T-.oOOo.    B9E0  The Lost Vikings (EU)
    0x32F837AA, // GM 00004107-00  Party Quiz Mega Q
    0x08D3F73A, // GM G-4118  -00  Puzzle & Action: Tant-R
    0x1FB9F11A, // GM G-4128  -00  Puzzle & Action: Ichidant-R
    0xF39075C2, // GM MK-1224 -00  Wimbledon Championship Tennis
    0x119D70EA, // GM MK-1224 -50  Wimbledon Championship Tennis (EU)
    0x8C853B1A, // GM T-119066-00  Hoops Shut Up and Jam!
    0x06581302, // GM T-119186-00  Barkley Shut Up and Jam 2
    0xC18154CA, // GM MK-1233 -00  World Championship Soccer II
    0xEFFB720A, // GM G-004122-00  Yuu Yuu Hakusho: Makyou Toitsusen
    0xB0256B72, // GM G-4133-00    Pepenga Pengo
    0xD609C40A, // GM MK-1221 -00  NBA Action '94
    0x1194FEF2, // GM MK-1236 -00  NBA Action '95
    0x797FF942, // GM MK-1240 -00  Prime Time NFL Football
    0x987216EA, // GM MK-1227 -00  College Football's National Championship
    0xDA5FBF6D, // GM T-106253-00  General Chaos
    0x716ECE05, // GM T-50626 -00  General Chaos (EU)
    0xD7E1FA65, // GM T-      -00 C5F1  FIFA International Soccer
    0x5F8280D5, // GM T-50706 -00  FIFA International Soccer
    0x413AD265, // GM T-50916 -00  FIFA Soccer 95
    0x423AD3F5, // GM T-50916 -01  FIFA Soccer 95 (rev 1)
    0x7CDC6175, // GM T-172086-00  FIFA Soccer 96
    0x06DBDE85, // GM T-172156-01  FIFA 97: Gold Edition
    0xA81A38C5, // GM T-172206-00  FIFA Road to World Cup 98
    0x0FA3E265, // GM T-50656 -00  NHL Hockey '94
    0xA2B8897D, // GM T-50856 -00  NHL 95
    0x2B60FAE5, // GM T-172036-00  NHL 96
    0x21019665, // GM T-172146-03  NHL 97
    0xF16E5465, // GM T-172176-00  NHL 98
    0xCA506BB5, // GM T-106263-00  Madden NFL '94
    0x77E7491D, // GM T-50676 -00  Madden NFL '94
    0x63841295, // GM T-50926 -00  Madden NFL '95
    0x349CDA65, // GM T-172076-00  Madden NFL 96
    0x3D1ED7D5, // GM T-172136-00  Madden NFL 97
    0xCCCD9895, // GM T-172196-00  Madden NFL 98
    0x7B0209D5, // GM T-50936 -00  NBA Live 95
    0xB3FFEED5, // GM T-172056-00  NBA Live 96
    0x2163E2E5, // GM T-172166-00  NBA Live 97
    0xBF4E55D5, // GM T-172186-00  NBA Live 98
    0x4D82EEFD, // GM T-      -00 5364  NBA Showdown '94
    0x3BF13FFD, // GM T-50756 -00  NBA Showdown '94
    0x8B4B781D, // GM T-50606 -00  Bill Walsh College Football
    0x6F34A875, // GM T-50826 -00  Bill Walsh College Football '95
    0x3F2DAB95, // GM T-50956 -00  Rugby World Cup 1995
    0x9B82572D, // GM T-50766 -00  Mutant League Hockey
    0x7F56EC8E, // GM T-120096-50  Micro Machines 2: Turbo Tournament
    0x8E7AB73E, // GM 00000000-00 168B  Micro Machines Military
    0x18FA2816, // GM T-123456-00 1EAE  Pete Sampras Tennis '96
    0xE250F6C6, // GM XXXXXXXX-XX DF39  Super Skidmarks
};
