//! Host tests for lib/party.zig (lobby protocol v1 client), lib/cart_serial.zig
//! (the ring ABI) and lib/party_virtual.zig (the `badge lobby` model).
//!
//! Byte vectors: section "frames.py vectors" holds every v1 message both
//! ways and the COBS edge cases, generated by running the reference
//! encoders of the fork's host tool (`tools/badge/badge/frames.py`,
//! `Hello/Send/Ping/Leave/Welcome/Roster/Data/Pong/Error(...).pack()`,
//! `encode`, `cobs_encode`) at sycl-badge-fork main 8ca6da6; the fork's
//! cart side (`src/os/cart/lobby.zig`) encodes COBS the same way. The
//! hand-written vectors further down follow fork/CART_SERIAL.md's message
//! tables and the Wikipedia COBS examples, except where those differ from
//! the reference (a full 254-byte block at the very end gets a trailing
//! 0x01 block code from both reference encoders).
const std = @import("std");
const party = @import("../party.zig");
const cart_serial = @import("../cart_serial.zig");
const pv = @import("../party_virtual.zig");

const Port = cart_serial.Virtual(.{});
const Client = party.Client(Port);
const expectEqual = std.testing.expectEqual;
const expectEqualSlices = std.testing.expectEqualSlices;
const expect = std.testing.expect;

// ---- COBS ----------------------------------------------------------------

fn expect_cobs(decoded: []const u8, encoded: []const u8) !void {
    var enc: [400]u8 = undefined;
    const n = party.cobs_encode(decoded, &enc);
    try expectEqualSlices(u8, encoded, enc[0..n]);
    var dec: [400]u8 = undefined;
    const m = party.cobs_decode(encoded, &dec).?;
    try expectEqualSlices(u8, decoded, dec[0..m]);
}

test "cobs: the reference examples" {
    try expect_cobs(&.{0x00}, &.{ 0x01, 0x01 });
    try expect_cobs(&.{ 0x00, 0x00 }, &.{ 0x01, 0x01, 0x01 });
    try expect_cobs(&.{ 0x00, 0x11, 0x00 }, &.{ 0x01, 0x02, 0x11, 0x01 });
    try expect_cobs(&.{ 0x11, 0x22, 0x00, 0x33 }, &.{ 0x03, 0x11, 0x22, 0x02, 0x33 });
    try expect_cobs(&.{ 0x11, 0x22, 0x33, 0x44 }, &.{ 0x05, 0x11, 0x22, 0x33, 0x44 });
    try expect_cobs(&.{ 0x11, 0x00, 0x00, 0x00 }, &.{ 0x02, 0x11, 0x01, 0x01, 0x01 });
    // 01..FE (254 bytes) -> FF 01..FE 01 (frames.py and lobby.zig close
    // with an empty block; Wikipedia's example stops after FE)
    var src: [255]u8 = undefined;
    var exp: [257]u8 = undefined;
    for (0..254) |i| src[i] = @intCast(i + 1);
    exp[0] = 0xFF;
    for (0..254) |i| exp[1 + i] = @intCast(i + 1);
    exp[255] = 0x01;
    try expect_cobs(src[0..254], exp[0..256]);
    // Wikipedia's shorter form decodes to the same bytes.
    var dec: [300]u8 = undefined;
    try expectEqualSlices(u8, src[0..254], dec[0..party.cobs_decode(exp[0..255], &dec).?]);
    // 00..FE (255 bytes) -> 01 FF 01..FE 01 (the same closing block)
    for (0..255) |i| src[i] = @intCast(i);
    exp[0] = 0x01;
    exp[1] = 0xFF;
    for (0..254) |i| exp[2 + i] = @intCast(i + 1);
    exp[256] = 0x01;
    try expect_cobs(src[0..255], exp[0..257]);
    // 01..FF (255 bytes) -> FF 01..FE 02 FF
    for (0..255) |i| src[i] = @intCast(i + 1);
    exp[0] = 0xFF;
    for (0..254) |i| exp[1 + i] = @intCast(i + 1);
    exp[255] = 0x02;
    exp[256] = 0xFF;
    try expect_cobs(src[0..255], exp[0..257]);
}

test "cobs: malformed frames are refused" {
    var dec: [16]u8 = undefined;
    try expect(party.cobs_decode(&.{ 0x05, 0x01 }, &dec) == null); // block past the end
    try expect(party.cobs_decode(&.{ 0x02, 0x00 }, &dec) == null); // a zero inside
    try expect(party.cobs_decode(&.{ 0x09, 1, 2, 3, 4, 5, 6, 7, 8 }, dec[0..4]) == null); // too long
}

// ---- a client on a bare virtual port ---------------------------------------

const opts: party.Options = .{
    .game = party.pad(8, "SNOUTDM1"),
    .name = party.pad(12, "ADRIAN"),
    .max_players = 16,
};

/// Everything the client wrote so far.
fn take(c: *Client, buf: []u8) []u8 {
    const n = c.port.os_take(buf);
    return buf[0..n];
}

fn put(c: *Client, bytes: []const u8) void {
    std.debug.assert(c.port.os_put(bytes) == bytes.len);
}

const hello_wire = [_]u8{ 0x11, 0x01, 0x01, 0x53, 0x4E, 0x4F, 0x55, 0x54, 0x44, 0x4D, 0x31, 0x41, 0x44, 0x52, 0x49, 0x41, 0x4E, 0x01, 0x01, 0x01, 0x01, 0x01, 0x02, 0x10, 0x00 };
const welcome_wire = [_]u8{ 0x04, 0x81, 0x01, 0x02, 0x02, 0x10, 0x00 };
const roster_wire = [_]u8{ 0x03, 0x82, 0x02, 0x07, 0x41, 0x44, 0x52, 0x49, 0x41, 0x4E, 0x01, 0x01, 0x01, 0x01, 0x01, 0x03, 0x02, 0x42, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x00 };
const data_wire = [_]u8{ 0x04, 0x83, 0x03, 0x05, 0x02, 0xC0, 0x00 };
const pong_wire = [_]u8{ 0x06, 0x84, 0x78, 0x56, 0x34, 0x12, 0x00 };
const error_wire = [_]u8{ 0x0D, 0x8F, 0x03, 0x4E, 0x4F, 0x54, 0x20, 0x4A, 0x4F, 0x49, 0x4E, 0x45, 0x44, 0x00 };

test "client: states, the flush byte and HELLO" {
    var c = Client.init(.{ .os_supported = false }, opts);
    try expect(c.poll() == null);
    try expectEqual(party.State.unsupported, c.state());

    c = Client.init(.{}, opts);
    try expect(c.poll() == null);
    try expectEqual(party.State.disconnected, c.state());
    c.port.host_open = true;
    try expect(c.poll() == null);
    try expectEqual(party.State.joining, c.state());
    var buf: [512]u8 = undefined;
    const out = take(&c, &buf);
    // A lone 0x00 on (re)connect, then HELLO.
    try expectEqual(@as(u8, 0), out[0]);
    try expectEqualSlices(u8, &hello_wire, out[1..]);
    try expectEqualSlices(u8, &hello_wire, blk: {
        var f: [64]u8 = undefined;
        const n = party.encode_frame(&c.hello_body(), &f);
        break :blk f[0..n];
    });
}

test "client: every host message parses" {
    var c = Client.init(.{}, opts);
    c.port.host_open = true;
    _ = c.poll();
    var buf: [512]u8 = undefined;
    _ = take(&c, &buf);
    put(&c, &welcome_wire);
    put(&c, &roster_wire);
    put(&c, &data_wire);
    put(&c, &pong_wire);
    put(&c, &error_wire);
    put(&c, &.{ 0x02, 0x77, 0x00 }); // an unknown type: ignored
    const w = c.poll().?.joined;
    try expectEqual(@as(u8, 2), w.you);
    try expectEqual(@as(u8, 0), w.room);
    try expectEqual(@as(u8, 16), w.max_players);
    try expectEqual(party.State.joined, c.state());
    try expect(c.poll().? == .roster);
    try expectEqual(@as(u16, 0b101), c.present);
    try expectEqualSlices(u8, "ADRIAN", c.name(0));
    try expectEqualSlices(u8, "B", c.name(2));
    const d = c.poll().?.data;
    try expectEqual(@as(u8, 3), d.from);
    try expectEqualSlices(u8, &.{ 0x05, 0x00, 0xC0 }, d.bytes);
    try expectEqual(@as(u32, 0x12345678), c.poll().?.pong);
    const e = c.poll().?.err;
    try expectEqual(party.Err.not_joined, e.code);
    try expectEqualSlices(u8, "NOT JOINED", e.message);
    try expect(c.poll() == null);
    // ERROR 3 (the host forgot us): HELLO again.
    try expectEqualSlices(u8, &hello_wire, take(&c, &buf));
}

test "client: every cart message encodes" {
    var c = Client.init(.{}, opts);
    c.port.host_open = true;
    _ = c.poll();
    var buf: [512]u8 = undefined;
    _ = take(&c, &buf);
    try expect(!c.broadcast(&.{1})); // not joined: nothing written
    try expectEqual(@as(usize, 0), take(&c, &buf).len);
    put(&c, &welcome_wire);
    _ = c.poll();
    try expect(c.broadcast(&.{ 0x05, 0x00, 0xC0 }));
    try expectEqualSlices(u8, &.{ 0x04, 0x02, 0xFF, 0x05, 0x02, 0xC0, 0x00 }, take(&c, &buf));
    try expect(c.broadcast_echo(&.{0x42}));
    try expectEqualSlices(u8, &.{ 0x04, 0x02, 0xFE, 0x42, 0x00 }, take(&c, &buf));
    try expect(c.send(3, "hi"));
    try expectEqualSlices(u8, &.{ 0x05, 0x02, 0x03, 0x68, 0x69, 0x00 }, take(&c, &buf));
    try expect(c.ping(0x12345678));
    try expectEqualSlices(u8, &.{ 0x06, 0x03, 0x78, 0x56, 0x34, 0x12, 0x00 }, take(&c, &buf));
    c.leave();
    try expectEqualSlices(u8, &.{ 0x02, 0x04, 0x00 }, take(&c, &buf));
    try expectEqual(party.State.idle, c.state());
    c.join();
    try expectEqualSlices(u8, &hello_wire, take(&c, &buf));
}

test "client: resync on 0x00, long and broken frames dropped, empty frames ignored" {
    var c = Client.init(.{}, opts);
    c.port.host_open = true;
    _ = c.poll();
    // Mid-frame garbage (a listener joining mid-stream), then a frame.
    put(&c, &.{ 0x33, 0x44, 0x00 });
    put(&c, &.{ 0x00, 0x00 });
    put(&c, &.{ 0x05, 0x81, 0x00 }); // a block past the end
    put(&c, &welcome_wire);
    try expect(c.poll().? == .joined);
    // 300 non-zero bytes: too long, skipped to the next 0x00.
    var long: [300]u8 = @splat(0x55);
    put(&c, &long);
    put(&c, &.{0x00});
    put(&c, &data_wire);
    try expectEqual(@as(u8, 3), c.poll().?.data.from);
    try expect(c.poll() == null);
    try expect(c.dec.dropped >= 2);
}

test "client: re-HELLO when the port connects again" {
    var c = Client.init(.{}, opts);
    c.port.host_open = true;
    _ = c.poll();
    var buf: [512]u8 = undefined;
    _ = take(&c, &buf);
    put(&c, &welcome_wire);
    try expect(c.poll().? == .joined);
    c.port.host_open = false;
    try expect(c.poll().? == .lost);
    try expectEqual(party.State.disconnected, c.state());
    c.port.host_open = true;
    try expect(c.poll() == null);
    try expectEqual(party.State.joining, c.state());
    const out = take(&c, &buf);
    try expectEqual(@as(u8, 0), out[0]);
    try expectEqualSlices(u8, &hello_wire, out[1..]);
}

test "client: a frame is written whole or not at all" {
    var c = Client.init(.{}, opts);
    c.port.host_open = true;
    _ = c.poll();
    var buf: [2048]u8 = undefined;
    _ = take(&c, &buf);
    put(&c, &welcome_wire);
    _ = c.poll();
    const data: [200]u8 = @splat(7);
    var sent: u32 = 0;
    while (c.broadcast(&data)) sent += 1;
    try expectEqual(@as(u32, 1024 / 204), sent);
    try expect(c.stats.tx_full > 0);
    const out = take(&c, &buf);
    try expectEqual(@as(usize, sent * 204), out.len);
    try expect(c.broadcast(&data));
}

test "client: HELLO again while no WELCOME comes (a lost HELLO)" {
    var c = Client.init(.{}, opts);
    c.port.host_open = true;
    _ = c.poll();
    var buf: [512]u8 = undefined;
    _ = take(&c, &buf); // 0x00 + HELLO, lost (the host flushed its input)
    c.retry_hello();
    try expectEqualSlices(u8, &hello_wire, take(&c, &buf));
    put(&c, &welcome_wire);
    try expect(c.poll().? == .joined);
    c.retry_hello(); // joined: nothing
    try expectEqual(@as(usize, 0), take(&c, &buf).len);
    c.leave();
    _ = take(&c, &buf);
    c.retry_hello(); // idle: nothing
    try expectEqual(@as(usize, 0), take(&c, &buf).len);
}

// ---- the relay model -----------------------------------------------------------

const Bench = struct {
    relay: pv.Relay,
    c: [6]Client,
    now: u64,

    fn init(b: *Bench, games: []const []const u8) void {
        b.relay.init(7);
        b.now = 0;
        for (games, 0..) |g, i| {
            var o = opts;
            o.game = party.pad(8, g);
            o.name = party.pad(12, &.{ 'P', '0' + @as(u8, @intCast(i)) });
            b.c[i] = Client.init(.{}, o);
        }
    }

    fn plug(b: *Bench, i: usize) void {
        b.relay.attach(i, pv.Endpoint.of(Port, &b.c[i].port), 1000, 500);
    }

    /// Run `us` in 1 ms steps; events of client i go to its log.
    fn run(b: *Bench, n: usize, us: u64, logs: ?*Logs) void {
        const end = b.now + us;
        while (b.now < end) {
            b.now += 1000;
            b.relay.advance(b.now);
            for (b.c[0..n], 0..) |*c, i| {
                while (c.poll()) |ev| if (logs) |l| l.add(i, ev);
            }
        }
    }
};

/// DATA payloads received per client (first byte of each, plus the sender).
const Logs = struct {
    data: [6][64]u16 = undefined,
    n: [6]u8 = @splat(0),
    rosters: [6]u8 = @splat(0),

    fn add(l: *Logs, i: usize, ev: party.Event) void {
        switch (ev) {
            .data => |d| {
                l.data[i][l.n[i]] = @as(u16, d.from) << 8 | d.bytes[0];
                l.n[i] += 1;
            },
            .roster => l.rosters[i] += 1,
            else => {},
        }
    }
};

test "relay: rooms per game, lowest free id, WELCOME then ROSTER" {
    var b: Bench = undefined;
    b.init(&.{ "SNOUTDM1", "SNOUTDM1", "OTHER", "SNOUTDM1" });
    for (0..4) |i| b.plug(i);
    b.run(4, 20_000, null);
    for (0..4) |i| try expectEqual(party.State.joined, b.c[i].state());
    // Same game: ids 0, 1, 2 in one room; the other game its own room.
    try expectEqual(@as(?u8, 0), b.c[0].me());
    try expectEqual(@as(?u8, 1), b.c[1].me());
    try expectEqual(@as(?u8, 0), b.c[2].me());
    try expectEqual(@as(?u8, 2), b.c[3].me());
    try expect(b.c[2].room != b.c[0].room);
    try expectEqual(@as(u16, 0b111), b.c[0].present);
    try expectEqual(@as(u16, 0b1), b.c[2].present);
    try expectEqualSlices(u8, "P3", b.c[1].name(2));
    // Player 1 leaves; a newcomer takes the lowest free id, 1.
    b.relay.unplug(1);
    b.run(4, 20_000, null);
    try expectEqual(@as(u16, 0b101), b.c[0].present);
    try expectEqual(party.State.disconnected, b.c[1].state());
    b.relay.replug(1);
    b.run(4, 20_000, null);
    try expectEqual(@as(?u8, 1), b.c[1].me());
    try expectEqual(@as(u16, 0b111), b.c[3].present);
}

test "relay: SEND fan-out, self-echo, one order for everyone" {
    var b: Bench = undefined;
    b.init(&.{ "G", "G", "G", "G" });
    for (0..4) |i| b.plug(i);
    b.run(4, 20_000, null);
    var logs: Logs = .{};
    // Everyone sends at once, several frames each, interleaved; badge 3
    // echoes to itself.
    for (0..5) |k| {
        for (0..4) |i| {
            const tag: u8 = @intCast(k * 16 + i);
            const ok = if (i == 3) b.c[i].broadcast_echo(&.{tag}) else b.c[i].broadcast(&.{tag});
            try expect(ok);
        }
        b.run(4, 1000, &logs);
    }
    try expect(b.c[0].send(2, &.{0xEE})); // only to player 2
    try expect(b.c[0].send(9, &.{0xEF})); // absent: dropped
    b.run(4, 30_000, &logs);
    // Each badge got every frame but its own (3 got its own too).
    try expectEqual(@as(u8, 15), logs.n[0]);
    try expectEqual(@as(u8, 15 + 1), logs.n[2]);
    try expectEqual(@as(u8, 20), logs.n[3]);
    // One order: removing each badge's own frames (and the directed one),
    // the sequences agree.
    var seq: [4][64]u16 = undefined;
    var len: [4]usize = @splat(0);
    for (0..4) |i| {
        for (logs.data[i][0..logs.n[i]]) |x| {
            if (x & 0xFF == 0xEE) continue;
            seq[i][len[i]] = x;
            len[i] += 1;
        }
    }
    for (0..4) |i| for (0..4) |j| {
        var a: [64]u16 = undefined;
        var na: usize = 0;
        for (seq[i][0..len[i]]) |x| if (x >> 8 != j and x >> 8 != i) {
            a[na] = x;
            na += 1;
        };
        var c: [64]u16 = undefined;
        var nc: usize = 0;
        for (seq[j][0..len[j]]) |x| if (x >> 8 != j and x >> 8 != i) {
            c[nc] = x;
            nc += 1;
        };
        try expectEqualSlices(u16, a[0..na], c[0..nc]);
    };
    // 3's own echoed frames sit at their place in that order: in 3's log
    // they come in the same order relative to 0's frames as in 1's log.
    try expectEqual(@as(u16, 3 << 8 | 3), logs.data[3][
        blk: {
            for (logs.data[3][0..logs.n[3]], 0..) |x, k| if (x >> 8 == 3) break :blk k;
            unreachable;
        }
    ]);
}

test "relay: PING, ERROR 3, unknown types" {
    var b: Bench = undefined;
    b.init(&.{"G"});
    b.c[0].want_join = false;
    b.plug(0);
    b.run(1, 5000, null);
    try expectEqual(party.State.idle, b.c[0].state());
    try expect(b.c[0].ping(77));
    // SEND before WELCOME, written by hand.
    try expect(b.c[0].write_body(&.{ party.T.send, 0xFF, 1 }));
    try expect(b.c[0].write_body(&.{0x55}));
    var got_pong = false;
    var got_err = false;
    const end = b.now + 10_000;
    while (b.now < end) {
        b.now += 1000;
        b.relay.advance(b.now);
        while (b.c[0].poll()) |ev| switch (ev) {
            .pong => |t| got_pong = t == 77,
            .err => |e| got_err = e.code == party.Err.not_joined,
            else => {},
        };
    }
    try expect(got_pong and got_err);
}

test "relay: unplug drops in-flight bytes for everyone; overflow removes the player" {
    var b: Bench = undefined;
    b.init(&.{ "G", "G", "G" });
    for (0..3) |i| b.plug(i);
    b.run(3, 20_000, null);
    var logs: Logs = .{};
    // 1 writes and is unplugged before the relay handles it: no one gets it.
    try expect(b.c[1].broadcast(&.{0x11}));
    b.relay.advance(b.now); // taken off the badge, still in flight
    b.relay.unplug(1);
    b.run(3, 20_000, &logs);
    try expectEqual(@as(u8, 0), logs.n[0]);
    try expectEqual(@as(u8, 0), logs.n[2]);
    try expectEqual(@as(u16, 0b101), b.c[0].present);
    // 2 stops reading; 0 floods: more than the limit waits for 2 for a second, 2 is removed,
    // 0 sees a plain leave.
    // (The stuck limit scaled down from 64 KiB to 8 KiB.)
    b.relay.stuck_limit = 8 * 1024;
    b.c[2].port.deaf = true;
    var k: u32 = 0;
    while (k < 200) : (k += 1) {
        const big: [200]u8 = @splat(@truncate(k));
        _ = b.c[0].broadcast(&big);
        b.run(3, 1000, null);
    }
    // Over the limit, but not yet for a second.
    try expect(!b.relay.was_removed(2));
    b.run(3, 1_100_000, null);
    try expect(b.relay.was_removed(2));
    try expectEqual(@as(u16, 0b1), b.c[0].present);
    try expectEqual(@as(u32, 1), b.relay.stats.removed);
}

test "relay: a HELLO from a player in a room is a leave, then a fresh join" {
    // fork/CART_SERIAL.md (8ca6da6), as lobby.py does it: the others get the
    // ROSTER without the player before the one with it again.
    var b: Bench = undefined;
    b.init(&.{ "G", "G", "G" });
    for (0..3) |i| b.plug(i);
    b.run(3, 20_000, null);
    try expectEqual(@as(u16, 0b111), b.c[0].present);
    try expect(b.c[1].write_body(&b.c[1].hello_body()));
    var seen: [4]u16 = undefined;
    var n: usize = 0;
    var rejoined = false;
    const end = b.now + 30_000;
    while (b.now < end) {
        b.now += 1000;
        b.relay.advance(b.now);
        while (b.c[0].poll()) |ev| if (ev == .roster) {
            seen[n] = b.c[0].present;
            n += 1;
        };
        while (b.c[1].poll()) |ev| if (ev == .joined) {
            rejoined = true;
        };
        while (b.c[2].poll()) |_| {}
    }
    try expectEqual(@as(usize, 2), n);
    try expectEqual(@as(u16, 0b101), seen[0]);
    try expectEqual(@as(u16, 0b111), seen[1]);
    try expect(rejoined);
    try expectEqual(@as(?u8, 1), b.c[1].me());
    try expectEqual(@as(u8, 1), b.c[1].room); // rooms count from 1
}

// ---- frames.py vectors -----------------------------------------------------
//
// Generated by running the fork's reference encoders (sycl-badge-fork main
// 8ca6da6, `tools/badge/badge/frames.py`): `body` is `Message(...).pack()`,
// `wire` is `frames.encode(body)` (COBS + 0x00); `enc` is
// `frames.cobs_encode(raw)`. Bodies: HELLO game SNOUTDM1 name ADRIAN max
// 16, and DOTS / ABCDEFGHIJKL / 0; SEND to 0xFF [05 00 C0], to 0xFE [42],
// to 3 "hi", empty, 240 bytes (i * 7, zeros inside) and 240 bytes
// ((i % 255) + 1); PING 0x12345678 and 0; LEAVE; WELCOME you 2 room 1 max
// 16; ROSTER [(0, ADRIAN)] and [(i, "P<i>") for i in 0..15]; DATA from 3
// [05 00 C0], from 15 240 bytes (255 - i % 256, 0 every 50th); PONG
// 0xDEADBEEF; ERROR 3 "SEND before WELCOME"; ERROR 4 "x" * 300 (cut to
// the 250-byte body); unknown type 0x77 with 01..F9 (250 bytes).

const Vector = struct { name: []const u8, body: []const u8, wire: []const u8 };
const Cobs = struct { name: []const u8, raw: []const u8, enc: []const u8 };

/// Hex digits to bytes at comptime (whitespace and newlines skipped).
fn hex(comptime s: []const u8) []const u8 {
    comptime {
        @setEvalBranchQuota(100_000);
        var out: [s.len / 2]u8 = undefined;
        var n: usize = 0;
        var hi: ?u8 = null;
        for (s) |ch| {
            const v: u8 = switch (ch) {
                '0'...'9' => ch - '0',
                'A'...'F' => ch - 'A' + 10,
                'a'...'f' => ch - 'a' + 10,
                ' ', '\n' => continue,
                else => @compileError("hex: bad digit"),
            };
            if (hi) |h| {
                out[n] = h << 4 | v;
                n += 1;
                hi = null;
            } else hi = v;
        }
        if (hi != null) @compileError("hex: odd digit count");
        const final = out[0..n].*;
        return &final;
    }
}

fn vec(comptime name: []const u8) Vector {
    inline for (message_vectors) |v| {
        if (comptime std.mem.eql(u8, v.name, name)) return v;
    }
    @compileError("no vector " ++ name);
}

test "frames.py vectors: every v1 message encodes and decodes the same" {
    for (message_vectors) |v| {
        errdefer std.debug.print("vector: {s}\n", .{v.name});
        try expect(v.body.len <= party.max_body);
        var f: [party.max_frame]u8 = undefined;
        const n = party.encode_frame(v.body, &f);
        try expectEqualSlices(u8, v.wire, f[0..n]);
        try expect(n <= party.max_frame);
        // The streaming decoder, a byte at a time, gives the body back.
        var d: party.Decoder = .{};
        var out: [party.max_body]u8 = undefined;
        var got: ?usize = null;
        for (v.wire, 0..) |b, i| {
            const r = d.push(b, &out);
            if (i + 1 < v.wire.len) try expect(r == null) else got = r;
        }
        try expectEqualSlices(u8, v.body, out[0..got.?]);
        try expectEqual(@as(u32, 0), d.dropped);
    }
}

test "frames.py vectors: COBS edge cases" {
    for (cobs_vectors) |v| {
        errdefer std.debug.print("vector: {s}\n", .{v.name});
        var enc: [600]u8 = undefined;
        const n = party.cobs_encode(v.raw, &enc);
        try expectEqualSlices(u8, v.enc, enc[0..n]);
        try expect(n <= party.cobs_max(v.raw.len));
        var dec: [600]u8 = undefined;
        const m = party.cobs_decode(v.enc, &dec).?;
        try expectEqualSlices(u8, v.raw, dec[0..m]);
    }
    // A body one past the limit is dropped by the frame decoder (as
    // frames.FrameDecoder does), and the next frame still decodes.
    var d: party.Decoder = .{};
    var out: [party.max_body]u8 = undefined;
    var big: [party.max_body + 1]u8 = undefined;
    for (&big, 0..) |*b, i| b.* = @intCast(i % 255 + 1);
    var f: [party.cobs_max(party.max_body + 1) + 1]u8 = undefined;
    const n = party.encode_frame(&big, &f);
    for (f[0..n]) |b| try expect(d.push(b, &out) == null);
    try expectEqual(@as(u32, 1), d.dropped);
    const leave = vec("LEAVE").wire;
    for (leave[0 .. leave.len - 1]) |b| try expect(d.push(b, &out) == null);
    try expectEqual(@as(?usize, 1), d.push(0, &out));
}

test "frames.py vectors: the client writes every cart message byte for byte" {
    var c = Client.init(.{}, opts);
    c.port.host_open = true;
    _ = c.poll();
    var buf: [1024]u8 = undefined;
    const first = take(&c, &buf);
    try expectEqual(@as(u8, 0), first[0]); // the flush byte
    try expectEqualSlices(u8, vec("HELLO SNOUTDM1 ADRIAN 16").wire, first[1..]);
    var c2 = Client.init(.{}, .{ .game = party.pad(8, "DOTS"), .name = party.pad(12, "ABCDEFGHIJKLMNOP"), .max_players = 0 });
    try expectEqualSlices(u8, vec("HELLO full name, max 0").body, &c2.hello_body());

    put(&c, vec("WELCOME").wire);
    try expect(c.poll().? == .joined);
    try expect(c.broadcast(&.{ 0x05, 0x00, 0xC0 }));
    try expectEqualSlices(u8, vec("SEND to 0xFF").wire, take(&c, &buf));
    try expect(c.broadcast_echo(&.{0x42}));
    try expectEqualSlices(u8, vec("SEND to 0xFE").wire, take(&c, &buf));
    try expect(c.send(3, "hi"));
    try expectEqualSlices(u8, vec("SEND to 3").wire, take(&c, &buf));
    try expect(c.broadcast(&.{}));
    try expectEqualSlices(u8, vec("SEND empty to 0xFF").wire, take(&c, &buf));
    var data: [party.max_data]u8 = undefined;
    for (&data, 0..) |*b, i| b.* = @truncate(i * 7);
    try expect(c.broadcast(&data));
    try expectEqualSlices(u8, vec("SEND 240 bytes with zeros").wire, take(&c, &buf));
    for (&data, 0..) |*b, i| b.* = @intCast(i % 255 + 1);
    try expect(c.broadcast_echo(&data));
    try expectEqualSlices(u8, vec("SEND 240 bytes no zeros").wire, take(&c, &buf));
    try expect(c.ping(0x12345678));
    try expectEqualSlices(u8, vec("PING").wire, take(&c, &buf));
    try expect(c.ping(0));
    try expectEqualSlices(u8, vec("PING zero").wire, take(&c, &buf));
    c.leave();
    try expectEqualSlices(u8, vec("LEAVE").wire, take(&c, &buf));
}

test "frames.py vectors: the client reads every host message" {
    var c = Client.init(.{}, opts);
    c.port.host_open = true;
    _ = c.poll();
    var buf: [1024]u8 = undefined;
    _ = take(&c, &buf);
    put(&c, vec("WELCOME").wire);
    const w = c.poll().?.joined;
    try expectEqual(@as(u8, 2), w.you);
    try expectEqual(@as(u8, 1), w.room);
    try expectEqual(@as(u8, 16), w.max_players);
    put(&c, vec("ROSTER 1").wire);
    try expect(c.poll().? == .roster);
    try expectEqual(@as(u16, 0b1), c.present);
    try expectEqualSlices(u8, "ADRIAN", c.name(0));
    put(&c, vec("ROSTER 16").wire);
    try expect(c.poll().? == .roster);
    try expectEqual(@as(u16, 0xFFFF), c.present);
    try expectEqualSlices(u8, "P15", c.name(15));
    try expectEqualSlices(u8, "P2", c.name(2));
    put(&c, vec("DATA").wire);
    const d = c.poll().?.data;
    try expectEqual(@as(u8, 3), d.from);
    try expectEqualSlices(u8, &.{ 0x05, 0x00, 0xC0 }, d.bytes);
    put(&c, vec("DATA 240 bytes").wire);
    const d2 = c.poll().?.data;
    try expectEqual(@as(u8, 15), d2.from);
    try expectEqual(@as(usize, 240), d2.bytes.len);
    for (d2.bytes, 0..) |b, i| try expectEqual(@as(u8, if (i % 50 != 0) @intCast(255 - i % 256) else 0), b);
    put(&c, vec("PONG").wire);
    try expectEqual(@as(u32, 0xDEADBEEF), c.poll().?.pong);
    put(&c, vec("ERROR max body").wire);
    const e = c.poll().?.err;
    try expectEqual(party.Err.malformed, e.code);
    try expectEqual(@as(usize, party.max_body - 2), e.message.len);
    put(&c, vec("unknown max body").wire); // ignored (v1 rule)
    put(&c, vec("ERROR not joined").wire); // the host lost us: HELLO again
    const e2 = c.poll().?.err;
    try expectEqualSlices(u8, "SEND before WELCOME", e2.message);
    try expect(c.poll() == null);
    try expectEqualSlices(u8, vec("HELLO SNOUTDM1 ADRIAN 16").wire, take(&c, &buf));
    try expectEqual(@as(u32, 0), c.dec.dropped);
}

// zig fmt: off
const message_vectors = [_]Vector{
    .{ .name = "HELLO SNOUTDM1 ADRIAN 16", .body = hex("0101534E4F5554444D3141445249414E00000000000010"), .wire = hex("110101534E4F5554444D3141445249414E0101010101021000") },
    .{ .name = "HELLO full name, max 0", .body = hex("0101444F5453000000004142434445464748494A4B4C00"), .wire = hex("070101444F54530101010D4142434445464748494A4B4C0100") },
    .{ .name = "SEND to 0xFF", .body = hex("02FF0500C0"), .wire = hex("0402FF0502C000") },
    .{ .name = "SEND to 0xFE", .body = hex("02FE42"), .wire = hex("0402FE4200") },
    .{ .name = "SEND to 3", .body = hex("02036869"), .wire = hex("050203686900") },
    .{ .name = "SEND empty to 0xFF", .body = hex("02FF"), .wire = hex("0302FF00") },
    .{ .name = "SEND 240 bytes with zeros", .body = hex(
        \\02FF00070E151C232A31383F464D545B626970777E858C939AA1A8AFB6BDC4CBD2D9E0E7EEF5FC030A11181F262D343B
        \\424950575E656C737A81888F969DA4ABB2B9C0C7CED5DCE3EAF1F8FF060D141B222930373E454C535A61686F767D848B
        \\9299A0A7AEB5BCC3CAD1D8DFE6EDF4FB020910171E252C333A41484F565D646B727980878E959CA3AAB1B8BFC6CDD4DB
        \\E2E9F0F7FE050C131A21282F363D444B525960676E757C838A91989FA6ADB4BBC2C9D0D7DEE5ECF3FA01080F161D242B
        \\323940474E555C636A71787F868D949BA2A9B0B7BEC5CCD3DAE1E8EFF6FD040B121920272E353C434A51585F666D747B
        \\8289
    ), .wire = hex(
        \\0302FFF0070E151C232A31383F464D545B626970777E858C939AA1A8AFB6BDC4CBD2D9E0E7EEF5FC030A11181F262D34
        \\3B424950575E656C737A81888F969DA4ABB2B9C0C7CED5DCE3EAF1F8FF060D141B222930373E454C535A61686F767D84
        \\8B9299A0A7AEB5BCC3CAD1D8DFE6EDF4FB020910171E252C333A41484F565D646B727980878E959CA3AAB1B8BFC6CDD4
        \\DBE2E9F0F7FE050C131A21282F363D444B525960676E757C838A91989FA6ADB4BBC2C9D0D7DEE5ECF3FA01080F161D24
        \\2B323940474E555C636A71787F868D949BA2A9B0B7BEC5CCD3DAE1E8EFF6FD040B121920272E353C434A51585F666D74
        \\7B828900
    ) },
    .{ .name = "SEND 240 bytes no zeros", .body = hex(
        \\02FE0102030405060708090A0B0C0D0E0F101112131415161718191A1B1C1D1E1F202122232425262728292A2B2C2D2E
        \\2F303132333435363738393A3B3C3D3E3F404142434445464748494A4B4C4D4E4F505152535455565758595A5B5C5D5E
        \\5F606162636465666768696A6B6C6D6E6F707172737475767778797A7B7C7D7E7F808182838485868788898A8B8C8D8E
        \\8F909192939495969798999A9B9C9D9E9FA0A1A2A3A4A5A6A7A8A9AAABACADAEAFB0B1B2B3B4B5B6B7B8B9BABBBCBDBE
        \\BFC0C1C2C3C4C5C6C7C8C9CACBCCCDCECFD0D1D2D3D4D5D6D7D8D9DADBDCDDDEDFE0E1E2E3E4E5E6E7E8E9EAEBECEDEE
        \\EFF0
    ), .wire = hex(
        \\F302FE0102030405060708090A0B0C0D0E0F101112131415161718191A1B1C1D1E1F202122232425262728292A2B2C2D
        \\2E2F303132333435363738393A3B3C3D3E3F404142434445464748494A4B4C4D4E4F505152535455565758595A5B5C5D
        \\5E5F606162636465666768696A6B6C6D6E6F707172737475767778797A7B7C7D7E7F808182838485868788898A8B8C8D
        \\8E8F909192939495969798999A9B9C9D9E9FA0A1A2A3A4A5A6A7A8A9AAABACADAEAFB0B1B2B3B4B5B6B7B8B9BABBBCBD
        \\BEBFC0C1C2C3C4C5C6C7C8C9CACBCCCDCECFD0D1D2D3D4D5D6D7D8D9DADBDCDDDEDFE0E1E2E3E4E5E6E7E8E9EAEBECED
        \\EEEFF000
    ) },
    .{ .name = "PING", .body = hex("0378563412"), .wire = hex("06037856341200") },
    .{ .name = "PING zero", .body = hex("0300000000"), .wire = hex("02030101010100") },
    .{ .name = "LEAVE", .body = hex("04"), .wire = hex("020400") },
    .{ .name = "WELCOME", .body = hex("8101020110"), .wire = hex("06810102011000") },
    .{ .name = "ROSTER 1", .body = hex("82010041445249414E000000000000"), .wire = hex("0382010741445249414E01010101010100") },
    .{ .name = "ROSTER 16", .body = hex(
        \\821000503000000000000000000000015031000000000000000000000250320000000000000000000003503300000000
        \\000000000000045034000000000000000000000550350000000000000000000006503600000000000000000000075037
        \\0000000000000000000008503800000000000000000000095039000000000000000000000A5031300000000000000000
        \\000B5031310000000000000000000C5031320000000000000000000D5031330000000000000000000E50313400000000
        \\00000000000F503135000000000000000000
    ), .wire = hex(
        \\038210035030010101010101010101040150310101010101010101010402503201010101010101010104035033010101
        \\010101010101040450340101010101010101010405503501010101010101010104065036010101010101010101040750
        \\370101010101010101010408503801010101010101010104095039010101010101010101050A50313001010101010101
        \\01050B5031310101010101010101050C5031320101010101010101050D5031330101010101010101050E503134010101
        \\0101010101050F50313501010101010101010100
    ) },
    .{ .name = "DATA", .body = hex("83030500C0"), .wire = hex("0483030502C000") },
    .{ .name = "DATA 240 bytes", .body = hex(
        \\830F00FEFDFCFBFAF9F8F7F6F5F4F3F2F1F0EFEEEDECEBEAE9E8E7E6E5E4E3E2E1E0DFDEDDDCDBDAD9D8D7D6D5D4D3D2
        \\D1D0CFCE00CCCBCAC9C8C7C6C5C4C3C2C1C0BFBEBDBCBBBAB9B8B7B6B5B4B3B2B1B0AFAEADACABAAA9A8A7A6A5A4A3A2
        \\A1A09F9E9D9C009A999897969594939291908F8E8D8C8B8A898887868584838281807F7E7D7C7B7A7978777675747372
        \\71706F6E6D6C6B6A006867666564636261605F5E5D5C5B5A595857565554535251504F4E4D4C4B4A4948474645444342
        \\41403F3E3D3C3B3A393800363534333231302F2E2D2C2B2A292827262524232221201F1E1D1C1B1A1918171615141312
        \\1110
    ), .wire = hex(
        \\03830F32FEFDFCFBFAF9F8F7F6F5F4F3F2F1F0EFEEEDECEBEAE9E8E7E6E5E4E3E2E1E0DFDEDDDCDBDAD9D8D7D6D5D4D3
        \\D2D1D0CFCE32CCCBCAC9C8C7C6C5C4C3C2C1C0BFBEBDBCBBBAB9B8B7B6B5B4B3B2B1B0AFAEADACABAAA9A8A7A6A5A4A3
        \\A2A1A09F9E9D9C329A999897969594939291908F8E8D8C8B8A898887868584838281807F7E7D7C7B7A79787776757473
        \\7271706F6E6D6C6B6A326867666564636261605F5E5D5C5B5A595857565554535251504F4E4D4C4B4A49484746454443
        \\4241403F3E3D3C3B3A393828363534333231302F2E2D2C2B2A292827262524232221201F1E1D1C1B1A19181716151413
        \\12111000
    ) },
    .{ .name = "PONG", .body = hex("84EFBEADDE"), .wire = hex("0684EFBEADDE00") },
    .{ .name = "ERROR not joined", .body = hex("8F0353454E44206265666F72652057454C434F4D45"), .wire = hex("168F0353454E44206265666F72652057454C434F4D4500") },
    .{ .name = "ERROR max body", .body = hex(
        \\8F0478787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878
        \\787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878
        \\787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878
        \\787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878
        \\787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878
        \\78787878787878787878
    ), .wire = hex(
        \\FB8F04787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878
        \\787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878
        \\787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878
        \\787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878
        \\787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878
        \\787878787878787878787800
    ) },
    .{ .name = "unknown max body", .body = hex(
        \\770102030405060708090A0B0C0D0E0F101112131415161718191A1B1C1D1E1F202122232425262728292A2B2C2D2E2F
        \\303132333435363738393A3B3C3D3E3F404142434445464748494A4B4C4D4E4F505152535455565758595A5B5C5D5E5F
        \\606162636465666768696A6B6C6D6E6F707172737475767778797A7B7C7D7E7F808182838485868788898A8B8C8D8E8F
        \\909192939495969798999A9B9C9D9E9FA0A1A2A3A4A5A6A7A8A9AAABACADAEAFB0B1B2B3B4B5B6B7B8B9BABBBCBDBEBF
        \\C0C1C2C3C4C5C6C7C8C9CACBCCCDCECFD0D1D2D3D4D5D6D7D8D9DADBDCDDDEDFE0E1E2E3E4E5E6E7E8E9EAEBECEDEEEF
        \\F0F1F2F3F4F5F6F7F8F9
    ), .wire = hex(
        \\FB770102030405060708090A0B0C0D0E0F101112131415161718191A1B1C1D1E1F202122232425262728292A2B2C2D2E
        \\2F303132333435363738393A3B3C3D3E3F404142434445464748494A4B4C4D4E4F505152535455565758595A5B5C5D5E
        \\5F606162636465666768696A6B6C6D6E6F707172737475767778797A7B7C7D7E7F808182838485868788898A8B8C8D8E
        \\8F909192939495969798999A9B9C9D9E9FA0A1A2A3A4A5A6A7A8A9AAABACADAEAFB0B1B2B3B4B5B6B7B8B9BABBBCBDBE
        \\BFC0C1C2C3C4C5C6C7C8C9CACBCCCDCECFD0D1D2D3D4D5D6D7D8D9DADBDCDDDEDFE0E1E2E3E4E5E6E7E8E9EAEBECEDEE
        \\EFF0F1F2F3F4F5F6F7F8F900
    ) },
};
const cobs_vectors = [_]Cobs{
    .{ .name = "empty", .raw = hex(""), .enc = hex("01") },
    .{ .name = "one zero", .raw = hex("00"), .enc = hex("0101") },
    .{ .name = "five zeros", .raw = hex("0000000000"), .enc = hex("010101010101") },
    .{ .name = "253 non-zero", .raw = hex(
        \\0102030405060708090A0B0C0D0E0F101112131415161718191A1B1C1D1E1F202122232425262728292A2B2C2D2E2F30
        \\3132333435363738393A3B3C3D3E3F404142434445464748494A4B4C4D4E4F505152535455565758595A5B5C5D5E5F60
        \\6162636465666768696A6B6C6D6E6F707172737475767778797A7B7C7D7E7F808182838485868788898A8B8C8D8E8F90
        \\9192939495969798999A9B9C9D9E9FA0A1A2A3A4A5A6A7A8A9AAABACADAEAFB0B1B2B3B4B5B6B7B8B9BABBBCBDBEBFC0
        \\C1C2C3C4C5C6C7C8C9CACBCCCDCECFD0D1D2D3D4D5D6D7D8D9DADBDCDDDEDFE0E1E2E3E4E5E6E7E8E9EAEBECEDEEEFF0
        \\F1F2F3F4F5F6F7F8F9FAFBFCFD
    ), .enc = hex(
        \\FE0102030405060708090A0B0C0D0E0F101112131415161718191A1B1C1D1E1F202122232425262728292A2B2C2D2E2F
        \\303132333435363738393A3B3C3D3E3F404142434445464748494A4B4C4D4E4F505152535455565758595A5B5C5D5E5F
        \\606162636465666768696A6B6C6D6E6F707172737475767778797A7B7C7D7E7F808182838485868788898A8B8C8D8E8F
        \\909192939495969798999A9B9C9D9E9FA0A1A2A3A4A5A6A7A8A9AAABACADAEAFB0B1B2B3B4B5B6B7B8B9BABBBCBDBEBF
        \\C0C1C2C3C4C5C6C7C8C9CACBCCCDCECFD0D1D2D3D4D5D6D7D8D9DADBDCDDDEDFE0E1E2E3E4E5E6E7E8E9EAEBECEDEEEF
        \\F0F1F2F3F4F5F6F7F8F9FAFBFCFD
    ) },
    .{ .name = "254 non-zero", .raw = hex(
        \\0102030405060708090A0B0C0D0E0F101112131415161718191A1B1C1D1E1F202122232425262728292A2B2C2D2E2F30
        \\3132333435363738393A3B3C3D3E3F404142434445464748494A4B4C4D4E4F505152535455565758595A5B5C5D5E5F60
        \\6162636465666768696A6B6C6D6E6F707172737475767778797A7B7C7D7E7F808182838485868788898A8B8C8D8E8F90
        \\9192939495969798999A9B9C9D9E9FA0A1A2A3A4A5A6A7A8A9AAABACADAEAFB0B1B2B3B4B5B6B7B8B9BABBBCBDBEBFC0
        \\C1C2C3C4C5C6C7C8C9CACBCCCDCECFD0D1D2D3D4D5D6D7D8D9DADBDCDDDEDFE0E1E2E3E4E5E6E7E8E9EAEBECEDEEEFF0
        \\F1F2F3F4F5F6F7F8F9FAFBFCFDFE
    ), .enc = hex(
        \\FF0102030405060708090A0B0C0D0E0F101112131415161718191A1B1C1D1E1F202122232425262728292A2B2C2D2E2F
        \\303132333435363738393A3B3C3D3E3F404142434445464748494A4B4C4D4E4F505152535455565758595A5B5C5D5E5F
        \\606162636465666768696A6B6C6D6E6F707172737475767778797A7B7C7D7E7F808182838485868788898A8B8C8D8E8F
        \\909192939495969798999A9B9C9D9E9FA0A1A2A3A4A5A6A7A8A9AAABACADAEAFB0B1B2B3B4B5B6B7B8B9BABBBCBDBEBF
        \\C0C1C2C3C4C5C6C7C8C9CACBCCCDCECFD0D1D2D3D4D5D6D7D8D9DADBDCDDDEDFE0E1E2E3E4E5E6E7E8E9EAEBECEDEEEF
        \\F0F1F2F3F4F5F6F7F8F9FAFBFCFDFE01
    ) },
    .{ .name = "255 non-zero", .raw = hex(
        \\0102030405060708090A0B0C0D0E0F101112131415161718191A1B1C1D1E1F202122232425262728292A2B2C2D2E2F30
        \\3132333435363738393A3B3C3D3E3F404142434445464748494A4B4C4D4E4F505152535455565758595A5B5C5D5E5F60
        \\6162636465666768696A6B6C6D6E6F707172737475767778797A7B7C7D7E7F808182838485868788898A8B8C8D8E8F90
        \\9192939495969798999A9B9C9D9E9FA0A1A2A3A4A5A6A7A8A9AAABACADAEAFB0B1B2B3B4B5B6B7B8B9BABBBCBDBEBFC0
        \\C1C2C3C4C5C6C7C8C9CACBCCCDCECFD0D1D2D3D4D5D6D7D8D9DADBDCDDDEDFE0E1E2E3E4E5E6E7E8E9EAEBECEDEEEFF0
        \\F1F2F3F4F5F6F7F8F9FAFBFCFDFEFF
    ), .enc = hex(
        \\FF0102030405060708090A0B0C0D0E0F101112131415161718191A1B1C1D1E1F202122232425262728292A2B2C2D2E2F
        \\303132333435363738393A3B3C3D3E3F404142434445464748494A4B4C4D4E4F505152535455565758595A5B5C5D5E5F
        \\606162636465666768696A6B6C6D6E6F707172737475767778797A7B7C7D7E7F808182838485868788898A8B8C8D8E8F
        \\909192939495969798999A9B9C9D9E9FA0A1A2A3A4A5A6A7A8A9AAABACADAEAFB0B1B2B3B4B5B6B7B8B9BABBBCBDBEBF
        \\C0C1C2C3C4C5C6C7C8C9CACBCCCDCECFD0D1D2D3D4D5D6D7D8D9DADBDCDDDEDFE0E1E2E3E4E5E6E7E8E9EAEBECEDEEEF
        \\F0F1F2F3F4F5F6F7F8F9FAFBFCFDFE02FF
    ) },
    .{ .name = "254 non-zero, a zero", .raw = hex(
        \\0102030405060708090A0B0C0D0E0F101112131415161718191A1B1C1D1E1F202122232425262728292A2B2C2D2E2F30
        \\3132333435363738393A3B3C3D3E3F404142434445464748494A4B4C4D4E4F505152535455565758595A5B5C5D5E5F60
        \\6162636465666768696A6B6C6D6E6F707172737475767778797A7B7C7D7E7F808182838485868788898A8B8C8D8E8F90
        \\9192939495969798999A9B9C9D9E9FA0A1A2A3A4A5A6A7A8A9AAABACADAEAFB0B1B2B3B4B5B6B7B8B9BABBBCBDBEBFC0
        \\C1C2C3C4C5C6C7C8C9CACBCCCDCECFD0D1D2D3D4D5D6D7D8D9DADBDCDDDEDFE0E1E2E3E4E5E6E7E8E9EAEBECEDEEEFF0
        \\F1F2F3F4F5F6F7F8F9FAFBFCFDFE00
    ), .enc = hex(
        \\FF0102030405060708090A0B0C0D0E0F101112131415161718191A1B1C1D1E1F202122232425262728292A2B2C2D2E2F
        \\303132333435363738393A3B3C3D3E3F404142434445464748494A4B4C4D4E4F505152535455565758595A5B5C5D5E5F
        \\606162636465666768696A6B6C6D6E6F707172737475767778797A7B7C7D7E7F808182838485868788898A8B8C8D8E8F
        \\909192939495969798999A9B9C9D9E9FA0A1A2A3A4A5A6A7A8A9AAABACADAEAFB0B1B2B3B4B5B6B7B8B9BABBBCBDBEBF
        \\C0C1C2C3C4C5C6C7C8C9CACBCCCDCECFD0D1D2D3D4D5D6D7D8D9DADBDCDDDEDFE0E1E2E3E4E5E6E7E8E9EAEBECEDEEEF
        \\F0F1F2F3F4F5F6F7F8F9FAFBFCFDFE0101
    ) },
    .{ .name = "a zero, 254 non-zero", .raw = hex(
        \\000102030405060708090A0B0C0D0E0F101112131415161718191A1B1C1D1E1F202122232425262728292A2B2C2D2E2F
        \\303132333435363738393A3B3C3D3E3F404142434445464748494A4B4C4D4E4F505152535455565758595A5B5C5D5E5F
        \\606162636465666768696A6B6C6D6E6F707172737475767778797A7B7C7D7E7F808182838485868788898A8B8C8D8E8F
        \\909192939495969798999A9B9C9D9E9FA0A1A2A3A4A5A6A7A8A9AAABACADAEAFB0B1B2B3B4B5B6B7B8B9BABBBCBDBEBF
        \\C0C1C2C3C4C5C6C7C8C9CACBCCCDCECFD0D1D2D3D4D5D6D7D8D9DADBDCDDDEDFE0E1E2E3E4E5E6E7E8E9EAEBECEDEEEF
        \\F0F1F2F3F4F5F6F7F8F9FAFBFCFDFE
    ), .enc = hex(
        \\01FF0102030405060708090A0B0C0D0E0F101112131415161718191A1B1C1D1E1F202122232425262728292A2B2C2D2E
        \\2F303132333435363738393A3B3C3D3E3F404142434445464748494A4B4C4D4E4F505152535455565758595A5B5C5D5E
        \\5F606162636465666768696A6B6C6D6E6F707172737475767778797A7B7C7D7E7F808182838485868788898A8B8C8D8E
        \\8F909192939495969798999A9B9C9D9E9FA0A1A2A3A4A5A6A7A8A9AAABACADAEAFB0B1B2B3B4B5B6B7B8B9BABBBCBDBE
        \\BFC0C1C2C3C4C5C6C7C8C9CACBCCCDCECFD0D1D2D3D4D5D6D7D8D9DADBDCDDDEDFE0E1E2E3E4E5E6E7E8E9EAEBECEDEE
        \\EFF0F1F2F3F4F5F6F7F8F9FAFBFCFDFE01
    ) },
    .{ .name = "508 non-zero", .raw = hex(
        \\0102030405060708090A0B0C0D0E0F101112131415161718191A1B1C1D1E1F202122232425262728292A2B2C2D2E2F30
        \\3132333435363738393A3B3C3D3E3F404142434445464748494A4B4C4D4E4F505152535455565758595A5B5C5D5E5F60
        \\6162636465666768696A6B6C6D6E6F707172737475767778797A7B7C7D7E7F808182838485868788898A8B8C8D8E8F90
        \\9192939495969798999A9B9C9D9E9FA0A1A2A3A4A5A6A7A8A9AAABACADAEAFB0B1B2B3B4B5B6B7B8B9BABBBCBDBEBFC0
        \\C1C2C3C4C5C6C7C8C9CACBCCCDCECFD0D1D2D3D4D5D6D7D8D9DADBDCDDDEDFE0E1E2E3E4E5E6E7E8E9EAEBECEDEEEFF0
        \\F1F2F3F4F5F6F7F8F9FAFBFCFDFEFF0102030405060708090A0B0C0D0E0F101112131415161718191A1B1C1D1E1F2021
        \\22232425262728292A2B2C2D2E2F303132333435363738393A3B3C3D3E3F404142434445464748494A4B4C4D4E4F5051
        \\52535455565758595A5B5C5D5E5F606162636465666768696A6B6C6D6E6F707172737475767778797A7B7C7D7E7F8081
        \\82838485868788898A8B8C8D8E8F909192939495969798999A9B9C9D9E9FA0A1A2A3A4A5A6A7A8A9AAABACADAEAFB0B1
        \\B2B3B4B5B6B7B8B9BABBBCBDBEBFC0C1C2C3C4C5C6C7C8C9CACBCCCDCECFD0D1D2D3D4D5D6D7D8D9DADBDCDDDEDFE0E1
        \\E2E3E4E5E6E7E8E9EAEBECEDEEEFF0F1F2F3F4F5F6F7F8F9FAFBFCFD
    ), .enc = hex(
        \\FF0102030405060708090A0B0C0D0E0F101112131415161718191A1B1C1D1E1F202122232425262728292A2B2C2D2E2F
        \\303132333435363738393A3B3C3D3E3F404142434445464748494A4B4C4D4E4F505152535455565758595A5B5C5D5E5F
        \\606162636465666768696A6B6C6D6E6F707172737475767778797A7B7C7D7E7F808182838485868788898A8B8C8D8E8F
        \\909192939495969798999A9B9C9D9E9FA0A1A2A3A4A5A6A7A8A9AAABACADAEAFB0B1B2B3B4B5B6B7B8B9BABBBCBDBEBF
        \\C0C1C2C3C4C5C6C7C8C9CACBCCCDCECFD0D1D2D3D4D5D6D7D8D9DADBDCDDDEDFE0E1E2E3E4E5E6E7E8E9EAEBECEDEEEF
        \\F0F1F2F3F4F5F6F7F8F9FAFBFCFDFEFFFF0102030405060708090A0B0C0D0E0F101112131415161718191A1B1C1D1E1F
        \\202122232425262728292A2B2C2D2E2F303132333435363738393A3B3C3D3E3F404142434445464748494A4B4C4D4E4F
        \\505152535455565758595A5B5C5D5E5F606162636465666768696A6B6C6D6E6F707172737475767778797A7B7C7D7E7F
        \\808182838485868788898A8B8C8D8E8F909192939495969798999A9B9C9D9E9FA0A1A2A3A4A5A6A7A8A9AAABACADAEAF
        \\B0B1B2B3B4B5B6B7B8B9BABBBCBDBEBFC0C1C2C3C4C5C6C7C8C9CACBCCCDCECFD0D1D2D3D4D5D6D7D8D9DADBDCDDDEDF
        \\E0E1E2E3E4E5E6E7E8E9EAEBECEDEEEFF0F1F2F3F4F5F6F7F8F9FAFBFCFD01
    ) },
    .{ .name = "250 non-zero", .raw = hex(
        \\0102030405060708090A0B0C0D0E0F101112131415161718191A1B1C1D1E1F202122232425262728292A2B2C2D2E2F30
        \\3132333435363738393A3B3C3D3E3F404142434445464748494A4B4C4D4E4F505152535455565758595A5B5C5D5E5F60
        \\6162636465666768696A6B6C6D6E6F707172737475767778797A7B7C7D7E7F808182838485868788898A8B8C8D8E8F90
        \\9192939495969798999A9B9C9D9E9FA0A1A2A3A4A5A6A7A8A9AAABACADAEAFB0B1B2B3B4B5B6B7B8B9BABBBCBDBEBFC0
        \\C1C2C3C4C5C6C7C8C9CACBCCCDCECFD0D1D2D3D4D5D6D7D8D9DADBDCDDDEDFE0E1E2E3E4E5E6E7E8E9EAEBECEDEEEFF0
        \\F1F2F3F4F5F6F7F8F9FA
    ), .enc = hex(
        \\FB0102030405060708090A0B0C0D0E0F101112131415161718191A1B1C1D1E1F202122232425262728292A2B2C2D2E2F
        \\303132333435363738393A3B3C3D3E3F404142434445464748494A4B4C4D4E4F505152535455565758595A5B5C5D5E5F
        \\606162636465666768696A6B6C6D6E6F707172737475767778797A7B7C7D7E7F808182838485868788898A8B8C8D8E8F
        \\909192939495969798999A9B9C9D9E9FA0A1A2A3A4A5A6A7A8A9AAABACADAEAFB0B1B2B3B4B5B6B7B8B9BABBBCBDBEBF
        \\C0C1C2C3C4C5C6C7C8C9CACBCCCDCECFD0D1D2D3D4D5D6D7D8D9DADBDCDDDEDFE0E1E2E3E4E5E6E7E8E9EAEBECEDEEEF
        \\F0F1F2F3F4F5F6F7F8F9FA
    ) },
    .{ .name = "250 zeros", .raw = hex(
        \\000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
        \\000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
        \\000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
        \\000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
        \\000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
        \\00000000000000000000
    ), .enc = hex(
        \\010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101
        \\010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101
        \\010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101
        \\010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101
        \\010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101
        \\0101010101010101010101
    ) },
};
// zig fmt: on
