#!/usr/bin/env python3
"""Generate core/vdp_tables.zig: the VDP's screen mapping tables (SPEC.md
section 6).

  python3 carts/snouty-genesis/tools/gen_vdp_tables.py

- `col_h40[i]` / `col_h32[i]`: the Genesis screen column shown in badge
  column i (H40: 2i; H32: i * 8 / 5).
- `first_h40[x]` / `first_h32[x]`: the first badge column whose Genesis
  column is >= x (160 when none), x = 0 .. screen width. Sprite and window
  spans turn screen-x ranges into badge-column ranges with it.
- `line_squeeze[r]` / `line_crop[r]`: the Genesis line shown in badge row r
  (r * 7 / 4, or 48 + r); `row_squeeze[l]` / `row_crop[l]`: the inverse
  over lines 0..223, 0xFF for a line that is not shown.

Literal data because heavy comptime table building runs Adrian's Mac Zig
out of memory (CLAUDE.md). Genesis tiles are packed 4bpp (two pixels per
byte, left pixel in the high nibble), so unlike Snouty Gear's planar mode 4
no bit-spread table is needed: the renderer shifts nibbles out of one
big-endian 32-bit row word.
"""
import os
import shutil
import subprocess

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "core", "vdp_tables.zig")
OUT_W = 160
OUT_H = 128
ACTIVE = 224


def fmt(name, doc, typ, values, per_line=16):
    lines = [f"/// {doc}", f"pub const {name} = [{len(values)}]{typ}{{"]
    for i in range(0, len(values), per_line):
        lines.append("    " + " ".join(f"{v}," for v in values[i:i + per_line]))
    lines.append("};")
    return "\n".join(lines)


def first_col(cols, width):
    out = []
    for x in range(width + 1):
        i = next((k for k, c in enumerate(cols) if c >= x), OUT_W)
        out.append(i)
    return out


def inverse(rows):
    inv = [0xFF] * ACTIVE
    for r, l in enumerate(rows):
        inv[l] = r
    return inv


def main():
    col_h40 = [2 * i for i in range(OUT_W)]
    col_h32 = [i * 8 // 5 for i in range(OUT_W)]
    squeeze = [r * 7 // 4 for r in range(OUT_H)]
    crop = [48 + r for r in range(OUT_H)]
    assert max(col_h32) < 256 and max(squeeze) < ACTIVE
    parts = [
        "//! Generated by tools/gen_vdp_tables.py; do not edit.",
        "//! Badge column and row to Genesis column and line (SPEC.md section 6).",
        "",
        fmt("col_h40", "H40: badge column i shows Genesis column 2i.", "u16", col_h40),
        "",
        fmt("col_h32", "H32: badge column i shows Genesis column i * 8 / 5.", "u16", col_h32),
        "",
        fmt("first_h40", "H40: first badge column showing Genesis column >= x (x = 0..320).", "u8", first_col(col_h40, 320)),
        "",
        fmt("first_h32", "H32: first badge column showing Genesis column >= x (x = 0..256).", "u8", first_col(col_h32, 256)),
        "",
        fmt("line_squeeze", "Squeeze: badge row r shows Genesis line r * 7 / 4.", "u8", squeeze),
        "",
        fmt("line_crop", "Crop: badge row r shows Genesis line 48 + r.", "u8", crop),
        "",
        fmt("row_squeeze", "Squeeze: the badge row showing line l, 0xFF when none.", "u8", inverse(squeeze)),
        "",
        fmt("row_crop", "Crop: the badge row showing line l, 0xFF when none.", "u8", inverse(crop)),
        "",
    ]
    with open(OUT, "w") as f:
        f.write("\n".join(parts))
    # Commit the zig fmt layout (it column-aligns array literals).
    zig = shutil.which("zig") or os.path.expanduser("~/.local/bin/zig")
    if os.path.exists(zig):
        subprocess.run([zig, "fmt", OUT], check=True, stdout=subprocess.DEVNULL)


if __name__ == "__main__":
    main()
