#!/usr/bin/env python3
"""Generate core/ym_tables.zig: the YM2612 log-sine and exponent tables and
the SN76489 attenuation table (no float in the core and no heavy comptime:
Adrian's Mac compiler runs out of memory, CLAUDE.md). Run from the cart
directory: python3 tools/gen_ym_tables.py > core/ym_tables.zig

Sources: the log-sine / exponent decomposition of the OPN family as the
YM2612 thread on SpritesMind (Nemesis, 2008-2009) describes it: an
operator looks up -log2(sin) of its quarter-wave phase (8 bits) in 4.8
fixed point, adds its attenuation (envelope + TL, 10 bits, << 2), and
converts back with 2^-x (fraction from a table, integer part a shift).
The PSG attenuation is 2 dB per step (SN76489 datasheet; SMS Power
"SN76489" page), step 15 off.
"""
import math

PSG_MAX = 2600  # one PSG channel's full scale, in FM operator units (+-8191)

logsin = [min(4095, round(-math.log2(math.sin((2 * i + 1) * math.pi / 1024)) * 256)) for i in range(256)]
exp = [round(8191 * 2 ** (-i / 256)) for i in range(256)]
psg = [round(PSG_MAX * 10 ** (-2 * i / 20)) for i in range(15)] + [0]

def rows(name, ty, vals, per=16):
    out = [f"pub const {name} = [{len(vals)}]{ty}{{"]
    for k in range(0, len(vals), per):
        out.append("    " + ", ".join(str(v) for v in vals[k:k + per]) + ",")
    out.append("};")
    return "\n".join(out)

print("//! Generated by tools/gen_ym_tables.py; do not edit.")
print("")
print("/// -log2(sin((2i+1) pi / 1024)) in 4.8 fixed point: a quarter sine wave.")
print(rows("logsin", "u16", logsin))
print("")
print("/// 8191 * 2^(-i/256): the fraction of the exponent; the integer part shifts.")
print(rows("exp", "u16", exp))
print("")
print(f"/// SN76489 attenuation steps of 2 dB from {PSG_MAX} (15 = off).")
print(rows("psg_vol", "u16", psg))
