#!/usr/bin/env python3
"""Generate core/tables.zig: the Z80 flag lookup tables as literal arrays.

Adrian's Mac Zig runs out of memory on comptime table building, so the
tables are data emitted here and committed. Run from anywhere:

    python3 carts/snouty-gear/tools/gen_tables.py

Tables (256 bytes each, 1 KB total), indexed by an 8-bit result:
  sz53    S, Z, and the undocumented Y (bit 5) and X (bit 3) copies
  sz53p   sz53 plus P/V as even parity
  inc     flags of INC r for result r, except C (kept by the caller)
  dec     flags of DEC r for result r, except C
"""
import os

S, Z, Y, H, X, P, N, C = 0x80, 0x40, 0x20, 0x10, 0x08, 0x04, 0x02, 0x01


def sz53(v):
    return (v & (S | Y | X)) | (Z if v == 0 else 0)


def parity(v):
    return P if bin(v).count("1") % 2 == 0 else 0


def inc(r):
    return sz53(r) | (P if r == 0x80 else 0) | (H if (r & 0x0F) == 0 else 0)


def dec(r):
    return sz53(r) | N | (P if r == 0x7F else 0) | (H if (r & 0x0F) == 0x0F else 0)


def emit(name, doc, values):
    lines = [f"/// {doc}", f"pub const {name} = [256]u8{{"]
    for i in range(0, 256, 16):
        lines.append("    " + " ".join(f"0x{v:02X}," for v in values[i : i + 16]))
    lines.append("};")
    return "\n".join(lines)


def main():
    out = [
        "//! Generated by tools/gen_tables.py; do not edit. Z80 flag lookup",
        "//! tables as literal data (no comptime table building, see CLAUDE.md).",
        "//! Flag bits: S 0x80, Z 0x40, Y 0x20, H 0x10, X 0x08, P/V 0x04, N 0x02, C 0x01.",
        "",
        emit("sz53", "S, Z, Y, X of an 8-bit result.", [sz53(v) for v in range(256)]),
        "",
        emit("sz53p", "S, Z, Y, X and even parity of an 8-bit result.", [sz53(v) | parity(v) for v in range(256)]),
        "",
        emit("inc", "INC r flags for result r, all but C.", [inc(v) for v in range(256)]),
        "",
        emit("dec", "DEC r flags for result r, all but C.", [dec(v) for v in range(256)]),
        "",
    ]
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "core", "tables.zig")
    with open(path, "w") as f:
        f.write("\n".join(out))


if __name__ == "__main__":
    main()
