#!/usr/bin/env python3
"""Generate core/vdp_tables.zig: the VDP's planar-to-packed bit-spread tables.

  python3 carts/snouty-gear/tools/gen_vdp_tables.py

A mode 4 tile row is four plane bytes; pixel i (0 = leftmost) takes bit
(7 - i) of each plane. `spread[b]` puts bit (7 - i) of `b` at bit 4*i, so

    row = spread[p0] | spread[p1] << 1 | spread[p2] << 2 | spread[p3] << 3

holds pixel i's 4-bit colour in nibble i. `spread_rev` is the same with the
pixel order reversed (horizontal flip). Literal data because heavy comptime
table building runs Adrian's Mac Zig out of memory (CLAUDE.md).
"""
import os

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "core", "vdp_tables.zig")


def spread(b, rev):
    v = 0
    for i in range(8):
        bit = (b >> i) & 1 if rev else (b >> (7 - i)) & 1
        v |= bit << (4 * i)
    return v


def table(name, doc, rev):
    lines = [f"/// {doc}", f"pub const {name} = [256]u32{{"]
    for row in range(0, 256, 8):
        lines.append("    " + " ".join(f"0x{spread(b, rev):08X}," for b in range(row, row + 8)))
    lines.append("};")
    return "\n".join(lines)


def main():
    parts = [
        "//! Generated by tools/gen_vdp_tables.py; do not edit.",
        "//! Planar tile row -> eight packed 4-bit pixels (nibble i = pixel i).",
        "",
        table("spread", "Bit (7 - i) of the index at bit 4*i: pixel order as stored.", False),
        "",
        table("spread_rev", "Bit i of the index at bit 4*i: horizontally flipped.", True),
        "",
    ]
    with open(OUT, "w") as f:
        f.write("\n".join(parts))


if __name__ == "__main__":
    main()
