//! GENERATED by tools/gen_demo.py from tools/scripts/demo_build_farm.json; do not edit.
//! Attract-mode demo: a fixed seed plus a run-length input log (SPEC.md 11,
//! PLAN.md M5). Bit layout of `buttons` is cart.Controls / state.Buttons.
pub const Run = struct { buttons: u16, ticks: u16 };

pub const level_index: u8 = 2;
pub const seed: u32 = 0x5EED0001;
pub const total_ticks: u32 = 4108;
/// sim.hash_gameplay of the state after the last tick as recorded in the
/// simulator; 0 = not recorded yet (tools/record_demo.sh).
pub const final_hash: u32 = 0x10A0860C;

pub const runs = [_]Run{
    .{ .buttons = 0x0000, .ticks = 30 },
    .{ .buttons = 0x0020, .ticks = 255 },
    .{ .buttons = 0x0004, .ticks = 194 },
    .{ .buttons = 0x0020, .ticks = 33 },
    .{ .buttons = 0x0080, .ticks = 36 },
    .{ .buttons = 0x0020, .ticks = 44 },
    .{ .buttons = 0x0100, .ticks = 53 },
    .{ .buttons = 0x0004, .ticks = 75 },
    .{ .buttons = 0x0080, .ticks = 7 },
    .{ .buttons = 0x0020, .ticks = 200 },
    .{ .buttons = 0x0080, .ticks = 10 },
    .{ .buttons = 0x0020, .ticks = 284 },
    .{ .buttons = 0x0008, .ticks = 210 },
    .{ .buttons = 0x0040, .ticks = 10 },
    .{ .buttons = 0x0004, .ticks = 242 },
    .{ .buttons = 0x0000, .ticks = 20 },
    .{ .buttons = 0x0100, .ticks = 5 },
    .{ .buttons = 0x0020, .ticks = 312 },
    .{ .buttons = 0x0000, .ticks = 40 },
    .{ .buttons = 0x0100, .ticks = 65 },
    .{ .buttons = 0x0020, .ticks = 268 },
    .{ .buttons = 0x0100, .ticks = 31 },
    .{ .buttons = 0x0020, .ticks = 93 },
    .{ .buttons = 0x0080, .ticks = 29 },
    .{ .buttons = 0x0020, .ticks = 216 },
    .{ .buttons = 0x0080, .ticks = 36 },
    .{ .buttons = 0x0020, .ticks = 130 },
    .{ .buttons = 0x0100, .ticks = 18 },
    .{ .buttons = 0x0020, .ticks = 65 },
    .{ .buttons = 0x0024, .ticks = 15 },
    .{ .buttons = 0x0104, .ticks = 10 },
    .{ .buttons = 0x0100, .ticks = 4 },
    .{ .buttons = 0x0004, .ticks = 85 },
    .{ .buttons = 0x0002, .ticks = 1 },
    .{ .buttons = 0x0000, .ticks = 70 },
    .{ .buttons = 0x0004, .ticks = 30 },
    .{ .buttons = 0x0000, .ticks = 20 },
    .{ .buttons = 0x0100, .ticks = 5 },
    .{ .buttons = 0x0020, .ticks = 220 },
    .{ .buttons = 0x0000, .ticks = 40 },
    .{ .buttons = 0x0080, .ticks = 55 },
    .{ .buttons = 0x0020, .ticks = 256 },
    .{ .buttons = 0x0100, .ticks = 4 },
    .{ .buttons = 0x0004, .ticks = 28 },
    .{ .buttons = 0x0000, .ticks = 12 },
    .{ .buttons = 0x0080, .ticks = 27 },
    .{ .buttons = 0x0020, .ticks = 115 },
    .{ .buttons = 0x0000, .ticks = 100 },
};
