//! GENERATED by tools/gen_demo.py from tools/scripts/demo_build_farm.json; do not edit.
//! Attract-mode demo: a fixed seed plus a run-length input log (SPEC.md 11,
//! PLAN.md M5). Bit layout of `buttons` is cart.Controls / state.Buttons.
pub const Run = struct { buttons: u16, ticks: u16 };

pub const level_index: u8 = 0;
pub const seed: u32 = 0x5EED0001;
pub const total_ticks: u32 = 180;
/// sim.hash_gameplay of the state after the last tick as recorded in the
/// simulator; 0 = not recorded yet (tools/record_demo.sh).
pub const final_hash: u32 = 0x0E80BADF;

pub const runs = [_]Run{
    .{ .buttons = 0x0000, .ticks = 60 },
    .{ .buttons = 0x0100, .ticks = 36 },
    .{ .buttons = 0x0080, .ticks = 36 },
    .{ .buttons = 0x0000, .ticks = 48 },
};
