#!/usr/bin/env python3
"""Writes cart/src/gen/name_font.zig: the capitals A-Z of Nimbus Sans
Narrow Bold at 27 px (caps 20 px tall), rendered in greyscale and
thresholded at 50%, cropped to their ink. Each glyph is `width` u32 column
words, bit 0 the top row. Run from carts/siwoo/ and commit the result:

    python3 tools/gen_name_font.py

Also writes docs/name_font.png, every glyph at 4x, for review.
"""
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

FONT = "/usr/share/fonts/opentype/urw-base35/NimbusSansNarrow-Bold.otf"
SIZE = 27
LETTERS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"

font = ImageFont.truetype(FONT, SIZE)
# The cap height from H, with the baseline at the bottom of H's ink.
probe = Image.new("L", (80, 80))
ImageDraw.Draw(probe).text((10, 10), "H", font=font, fill=255)
top, bottom = probe.getbbox()[1], probe.getbbox()[3]
height = bottom - top

glyphs = []
for c in LETTERS:
    im = Image.new("L", (80, 80))
    ImageDraw.Draw(im).text((10, 10), c, font=font, fill=255)
    bw = im.point(lambda v: 255 if v >= 128 else 0)
    x0, _, x1, _ = bw.getbbox()
    cols = []
    for x in range(x0, x1):
        word = 0
        for y in range(height):
            if bw.getpixel((x, top + y)):
                word |= 1 << y
        cols.append(word)
    lost = sum(1 for x in range(x0, x1) for y in range(80)
               if bw.getpixel((x, y)) and not (top <= y < bottom))
    glyphs.append((c, cols, lost))

here = Path(__file__).resolve().parent.parent
out = here / "cart/src/gen/name_font.zig"
lines = [
    "//! Generated by tools/gen_name_font.py; do not edit. Rerun and commit to change.",
    f"//! Nimbus Sans Narrow Bold {SIZE} px, capitals {height} px tall, thresholded at 50%,",
    "//! each glyph cropped to its ink. A glyph is `columns.len` u32 column words;",
    "//! bit 0 is the top row.",
    "",
    f"pub const height = {height};",
    "",
    "/// Column words of capital `c` ('A'..'Z'); anything else has none.",
    "pub fn glyph(c: u8) []const u32 {",
    "    if (c < 'A' or c > 'Z') return &.{};",
    "    return letters[c - 'A'];",
    "}",
    "",
    "const letters = [26][]const u32{",
]
for c, cols, lost in glyphs:
    note = f" // {c}" + (f", {lost} px clipped" if lost else "")
    lines.append(f"    &.{{ {', '.join(f'0x{w:05x}' for w in cols)} }},{note}")
lines += ["};", ""]
out.write_text("\n".join(lines))

# Review sheet.
scale = 4
sheet_w = sum(len(cols) + 2 for _, cols, _ in glyphs) + 2
sheet = Image.new("RGB", (sheet_w * scale, (height + 4) * scale), (16, 12, 32))
d = ImageDraw.Draw(sheet)
x = 2
for _, cols, _ in glyphs:
    for i, w in enumerate(cols):
        for y in range(height):
            if w >> y & 1:
                d.rectangle([(x + i) * scale, (y + 2) * scale, (x + i + 1) * scale - 1, (y + 3) * scale - 1], fill=(62, 207, 142))
    x += len(cols) + 2
sheet.save(here / "docs/name_font.png")
print(f"height {height}, wrote {out}")
