#!/usr/bin/env python3
"""Write cart/src/gen/tables.zig: the trombone's constant tables.

    python3 tools/gen_tables.py          # rewrite the file
    python3 tools/gen_tables.py --check  # exit 1 if the committed file differs

Generated on the host and committed (repository CLAUDE.md: heavy comptime
fails on Adrian's Mac, so no comptime maths):

- base_inc_q8: the phase increment of MIDI note 0 (8.1758 Hz) at 44.1 kHz
  for a 32-bit phase, times 256 (as the theremin).
- semitone_q30: 2^(s/12) for s = 0..11, Q30.
- cent_q30: 2^(c/1200) for c = 0..99, Q30.
- partial_cents: 1200 log2(n) for the harmonic series n = 0..8 (n = 0
  unused), rounded to whole cents: the 7th partial is the real horn's,
  31 cents flat of equal temperament.
- svf_f_q15: the Chamberlin state-variable filter's frequency coefficient
  2 sin(pi fc / fs) in Q15 for fc = 50 Hz * 2^(i/8), i = 0..63 (eighth
  octaves from 50 Hz to ~11.7 kHz): the voice moves its cutoff in eighth
  octaves (brightness with level, the plunger mute) and interpolates.
"""
import math
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "cart", "src", "gen", "tables.zig")
RATE = 44100
SVF_BASE_HZ = 50.0
SVF_STEPS = 64


def render() -> str:
    semi = [round((2 ** (s / 12)) * (1 << 30)) for s in range(12)]
    cent = [round((2 ** (c / 1200)) * (1 << 30)) for c in range(100)]
    midi0 = 440.0 * 2 ** (-69 / 12)
    base = round(midi0 * (1 << 40) / RATE)
    partial = [0] + [round(1200 * math.log2(n)) for n in range(1, 9)]
    svf = []
    for i in range(SVF_STEPS):
        fc = SVF_BASE_HZ * 2 ** (i / 8)
        f = 2 * math.sin(math.pi * min(fc, RATE / 6) / RATE)
        svf.append(round(f * 32768))
    out = []
    out.append("//! Generated by tools/gen_tables.py; do not edit by hand.")
    out.append("//! 2^(s/12) and 2^(c/1200) in Q30, the 32-bit phase increment of MIDI")
    out.append("//! note 0 at 44.1 kHz times 256, the harmonic series in cents and the")
    out.append("//! state-variable filter's coefficient per eighth octave from 50 Hz.")
    out.append("")
    out.append(f"pub const base_inc_q8: u32 = {base};")
    out.append(f"pub const svf_base_hz: u32 = {int(SVF_BASE_HZ)};")
    out.append("")
    # One value per line: zig fmt aligns multi-value rows into columns.
    out.append("pub const semitone_q30 = [12]u32{")
    out.extend(f"    {v}," for v in semi)
    out.append("};")
    out.append("")
    out.append("pub const cent_q30 = [100]u32{")
    out.extend(f"    {v}," for v in cent)
    out.append("};")
    out.append("")
    out.append("pub const partial_cents = [9]i32{")
    out.extend(f"    {v}," for v in partial)
    out.append("};")
    out.append("")
    out.append(f"pub const svf_f_q15 = [{SVF_STEPS}]i32{{")
    out.extend(f"    {v}," for v in svf)
    out.append("};")
    out.append("")
    return "\n".join(out)


def main() -> int:
    text = render()
    if "--check" in sys.argv[1:]:
        try:
            with open(OUT) as f:
                ok = f.read() == text
        except FileNotFoundError:
            ok = False
        print("gen_tables: " + ("up to date" if ok else "cart/src/gen/tables.zig differs; run tools/gen_tables.py"))
        return 0 if ok else 1
    with open(OUT, "w") as f:
        f.write(text)
    print(f"gen_tables: wrote {os.path.relpath(OUT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
